#99129 Theme Color for git staged files.
microsoft/vscode pull request #100129
Opened 2020-06-14 17:26 UTC by codingonHP

Introduce a new status 'S' and corresponding theme color to easily identify resources that are staged
in git and explorer view.

This PR fixes #99129

2020-06-20 15:08 UTC, codingonHP commented
@joaomoreno Any feedbacks?

2020-07-29 13:55 UTC, codingonHP commented
@joaomoreno Hey, it's been a while since I raised this PR. Can you please have a look at it whenever you find any time.

2020-07-30 08:01 UTC, joaomoreno requested changes
You seem to be bundling all staged changes into a single abstraction. Note that a staged file can either be modified, added, deleted, etc.

So you need all combinations: `stagedAddedResourceForeground`, `stagedModifiedResourceForeground`, etc.

2020-07-30 08:01 UTC, joaomoreno commented on extensions/git/src/repository.ts
> +				return 'S';
I don't think this is a good idea, since we've been using `M` for this for a long long time.

2020-07-30 08:01 UTC, joaomoreno commented on extensions/git/package.nls.json
> +	"colors.stagedAdded": "Color for staged resources.",
Not exactly right. Staged resources can be added, modified, deleted...

2020-11-06 14:57 UTC, joaomoreno commented
Issue is now fixed: https://github.com/microsoft/vscode/issues/99129

Sorry about that and thanks for the PR!

2020-11-06 14:57 UTC, closed without merging