handle errors in backup tracker while writing backup
microsoft/vscode pull request #106763
Opened 2020-09-15 13:16 UTC by sandy081

This PR fixes #106388

2020-09-15 14:13 UTC, bpasero requested changes

2020-09-15 14:13 UTC, bpasero commented on src/vs/workbench/contrib/backup/common/backupTracker.ts
> +				} catch (error) { /* Ignore */ }
At least we should log the error, no?

2020-09-16 08:44 UTC, sandy081 commented on src/vs/workbench/contrib/backup/common/backupTracker.ts
> +				} catch (error) { /* Ignore */ }
👍 Logged

2020-09-16 09:06 UTC, bpasero approved these changes
LGTM

2020-09-17 14:57 UTC, merged