Initial sketches for copy/paste action provider API
microsoft/vscode pull request #107283
Opened 2020-09-23 07:56 UTC by mjbvz

Initial sketches for copy/paste action provider 

For #30066

2022-05-10 23:05 UTC, mjbvz commented on extensions/markdown-language-features/src/extension.ts
> +	let copyCount = 0;
For testing purposes and should not be merged

2022-05-17 15:28 UTC, mjbvz commented on src/vscode-dts/vscode.proposed.documentPaste.d.ts
> +		prepareDocumentPaste?(document: TextDocument, selection: Selection, dataTransfer: DataTransfer, token: CancellationToken): void | Thenable<void>;
Selection -> Range

2022-05-17 15:32 UTC, mjbvz commented on src/vscode-dts/vscode.proposed.documentPaste.d.ts
> +		export function registerDocumentPasteEditProvider(selector: DocumentSelector, provider: DocumentPasteEditProvider): Disposable;
TODO: add display name to show in UI?

2022-05-24 00:00 UTC, mjbvz reviewed
Notes from discussions: 

- Right now we always apply the first edit from a paste provider. In the future we may instead want to show UI on paste that lets users select  which edit to use


- Instead of returning a `WorkspaceEdit` directly, we may want to return a new type such as `PasteAction` that has a `WorkspaceEdit`. This would let extensions provide names if we show the action in the UI, and also potentially let us split the paste into two phases: provide and resolve

- The current implementation does not apply data transfer contributed by extensions to the global clipboard

     This means that you cannot copy and paste data that comes from a provider in VS Code into out into another application. This is likely something we can fix, but means we would need permissions to access the clipboard api

2022-05-24 07:54 UTC, jrieken requested changes
Looking good, but API proposals need to be enforced 👮🏼‍♂️

2022-05-24 07:54 UTC, jrieken commented on src/vs/editor/browser/widget/codeEditorWidget.ts
> +		this._register(_languageFeaturesService.documentPasteEditProvider.onDidChange(update));
Is this needed? I see no paste-related context key that's being updated?

2022-05-24 07:54 UTC, jrieken commented on src/vs/workbench/api/common/extHost.api.impl.ts
> +				return extHostLanguageFeatures.registerDocumentPasteEditProvider(extension, checkSelector(selector), provider);
proposal must be enforced

2022-05-24 07:54 UTC, jrieken commented on src/vs/workbench/api/common/extHost.api.impl.ts
> +				return extHostLanguageFeatures.registerDocumentPasteEditProvider(extension, checkSelector(selector), provider);
and then added to markdown's `package.json`

2022-05-24 07:54 UTC, jrieken commented on src/vs/editor/contrib/copyPaste/browser/copyPasteController.ts
> +				const edit = await provider.provideDocumentPasteEdits(model, selection, dataTransfer, CancellationToken.None);
fyi - there is `EditorStateCancellationTokenSource` which helps you check the document version and automatically cancel requests

2022-05-25 10:27 UTC, jrieken approved these changes

2022-05-25 10:27 UTC, merged