support to delete remote tag from command palette.
microsoft/vscode pull request #107476
Opened 2020-09-25 19:27 UTC by Shubhamurkade

This PR fixes #104845

Added support to delete remote tag using the following git command - 'git push --delete <remote_name> <tag_name>'.

The 'deleteRemoteTag' function in 'repository.ts' is the function which has all the logic. The following actions happen when the user selects 'Delete: Remote Tag' from command palette:

1. The user is prompted to choose a tag from the repository.
2. The user is prompted to choose a remote from the repository.
3. After that the above-mentioned git command is executed to delete the tag from the remote specified.

2020-11-10 10:46 UTC, joaomoreno requested changes

2020-11-10 10:46 UTC, joaomoreno commented on extensions/git/src/commands.ts
> +			window.showErrorMessage(localize('no remotes added', "Your repository has no remotes."));
We should do this validation before asking for user input.

2020-11-10 10:46 UTC, joaomoreno commented on extensions/git/src/commands.ts
> +			window.showWarningMessage(localize('no remotes', "This repository has no remotes."));
This should be an error message, not warning. Also, the validation should happen before asking for user input.

2020-11-10 10:46 UTC, joaomoreno commented on extensions/git/src/commands.ts
> +		const picksRemote = remotes.filter(r => r.fetchUrl !== undefined).map(r => ({ label: r.name, description: r.fetchUrl! }));
Why `fetchUrl`? Wouldn't `pushUrl` be a better indicator?

2020-12-10 18:49 UTC, kadirselcuk approved these changes

2023-01-02 16:58 UTC, lszomoru commented
Thank you very much for your contribution. It looks like this pull request has been abandoned as the requested changes were never implemented. There is also a new pull request that adds the same functionality - https://github.com/microsoft/vscode/pull/134327. Closing this pull request.

2023-01-02 16:58 UTC, closed without merging