Fix spelling in papercuts.github-issues
microsoft/vscode pull request #115452
Opened 2021-01-30 06:14 UTC by jogo-

Read [Spell check errors](https://github.com/microsoft/vscode/wiki/How-to-Contribute#spell-check-errors), but still not sure if these ones are actually in source code

2021-02-01 11:22 UTC, jrieken requested changes
Thanks for far

2021-02-01 11:22 UTC, jrieken commented on .vscode/notebooks/papercuts.github-issues
> +    "value": "## Papercuts\n\nThis notebook serves as an ongoing collection of papercut issues that we encounter while dogfooding. With that in mind only promote issues that really turn you off, e.g.
"want to" not "wan to"

2021-02-02 05:30 UTC, jogo- commented on .vscode/notebooks/papercuts.github-issues
> +    "value": "## Papercuts\n\nThis notebook serves as an ongoing collection of papercut issues that we encounter while dogfooding. With that in mind only promote issues that really turn you off, e.g.
Correct! Typo fixed.

2021-02-02 08:58 UTC, jrieken approved these changes

2021-02-02 08:59 UTC, merged