tabs
microsoft/vscode pull request #120591
Opened 2021-04-05 21:44 UTC by meganrogge

2021-04-05 23:14 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/media/terminal.css
> +	width: 20%;
When the split view works we'll want to remove these explicit widths

2021-04-05 23:14 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/media/terminal.css
> +	float: left;
`display: flex` is way better than using float for layouts

2021-04-05 23:14 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/tabsView.ts
> +		this._terminalService.terminalTabs.forEach(t => t.layout(width - 100, height));
The `TerminalTabsWidget` and terminal tabs container would be `SplitPane` children of the `SplitView`, like how a `TerminalTab`'s `SplitPaneContainer` has a child `SplitPane` for every instance in the tab.

2021-04-07 18:38 UTC, Tyriar requested changes

2021-04-07 18:38 UTC, Tyriar commented on .vscode/settings.json
> -	"testing.autoRun.mode": "onlyPreviouslyRun",
Accidentally committed?

2021-04-07 18:38 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/tabsView.ts
> +	private _splitView!: SplitView;
Should we move the split view creation into the ctor to avoid the `!`?

2021-04-07 18:38 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/tabsView.ts
> +	private _splitView!: SplitView;
readonly?

2021-04-07 18:38 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/tabsView.ts
> +	private _terminalContainer: HTMLElement;
readonly?

2021-04-07 18:38 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/tabsView.ts
> +		if (this._splitView) {
We can avoid this I think as it's only created once?

2021-04-07 19:01 UTC, Tyriar requested changes
Reviewing on my phone so I couldn't look into some things myself 🙂

2021-04-07 19:01 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts
> +			'description': localize('sideBarLocation', "Controls the location of the terminal tabs, either left or right of the terminal container.")
Id needs renaming

2021-04-07 19:46 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts
> +		this._tabsWidget = this._instantiationService.createInstance(TerminalTabsWidget, this._terminalTabTree);
no, we want to always create it. and set it's visibilty I think

2021-04-07 22:21 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/common/terminal.ts
> +	tabsLocation: 'left' | 'right';
yes

2021-04-07 22:36 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/browser/terminalTabsWidget.ts
> +		return 24;
https://github.com/microsoft/vscode/blob/10d92e5efaf67a39660260f4fa5e44b3f847c597/src/vs/workbench/contrib/preferences/browser/tocTree.ts#L145-L145

2021-04-08 12:33 UTC, Tyriar approved these changes

2021-04-08 12:44 UTC, Tyriar commented
Exception on right click:

<img width="635" alt="Screen Shot 2021-04-08 at 5 44 32 AM" src="https://user-images.githubusercontent.com/2193314/114028594-80fdd080-982d-11eb-9a7a-4dff25ae3778.png">

2021-04-08 12:48 UTC, merged