Take changelog from remote if provided
microsoft/vscode pull request #12455
Opened 2016-09-22 14:41 UTC by XVincentX

The following PR should be the missing part to make #11940

2016-09-22 14:42 UTC, msftclas commented
Hi __@XVincentX__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-09-22 15:14 UTC, XVincentX commented
@joaomoreno Last part is here!

2016-09-22 15:31 UTC, joaomoreno commented on src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts
> +		return this.gallery && this.gallery.assets.changelog;
This was the wrong place. You should do it in the `hasChangelog` and `getChangelog`. While you're at it, just delete the `readmeUrl` and `changelogUrl`; the former was an old implementation which I forgot to delete.

2016-09-22 15:32 UTC, joaomoreno commented on src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts
> +		return this.gallery && this.gallery.assets.changelog;
Actually no...

Make those two getters `private` and use them in the `getReadme` and `getChangelog` methods to get a hold of the URL.

2016-09-22 15:33 UTC, joaomoreno requested changes
Awesome dude, almost there!

2016-09-22 16:07 UTC, XVincentX commented
Addressed in 154a45c @joaomoreno

2016-09-27 09:46 UTC, XVincentX commented
@joaomoreno I think I made a mistake here while rebasing my fork. 
Is it still possible to make this happen within September release?

2016-09-27 09:50 UTC, msftclas commented
Hi __@XVincentX__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-09-27 09:51 UTC, XVincentX commented
Ok I managed to reopen it.

2016-09-27 16:27 UTC, msftclas commented
Hi __@XVincentX__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-09-27 16:27 UTC, joaomoreno approved these changes

2016-09-27 17:01 UTC, merged

2016-09-27 17:01 UTC, joaomoreno commented
Thanks @XVincentX, great work!!

2016-09-27 18:48 UTC, XVincentX commented
I can't wait to see it live!