Fix terminal icon hover.
microsoft/vscode pull request #125895
Opened 2021-06-10 03:36 UTC by timfenney

This PR fixes #122427.

This change allows the Terminal status icons to show a label when hovered.
For example, in a Terminal you may execute:
```$ while true ; do sleep 5 ; tput bel ; done```
In the VS Code Settings, ensure that the Terminal Bell is enabled, and it's duration is set to a long enough time to show the hover on mouse over, such as 5000 ms.
Finally, when the Bell appears, mouse over it to show the popup.

2021-06-11 14:45 UTC, Tyriar requested changes
We definitely want to avoid the 2 tooltips showing at once

2021-06-11 16:08 UTC, timfenney commented
> We definitely want to avoid the 2 tooltips showing at once

Which, "sleep" & ":bell: Bell" ?
This is the text that is provided from the html element, what should it say instead?

2021-06-11 17:54 UTC, Tyriar commented
See how there is the darker tooltip behind the lighter one here:

![image](https://user-images.githubusercontent.com/2193314/121729445-5802f180-caa3-11eb-93a4-085de9046d22.png)

2021-06-12 14:08 UTC, timfenney commented
> See how there is the darker tooltip behind the lighter one here:
> 
> ![image](https://user-images.githubusercontent.com/2193314/121729445-5802f180-caa3-11eb-93a4-085de9046d22.png)

This is interesting. The underlying "darker tooltip" is because the mouse pointer is momentarily hovering over the list row for the terminal. The changes on this branch are not causing it; I can reproduce it on `main`. I think it is caused by the visual instability seen when the 🔔 appears.

It might be a bigger conversation to figure out how to improve the visual stability; i.e. the layout shift of the 📖 and 🗑️ left and right.

What do you think @Tyriar ?

2021-07-06 21:15 UTC, Tyriar commented
Sorry about the delay, I'm pretty sure this branch is causing the problem since you're targeting a different element? I might be wrong but you should resync with `main` since it definitely doesn't happen on the latest.

2021-09-05 18:11 UTC, timfenney commented
@Tyriar sorry I have not had time to look at this; also I'm getting pinged on new related suggestions, is the design of this feature finalized?

2021-10-12 12:38 UTC, jrieken commented
Sorry this become obsolete as we pushed for a slightly different fix.

2021-10-12 12:38 UTC, closed without merging