Fix #1939 - Show tag name instead of commit in GitStatusbar
microsoft/vscode pull request #12584
Opened 2016-09-25 20:15 UTC by Krzysztof-Cieslak

If there exist tag with same `ps1` as checkout commit show tag name, otherwise use `ps1` as before

CC @joaomoreno, issue #1939

2016-09-25 20:15 UTC, msftclas commented
Hi __@Krzysztof-Cieslak__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-10-14 13:24 UTC, joaomoreno requested changes
This functionality should be done in `model.getPS1()`, not outside of it.

2016-10-14 13:24 UTC, joaomoreno commented on src/vs/workbench/parts/git/browser/gitWidgets.ts
> +		const tags = model.getRefs().filter(iref => iref.commit.substr(0,8) === ps1);
You should use `model.getHEAD().commit` to compare with `iref.commit`.

2016-10-14 13:24 UTC, joaomoreno commented on src/vs/workbench/parts/git/browser/gitWidgets.ts
> +		const name = tags.length > 0 ? tags[0].name : model.getPS1();
This breaks the `+*!` symbols in front of branches, since whenever a branch is checked out, `model.getPS1` is never called.

2016-10-20 10:02 UTC, Krzysztof-Cieslak commented
@joaomoreno: Fixed.

2016-10-20 21:49 UTC, Krzysztof-Cieslak commented
@joaomoreno: Any idea about CI errors? Error messages are really ... unhelpful. And it builds fine on My Machine™️

2016-10-21 07:03 UTC, msftclas commented
Hi __@Krzysztof-Cieslak__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-10-21 09:42 UTC, merged

2016-10-21 09:43 UTC, joaomoreno commented
Thanks!