Add option: include command in screencast overlay
microsoft/vscode pull request #126742
Opened 2021-06-19 16:28 UTC by PEZ

This PR fixes  #126713

When setting up the keyboard keys overlay for shortcuts in Screencast mode, it is now 

1. Prepended with a `Command category: Command title`.
2. Displaying the full shortcut chord.

NB: `keybindingService.lookupKeybinding(commandId)` is used to display the full shortcut chord. This method/function has a bug making it sometimes pick up the wrong keybinding, if different keybindings are configured for the shortcut for different operating systems. I think it might be the same root cause as for #126306. Do you want me to try fix that bug in this PR? I want to. 😄 

The bug gets extra important to fix by the fact that I am planning to add information to the key casting about differences in operating systems. So for instance if the shortcut for Calva's command to move *Sexp Forward* is `alt+right` on Mac, but `ctrl+right` on Linux and Windows, I'd like to display something like:

![image](https://user-images.githubusercontent.com/30010/122648771-e8d46f80-d12a-11eb-963d-f4dee3cb4c95.png)

2021-06-19 21:47 UTC, PEZ commented
It seems very involved to figure out the keybinding for a given command on other platforms than the current. The keybindingRegistry doesn't keep the info around. I edited the PR description to not include that part of the functionality.

2021-06-21 08:24 UTC, joaomoreno commented
@PEZ There seem to be extra commits on this PR that you did not authored. Can you clean the branch?

2021-06-21 10:34 UTC, PEZ commented
Hmm, yeah, I rebased with main, interpreting some PR instruction that way... I now force pushed a reset from before the rebase. Is that what you need, @joaomoreno ?

2021-06-25 10:04 UTC, PEZ commented
@alexdima , in this PR I am currently sending along the context service to `lookUpKeybindings()`. With https://github.com/microsoft/vscode/commit/87d09c2e939aac5d8ae6c938b2bd4e750431a214 that isn't strictly necessary anymore. You think I should call it w/o passing on context?

Also, the context doesn't even help. With or  without passing it, `contextMatchesRules()` fails. I also tested with your commit applied. Same. Any idea why the context would be different in the screencast situation than when summoning the command palette?

2021-06-27 14:33 UTC, PEZ commented
Here's an example screencast using this feature:

https://www.youtube.com/watch?v=U-cys75qaCw

2021-07-05 12:33 UTC, alexdima commented
> You think I should call it w/o passing on context?

:+1: to call without a context (it looks like you're passing in the global context anyways, so the behavior should be the same with or without passing it in).

2021-07-16 11:17 UTC, joaomoreno commented
A few problems:

- Most commands don't show any label. Try copy text or comment line. Only the keybinding appears.
- The setting should probably be an enum instead of two settings, something like: `screencastMode.keyboardShortcutsPrefix: 'none' | 'command' | 'commandAndGroup'`
- The default should not change: it should be off/`'none'` by default

2021-07-16 11:17 UTC, joaomoreno requested changes
A few problems:

- Most commands don't show any label. Try copy text or comment line. Only the keybinding appears.
- The setting should probably be an enum instead of two settings, something like: `screencastMode.keyboardShortcutsPrefix: 'none' | 'command' | 'commandAndGroup'`
- The default should not change: it should be off/`'none'` by default

2021-07-16 14:05 UTC, PEZ commented
@joaomoreno , thanks! I've fixed the settings.

I think I need some guidance for the issue with that many commands do not show a label.  I'm currently using the `MenuRegistry` for this and as far as I have tracked things this registry is populated with `addCommand()` at line 232 of `src/vs/platform/actions/common/actions.ts`. The `workbench.action.files.save ` command is never registered here. Should I be looking somewhere else?

2021-07-19 13:30 UTC, joaomoreno commented
You should use the [command registry](https://github.com/microsoft/vscode/blob/132e3783d0ad7c3e89935e67857828f5982d6bdb/src/vs/platform/commands/common/commands.ts/#L123) instead.

2021-07-22 19:32 UTC, PEZ commented
@joaomoreno , that's  one of the things I've considered, but it doesn't seem to have what we need to populate the overlay:

```typescript
export interface ICommand {
	id: string;
	handler: ICommandHandler;
	description?: ICommandHandlerDescription | null;
}
```

2021-08-31 06:04 UTC, PEZ commented
I'm stuck on the issue with many built in commands not showing a label.

I can say this though, that for extension contributed commands it works, and that when I create screencasts I much rather use the PR build than the regular build. Meaning to say, we're adding value as it stands. 😄

2021-09-10 12:18 UTC, joaomoreno commented
> @joaomoreno , that's one of the things I've considered, but it doesn't seem to have what we need to populate the overlay:

Isn't `description` set for most commands/

2021-10-09 13:24 UTC, PEZ commented
@joaomoreno:

> Isn't description set for most commands?

The problem I am hitting is not a lack of description. Yet. The CommanRegisitry has `ICommand`s, where I think I need `ICommandAction`s. That said, I don't see much in the way of `description` either.

If I pick out one command from each registry like so:

```typescript
const command = shortcut?.commandId ? MenuRegistry.getCommand(shortcut.commandId) : null;
const command2 = shortcut?.commandId ? CommandsRegistry.getCommand(shortcut.commandId) : null;
```

Logging them out shows this for some different commands:

```
MenuRegistry-command: undefined
CommandRegistry-command: {"id":"editor.action.smartSelect.expand"}

MenuRegistry-command: undefined
CommandRegistry-command: {"id":"editor.action.addSelectionToNextFindMatch"}

MenuRegistry-command: {"id":"paredit.forwardUpSexp","title":"Forward Up Sexp","category":"Calva Paredit","precondition":{"key":"editorLangId","value":"clojure","type":4}}
CommandRegistry-command: {"id":"paredit.forwardUpSexp"}

MenuRegistry-command: {"id":"calva.evaluateCurrentTopLevelForm","title":"Evaluate Top Level Form (defun)","category":"Calva","precondition":{"key":"calva:connected","type":2}}
CommandRegistry-command: {"id":"calva.evaluateCurrentTopLevelForm"}

MenuRegistry-command: {"id":"workbench.action.showCommands","title":{"value":"Show All Commands","original":"Show All Commands"}}
CommandRegistry-command: {"id":"workbench.action.showCommands"}

MenuRegistry-command: undefined
CommandRegistry-command: {"id":"workbench.action.closeQuickOpen","weight":200,"when":{"key":"inQuickOpen","type":2},"primary":9,"secondary":[1033]}
```

Maybe the real fix is to have more commands registered in the MenuRegistry? But seems a bit out of scope for this PR, WDYT?

2021-10-11 07:00 UTC, alexdima commented
@joaomoreno See my answer to the question above ⬆️  https://github.com/microsoft/vscode/pull/126742#issuecomment-869173459

Is there any other question that I missed?

2021-10-11 08:52 UTC, PEZ commented
@alexdima @joaomoreno , if I may try to summarize what I think are the considerations:

I've addressed all but one change request, which is: With the current state of the PR only commands registered in the MenuRegistry will get a command title in the screencast overlay. It seems all extension contributed commands are there, but amongst the built-in commands most are not registrered there. This raises two questions:

1. Is that good enough for merging?
2. Is there some way in reach where we can display titles for the commands not in the MenuRegistry?

As to the second question, I can't see there is. If there is, I need guidance to find it.

As to the first question, in my opinion the current PR brings a lot of the feature's value already, I use it often for my screencasts/demo sessions. To me it would make sense to ship this as the first take and then make separate issues for:

1. Getting more built-in commands registered in the MenuRegistry (or device another way for providing what is needed by the screencast overlay)
2. Add an option for displaying the default keyboard shortcuts (currently the PR displays the active bindings)
3. Add an option for displaying the keyboard shortcuts for all platforms, when they differ

2021-10-30 16:12 UTC, PEZ commented
@joaomoreno I have been running with the generalized settings a while now and I think they work great.

I choose to default to `commandAndKeys` and might be a bit blind/biased about it, but during my testing it has felt totally natural as a default.  😄 

As a `v1` I think this is fine now. I want to keep iterating on it, something in this order:

1. Display command titles for more commands. We now know how find more commands, but it doesn't feel right to loop through all EditorActions at every keypress, so I will need to figure out how to only do that if the source has changed.
2. Make it possible to choose between showing default shortcut bindings and the ones configured.
3. Add option to display shortcut bindings for different OS platforms when they differ.

2021-11-01 09:02 UTC, merged

2021-11-01 09:02 UTC, joaomoreno commented
Thanks! 🍻

2021-11-03 10:51 UTC, ArturoDent commented
Is this in the Insiders Build yet?  I can't find the setting to test it.

Version: 1.62.0-insider (user setup)
Commit: 4bbec283c36a51cf80f9b77c7a81c140a76a363b
Date: 2021-11-02T08:19:40.220Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

2021-11-03 13:46 UTC, joaomoreno commented
@ArturoDent, not yet. We're currently stabilizing so we can release stable. It will be in Insiders closer to the end of this week.