[typescript-language-features] Add suggest.allowIncompleteCompletions and pass trigger kind to TS Server
microsoft/vscode pull request #127673
Opened 2021-06-30 16:16 UTC by andrewbranch

Counterpart to https://github.com/microsoft/TypeScript/pull/44713

2021-06-30 16:17 UTC, andrewbranch commented
To discuss: how/whether to present `suggest.allowIncompleteCompletions` in settings UI

2021-06-30 21:58 UTC, mjbvz requested changes

2021-06-30 21:58 UTC, mjbvz commented on extensions/typescript-language-features/src/utils/typeConverters.ts
> +		return kind + 1;
Can we use a more explicit mapping here, such as a switch statement or map?

2021-06-30 21:58 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts
> +			allowIncompleteCompletions: config.get<boolean>('suggest.allowIncompleteCompletions', true),
Following up on our discussion earlier today:  we agreed that this should not be user configurable

2021-07-06 23:10 UTC, merged

2021-07-06 23:10 UTC, mjbvz commented
Thanks!