move run above and below
microsoft/vscode pull request #130009
Opened 2021-08-03 00:29 UTC by DavidKutu

to position 1 instead of 0, this allows run by line to be the first menu item

This PR fixes #

2021-08-03 01:43 UTC, roblourens requested changes
Use the `CellToolbarOrder` enum for this. I guess I didn't adopt it for the run above/below commands, you could do that too if you want

2021-08-03 16:07 UTC, roblourens commented on src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts
> +					order: CellToolbarOrder.SplitCell,
I mean, add new entries that represent this command :)

2021-08-03 16:54 UTC, roblourens approved these changes

2021-08-03 16:54 UTC, merged

2021-08-07 20:18 UTC, scybert commented
Hi @roblourens . Is merging of failed PR's expected in VScode? I'm totally new!

2021-08-09 19:02 UTC, roblourens commented
I checked that the errors were not related to these changes