Added close field in vscode.d.ts interface TaskPresntationOptions
microsoft/vscode pull request #131127
Opened 2021-08-18 20:37 UTC by jackos

Although there is an option to close terminal after task completes running in tasks.json, the option didn't exist in vscode.d.ts interface TaskPresntationOptions

Confirmed that this works as expected in a custom extension.

Please see more details in [Issue #131125](https://github.com/microsoft/vscode/issues/131125)

To test this works, create a task in a VS Code extension with vscode.Task, add the presentation option close: true, and execute the task with vscode.tasks.execute task e.g:

![image](https://user-images.githubusercontent.com/77730378/129968561-f7e59cf8-61d5-47d7-883c-0561d417159c.png)

Here is an example of it working: 

![working](https://user-images.githubusercontent.com/77730378/129968760-33f1acd0-35e7-4550-90bc-f53e4e13a0a5.gif)

This PR fixes #131125

2021-08-19 09:16 UTC, alexr00 requested changes
Thanks for the PR! New API must be added to `vscode.proposed.d.ts` before it can move into `vscode.d.ts`. Additionally, I would like to understand how you want to use the new `close` API before we add it.

2021-08-20 00:08 UTC, jackos commented
Thanks for looking at it! I moved it into `vscode.proposed.d.ts`.

The tasks API is fantastic and allows you to do async tasks more cleanly than using node's child_process and an output, plus I found major performance improvements, it also gives the user more control as they can see clearly in a terminal what code your extension is running and close it if they wish. 

Not having control to close a task programmatically after completion causes issues, the main one I came across is that I want to do a check on user input to see if a task is running, which can branch to different logic. Another example is I run a few tasks asynchronously, I want the user to be aware of what's going on especially if a task is blocking, but then they're left with a lot of clutter and have to close them manually making a poor ux. 

I would actually prefer the default to be close after run, but others would prefer it to work how it does now, making this a perfect candidate for an optional field! Additionally I would say if this makes sense as an option when a user is creating their own task in `tasks.json`, it also makes sense here. Also for developer experience, if we're building extensions it's because we love VS Code and we're familiar with using a `tasks.json` file, so matching up the programmtic interface makes sense.

2021-08-20 08:20 UTC, alexr00 approved these changes
Looks good. I will merge it in September.

2021-08-27 23:42 UTC, jackos commented
@alexr00 Thanks so much, it's a real honor to have a PR accepted for VS Code (no matter how small!) which is my favorite IDE by a long way.

2021-08-28 15:30 UTC, andrewchoi5 approved these changes

2021-09-01 13:59 UTC, merged