Added 'zsh' to ignoreProcessNames[] in childProcessMonitor.ts and created the new setting in terminalConfiguration.ts , contributing to issue #131386
microsoft/vscode pull request #131486
Opened 2021-08-24 09:27 UTC by san-coding

This PR fixes #131386 

Added 'zsh' to ignoreProcessNames[] in childProcessMonitor.ts and created the new setting in terminalConfiguration.ts , contributing to issue #131386

2021-08-24 09:30 UTC, san-coding commented
@Tyriar please review the pull request

2021-08-24 11:09 UTC, Tyriar commented
@san-coding thanks for the change, we've just started testing v1.60 so we'll probably review this for v1.61 next week

2021-08-24 14:15 UTC, san-coding commented
Thanks , will this be reviewed by the end of this month ?

2021-08-25 02:13 UTC, san-coding commented
@Tyriar is there a need to add a dropdown (enum) for the newly created configurable/setting ?

2021-08-27 13:31 UTC, Tyriar requested changes
> is there a need to add a dropdown (enum) for the newly created configurable/setting ?

@san-coding since we don't know what the values could be (literally anything), we wouldn't be able to list them all out in an enum. Right now it's an array but I think you can tighten it to be a string array to make sure booleans, numbers, etc. don't get added.

2021-08-29 11:14 UTC, san-coding commented on src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts
> +		[TerminalSettingId.ignoreProcessNames]: {
Ok thanks, I will make those changes, but do I have the roll back my existing commits ?

2021-08-29 12:34 UTC, san-coding commented
@Tyriar I have changed `ignoreProcessNames` to `IgnoreProcessNames` in  `terminalConfiguration.ts`
 (Type rectified from last commit) and added `IgnoreProcessNames` definition to  `terminalPlatformConfiguration.ts`

2021-08-30 13:18 UTC, Tyriar requested changes
This won't compile as `ignoreProcessNames` was removed but wasn't replaced with using the setting yet.

2021-08-30 15:13 UTC, san-coding commented
> This won't compile as `ignoreProcessNames` was removed but wasn't replaced with using the setting yet. Please make sure you test the change and that it fixed the issue.

Sorry I don't understand what you meant by _`ignoreProcessNames` was removed but wasn't replaced with using the setting yet_ , we are using `IConfigurationService` in place of it right ?

2021-08-30 17:10 UTC, Tyriar commented
> but I don't understand what you meant by ignoreProcessNames was removed but wasn't replaced with using the setting yet

You commented out the variable `ignoreProcessNames` but it's still being used and you didn't update the usage.

> we are using IConfigurationService in place of it right

You've injected the service but are not using it yet.

> could you please elaborate on why it won't compile

Please make sure the codebase compiles locally before sending PRs.

2021-08-30 19:48 UTC, san-coding commented
> > but I don't understand what you meant by ignoreProcessNames was removed but wasn't replaced with using the setting yet
> 
> You commented out the variable `ignoreProcessNames` but it's still being used and you didn't update the usage.
> 
> > we are using IConfigurationService in place of it right
> 
> You've injected the service but are not using it yet.
> 
> > could you please elaborate on why it won't compile
> 
> Please make sure the codebase compiles locally before sending PRs.

Yes I feel the below code will cause an error, how can I fix this 
https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/childProcessMonitor.ts#L123

2021-08-30 19:49 UTC, san-coding commented
> > > but I don't understand what you meant by ignoreProcessNames was removed but wasn't replaced with using the setting yet
> > 
> > 
> > You commented out the variable `ignoreProcessNames` but it's still being used and you didn't update the usage.
> > > we are using IConfigurationService in place of it right
> > 
> > 
> > You've injected the service but are not using it yet.
> > > could you please elaborate on why it won't compile
> > 
> > 
> > Please make sure the codebase compiles locally before sending PRs.
> 
> Yes I feel the below code will cause an error, how can I fix this , I don't see this being used anywhere else
> 
> https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/childProcessMonitor.ts#L123

2021-08-31 11:04 UTC, san-coding commented
## I have un-commented `ignoreProcessNames`, will the issue be resolved now ?

2021-08-31 12:49 UTC, Tyriar commented
> I have un-commented ignoreProcessNames, will the issue be resolved now ?

That will just do what it was doing before, you need to pull the setting in using the configuration service like this:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/terminalProfiles.ts#L42-L42

2021-08-31 14:37 UTC, san-coding commented
> > I have un-commented ignoreProcessNames, will the issue be resolved now ?
> 
> That will just do what it was doing before, you need to pull the setting in using the configuration service like this:
> 
> https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/terminalProfiles.ts#L42-L42

Ok I will try to fix the issue, should I pull setting in `childProcessMonitor.ts` ?

2021-08-31 14:54 UTC, Tyriar commented
Yep, in place of where ignoreProcessNames was being used

2021-09-03 05:11 UTC, san-coding commented
> Yep, in place of where ignoreProcessNames was being used

Hey @Tyriar , I made the changes, but I feel that  they are incorrect and syntax is wrong , could you please verify and tell me what to do, thanks

2021-09-06 05:31 UTC, san-coding commented
@Tyriar ??

2021-09-09 10:16 UTC, Tyriar commented
This is still not really that close. It's imperative that you actually test the change when you contribute to OSS before you submit the pull request so as to not waste the time of the maintainers. Also it's bad etiquette to ping people on twitter and email, github is the place for that. Closing this to prevent more time from being wasted on both our parts.

2021-09-09 10:16 UTC, closed without merging

2021-09-09 10:28 UTC, san-coding commented
@Tyriar, I was just excited about my first pull request, wasn't receiving any response from your side, so I decided to ping you on Twitter and email you for help, I understand the inconvenience it might have caused, thank you for your assistance so far, I did learn a lot about VSCode codebase through this PR  and have learnt the lessons, won't repeat the same mistake, learning and contributing will continue 👍🏻

2021-09-09 10:54 UTC, Tyriar commented
@san-coding glad you learned something and I don't intend to me mean, but it's taking too much time for me to guide you through this. I also just saw you pinged me on unrelated PRs, this is really quite annoying. Here's a screenshot of my inbox to give you an idea of what I'm working with:

![image](https://user-images.githubusercontent.com/2193314/132673338-dcd1ed4f-e2ce-4219-80be-8573bdebeae0.png)

PRs are always welcome but they must work, this either did compile or didn't fix the problem it claimed to (using the setting).

2021-09-09 10:57 UTC, san-coding commented
> @san-coding glad you learned something and I don't intend to me mean, but it's taking too much time for me to guide you through this. I also just saw you pinged me on unrelated PRs, this is really quite annoying. Here's a screenshot of my inbox to give you an idea of what I'm working with:
> 
> ![image](https://user-images.githubusercontent.com/2193314/132673338-dcd1ed4f-e2ce-4219-80be-8573bdebeae0.png)
> 
> PRs are always welcome but they must work, this either didn't compile or didn't fix the problem it claimed to (using the setting).

Oh I understand .. will do better next time