Headings outline for markdown
microsoft/vscode pull request #13238
Opened 2016-10-05 09:05 UTC by jrieken

Adds a DocumentSymbolProvider for markdown that lists headings. Should make navigation is large document easier. 

![screen shot 2016-10-05 at 11 04 07](https://cloud.githubusercontent.com/assets/1794099/19107248/a37a4f48-8aeb-11e6-8dc4-ab2fda977c7f.png)

2016-10-05 18:15 UTC, mjbvz requested changes

2016-10-05 18:15 UTC, mjbvz commented on extensions/markdown/src/extension.ts
> +	private static _atxPattern = /^(#){1,6}\s+.+(\s+\1)?/;
On the regex:
* Strip out any number of trailing `#`s at the end of the line. This does not have to match the number at the start: http://spec.commonmark.org/0.26/#example-42
* Match end of line too, to handle weird cases like `# a # a #`
* Strip out whitespace around the header text itself for the displayed symbol.

Something like: `^(#{1,6})\s+(.+?)\s*#*\s*$` and use these two captures to build up the symbol

2016-10-05 18:15 UTC, mjbvz commented on extensions/markdown/src/extension.ts
> +	private static _settext = /^\s*[-=]+\s*$/;
Make sure to also test that this does not pick up separators

2016-10-05 18:15 UTC, mjbvz commented on extensions/markdown/src/extension.ts
> +	private static _atxPattern = /^(#){1,6}\s+.+(\s+\1)?/;
Also, there are a few other cases to consider, such header like text inside of code blocks. These should not be picked up. Probably not essential for a first pass, but worth considering.

2016-10-05 18:15 UTC, mjbvz commented on extensions/markdown/src/extension.ts
> +	private static _atxPattern = /^(#){1,6}\s+.+(\s+\1)?/;
And headers can also indented up to three spaces for each indentation level. I'd make sure to handle the common case, a top level indent of between zero and three spaces (at four it becomes a code block). Handling headers in lists is probably not part of this feature.

2016-10-31 09:22 UTC, jrieken commented
@mjbvz I am aware of how this should work in a perfect world using a syntax tree with all bells and whistles. I have no intentions of implementing that 😄 Closing this PR.

2016-10-31 09:22 UTC, closed without merging

2016-11-01 20:35 UTC, mjbvz commented
@jrieken I'm not opposed to taking this change in with these limitations (although I would like to see the few suggested fixes for the regular expressions). It would be beneficial to include this in the builtin markdown functionality, even if it it's not perfect.