Minimap - highlight all instances of selected word
microsoft/vscode pull request #132584
Opened 2021-09-07 20:49 UTC by utajum

This PR fixes #84151

Adds minimap decoration options that are the same as find decoration ones on double click selection.

To test, simply double click a word after which you will see it selected in the minimap. 

![](https://i.imgur.com/U7RIa0q.png)

2021-09-08 15:38 UTC, alexdima commented on src/vs/editor/contrib/multicursor/multicursor.ts
> +			color: themeColorFromId(minimapFindMatch),
I suggest that we create a new color e.g. `minimalSelectionHighlight` and not reuse `minimapFindMatch`

2021-09-08 15:39 UTC, alexdima requested changes
I find it a bit confusing to reuse the `minimapFindMatch` color for selection highlights. I suggest to define a new color.

2021-09-08 19:19 UTC, utajum commented
`minimap.selectionHighlight` was already taken, so the new color variable is called `minimapSelectionOccurrenceHighlight` with an `id` of `minimap.selectionOccurrenceHighlight`.

The color used is the same as in Atom

2021-09-14 21:40 UTC, alexdima approved these changes

2021-09-14 21:41 UTC, merged