Implements line scopes
microsoft/vscode pull request #133509
Opened 2021-09-21 09:37 UTC by hediet

Works efficiently on checker.ts:

![image](https://user-images.githubusercontent.com/2931520/134147649-98e9e872-98ee-4cea-bca9-c3fe2222df86.png)

Uses indentation of brackets (min of start/end column):

![image](https://user-images.githubusercontent.com/2931520/134147316-fe0b909c-5e13-4e93-aada-acf5992e9c7e.png)

Overrides indent guides if indent guides are enabled:

![image](https://user-images.githubusercontent.com/2931520/134147262-5266cd9a-2f35-402f-805a-f7c8227c7aa5.png)

Active indent guide is only highlighted when there are no bracket guides:

![image](https://user-images.githubusercontent.com/2931520/134147453-e970a6a7-62d9-4524-8368-701af575bf60.png)

Bracket guides can overlap badly formatted text (fixing this is a non-trivial follow up feature and this case should not happen often anyway):

![image](https://user-images.githubusercontent.com/2931520/134147527-ddf2e51a-39b7-4d58-9edc-20822df89f86.png)

2021-09-21 09:39 UTC, hediet commented on src/vs/editor/browser/viewParts/indentGuides/indentGuides.css
> -.monaco-editor .lines-content .cigra {
I don't really know how to measure it, but I really doubt that these abbreviations improve performance/memory consumption much. Every frame maybe renders at most up to 100 of those.

2021-09-21 09:40 UTC, hediet commented on src/vs/editor/common/controller/cursorColumns.ts
> +/*---------------------------------------------------------------------------------------------
I had to move this to a separate file due to cyclic module dependencies.

2021-09-21 09:41 UTC, hediet commented on src/vs/editor/common/model/bracketPairColorizer/bracketPairColorizer.ts
> +		this.bracketsRequested = true;
The tree is build the first time brackets are requested and stays alive until the model is disposed.

2021-09-21 18:16 UTC, alexdima requested changes
Looks good! I would like to see tests, as a lot of the new code is complicated and it is not covered by existing tests. 

I ran into the following case that crashes the editor:

* repeat the line `this is a large file. this is a large file. this is a large file. this is a large file. this is a large file. this is a large file. this is a large file. this is a large file. this is a large file. this is a large file.` 400k times
* enable `"editor.bracketPairGuides.enabled": true,`
* observe NPE that causes the editor to not render completely

![image](https://user-images.githubusercontent.com/5047891/134222661-c7dde796-039d-40a5-a0fe-bd9ce81b3ecb.png)

2021-09-22 13:08 UTC, hediet commented on src/vs/editor/common/controller/cursorCommon.ts
> +export { CursorColumns } from './cursorColumns';
It has 88 references and these changes would dominate the other changes in this PR. I suggest to do the refactoring separately.

2021-09-22 13:10 UTC, hediet commented on src/vs/editor/common/model/textModel.ts
> +		const bracketPairs = this._bracketPairColorizer.getBracketPairsInRange(
Bracket guides & colorization behave the same. For extra large file, no tree is constructed in both cases.

2021-09-22 13:21 UTC, hediet commented on src/vs/editor/common/model/textModel.ts
> +			activeBracketPairRange = tail(bracketsContainingActivePosition)?.range;
But there also cases like this:

```ts
function test() {
	if (true) { | }
}
```

I think highlighting the range from line 1 to 3 (i.e. effectively line 2) in this case could also be confusing.

I'm open to implement your suggestion though.

2021-09-22 13:39 UTC, hediet commented on src/vs/editor/common/viewModel/splitLinesCollection.ts
> +		const minViewColumn = line.getViewLineMaxColumn(
Good catch, this was a copy paste error!

2021-09-23 16:25 UTC, alexdima approved these changes

2021-09-24 08:18 UTC, merged