Categorize kernels in the notebook kernel picker
microsoft/vscode pull request #135502
Opened 2021-10-20 18:37 UTC by DonJayamanne

For https://github.com/microsoft/vscode-jupyter/issues/7373#issuecomment-942697333

* Display currently selected & preferred items on top under `Suggested`
* Display rest of the kernels grouped by category or extension id (if theres not category)

![image](https://user-images.githubusercontent.com/1948812/138151779-974c4969-df96-48d6-82ef-196c89d0c252.png)

2021-10-20 18:45 UTC, rchiodo approved these changes

2021-10-20 18:48 UTC, IanMatthewHuff approved these changes

2021-10-21 15:49 UTC, jrieken requested changes
Thanks so far - some nit and simplifications. Proposed API enforcement is important and I believe `suggested` vs `suggestions` too

2021-10-25 09:24 UTC, jrieken approved these changes
LGTM. Thanks

2021-10-25 15:23 UTC, merged

2022-03-30 07:29 UTC, jrieken commented
@DonJayamanne @rebornix I believe we should bring this proposal to finalization