sort extensions list by name
microsoft/vscode pull request #13885
Opened 2016-10-17 13:14 UTC by JoolsMcFly

@spywhere 's contribution to #12910 sorts the initial list of extensions by name.

This PR adds an entry to the sort by menu so users can sort by name again in case they have sorted by installs or ratings.

2016-10-17 13:14 UTC, msftclas commented
Hi __@JoolsMcFly__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSBOT;

2016-10-18 12:28 UTC, JoolsMcFly commented
I am a bit stumped as to why travis build fails. When I run VScode from my cloned repo (through `./scripts/code.sh`) I see the new "Sort by: name" menu item and no errors are thrown.

I ran `./scripts/test.sh`and got green.

Any idea?

Thanks!

ps: when I use Debug > Launch VSCode, extensions list remains empty no matter what I search. Is that expected behaviour?

2016-10-18 12:28 UTC, msftclas commented
Hi __@JoolsMcFly__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSBOT;

2016-10-18 14:32 UTC, JoolsMcFly commented
And now both are green. ^^

2016-10-20 14:29 UTC, joaomoreno requested changes

2016-10-20 14:29 UTC, joaomoreno commented on src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts
> +				this.instantiationService.createInstance(ChangeSortAction, 'extensions.sort.name', localize('sort by name', "Sort By: Name"), this.onSearchChange, 'name', undefined),
Are you sure this alone fixes it? Did you give it a try?

2016-10-20 19:56 UTC, JoolsMcFly commented
Hi Joao,

thanks for your answer.
I did give it a try, see attached screenshot. 
![extensions](https://cloud.githubusercontent.com/assets/4972399/19575170/98b57ee2-970d-11e6-8e93-d1a9f0f5de4c.jpg)

New menu item shows up and clicking on it does interact with search box. However, no matter what I search list remains empty.

I decided to try with a fresh cloned repo thinking my changes broek something. So I cloned vscode again, ran `./scripts/npm.sh install` and ran `./scripts/code.sh` to see what UI looked like.
Same thing, no extensions pop up no matter what I search.

So I went for another test. I packaged it all using `gulp vscode-linux-x64` and ran that: same thing, empty list.

If I try with an official build then I do get extensions as I search them.

Any ideas why this is?

Thanks!

2016-10-21 06:56 UTC, joaomoreno commented
Add the following section to the `product.json` top level file:

```
	"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	}
```

This will let you run the extension gallery in development mode.

2016-10-21 10:41 UTC, JoolsMcFly commented
Thanks a lot. I'll be afk for about two weeks and I'll give it a go when I'm back.

2016-10-25 18:18 UTC, JoolsMcFly commented
Thanks a lot. I'll be afk for about two weeks and I'll give it a go when I'm back.






On Fri, Oct 21, 2016 at 8:57 AM +0200, "João Moreno" <notifications@github.com> wrote:





Add the following section to the `product.json` top level file:

```
        "extensionsGallery": {
                "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
                "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
                "itemUrl": "https://marketplace.visualstudio.com/items"
        }
```

This will let you run the extension gallery in development mode.

--
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/Microsoft/vscode/pull/13885#issuecomment-255308374

2017-01-23 14:11 UTC, joaomoreno commented
Closing as it's been a while.

2017-01-23 14:11 UTC, closed without merging