Moves tokenization logic from text model to its own text model part.
microsoft/vscode pull request #146552
Opened 2022-04-01 15:29 UTC by hediet

This reduces the complexity of `TextModel` and groups all tokenization-related functionality.

2022-04-04 19:12 UTC, alexdima requested changes
Very good! However, I find that moving `getWordAtPosition` and `getWordUntilPosition` under `.tokenization` is unfriendly towards users of the `ITextModel`. Could these methods remain on `ITextModel`? Personally, I would not search for such methods under `.tokenization`.

2022-04-05 09:48 UTC, hediet commented on src/vs/monaco.d.ts
> +	export interface ITokenizationTextModelPart {
Yes. I added some doc comment.

2022-04-06 08:11 UTC, alexdima approved these changes

2022-04-06 08:12 UTC, alexdima commented
@hediet I removed for now the new `monaco.d.ts` API because it lacked JSDoc comments. Let's expose that with a subsequent change. I'd like to get this in to avoid conflicts and get more selfhosting confidence on the refactoring.

2022-04-06 08:12 UTC, merged