Add ${rootNameShort} template option to window.title for saved workspaces
microsoft/vscode pull request #146780
Opened 2022-04-04 23:46 UTC by Wolverine1621

This PR fixes #145238

This PR adds a `${rootNameShort}` template option for the `window.title` property for saved workspaces. An optional `short` option is added to the `getWorkspaceName` interface and handled in the `labelService` implementation. Calls to `getWorkspaceName` with the `verbose` option, and `window.title` behavior for other types of workspaces, remain unchanged.

Example:

- Default window title: "wsName (Workspace) [Remote Name]"
- `${rootNameShort}` enabled: "wsName"

2022-04-11 18:31 UTC, Wolverine1621 commented
Hello! I see this has been marked as a draft - are there some things I need to review and change? If you have some time to give me some direction I'll take another look.

2022-04-14 18:58 UTC, Wolverine1621 commented
@bpasero Are there any updates on this PR currently? Thank you!

2022-04-19 09:31 UTC, bpasero requested changes
At a quick glance I find both `verbose: boolean` and `short: boolean` hard to understand. Imho it would be easier if there was a single option `verbosity` as we do have for editor inputs:

https://github.com/microsoft/vscode/blob/0e04328299ad24b0d7ff83bc9c763fa1ac5312bc/src/vs/workbench/common/editor/editorInput.ts#L113

And then:
* `SHORT`: is just the name
* `MEDIUM`: is the default as today
* `LONG`: the same as with `verbose: true`

Besides, `rootName` does not only apply to workspaces, but also when you have a single folder opened, so I would think this needs to apply also when folders are opened. There we do not append the ` (Workspace)` suffix, but we would append the remote name.

2022-04-19 09:31 UTC, bpasero commented on src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
> +			rootNameShort,
A new variable needs to be added to here as well:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/extensions/configuration-editing/src/settingsDocumentHelper.ts#L81

and also here:

https://github.com/microsoft/vscode/blob/1128bdab1bcf92f643afee2af1d6c055c8475081/src/vs/workbench/browser/workbench.contribution.ts#L487

2022-04-19 09:31 UTC, bpasero commented on src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
> +		const rootNameShort = this.labelService.getWorkspaceLabel(workspace, { verbose: false, short: true });
This deserves a test for example in here:

https://github.com/microsoft/vscode/blob/19f6f3103606da3fe5d8be4b722d96fe8e18271a/src/vs/base/test/common/labels.test.ts#L105

2022-09-13 04:26 UTC, hoaprofessional approved these changes
good feature

2022-09-23 07:42 UTC, bpasero commented
Closing as stale.

2022-09-23 07:42 UTC, closed without merging