Make markdown image dimensions configurable using a custom image renderer
microsoft/vscode pull request #14811
Opened 2016-11-01 16:30 UTC by kisstkondoros

In the newly introduced syntax extension the width and height of an image
can be given in the image title using following format:
`![image](someimageurl 'caption|height=200, width=100')`.
Both width and height parameters are optional, if they are not given the
width and height attributes remains unset on the image element

This resolves #14803

2016-11-01 22:36 UTC, mjbvz requested changes
Added a few suggestions. I like the idea, but am not sure about overloading the title to support image size, at least without additional checks to make sure we still correctly support titles that contain `|` characters.

Would using the image source instead work?

``` md
![alt](image.png|width=200,height=300 'title')
```

I'm not sure if marked has already encoded the `|` to  a `%7C` when the render function is called or not.

2016-11-01 22:36 UTC, mjbvz commented on src/vs/base/browser/htmlContentRenderer.ts
> +					const heightFromParams = new RegExp(/height=(\d+)/).exec(parameters);
[nit] Just use regexp literal, not `new RegExp`

2016-11-01 22:36 UTC, mjbvz commented on src/vs/base/browser/htmlContentRenderer.ts
> +				title = splitted[0];
Looks like the actual title is getting lost now. Add it back into the attributes

2016-11-01 22:36 UTC, mjbvz commented on src/vs/base/browser/htmlContentRenderer.ts
> +					if (width) {
Change this check to `isFinite` to correctly handle zero width/heights

2016-11-03 07:13 UTC, kisstkondoros commented
@mjbvz I've changed the implementation according to your suggestions

2016-11-04 19:24 UTC, merged

2018-06-22 06:30 UTC, neilsustc commented
@kisstkondoros Thanks a lot!