Need at least one '/' after ':' for md auto links
microsoft/vscode pull request #149585
Opened 2022-05-15 19:53 UTC by MachineMitch21

This PR fixes #149475

2022-05-16 13:44 UTC, jsoref commented on extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts
> +const autoLinkPattern = /\<(\w+:\/{1,}[^\>\s]+)\>/g;
Given that `+` is already used in this pattern...
```suggestion
const autoLinkPattern = /\<(\w+:\/+[^\>\s]+)\>/g;
```

2022-05-16 14:55 UTC, mjbvz requested changes
Thanks for looking into this but autolinks don't require a `/`. For example: `<mailto:user@example.com>`

2022-05-16 15:10 UTC, jsoref commented
In theory one can register any arbitrary protocol `foo:` with their OS. Which means that yeah, it could be...

I think you could make the argument that: `<`+ [ `/` ] + xml-characters +`:` + xml-characters + [ space + attributes] + `>` shouldn't be treated as a protocol. It's really just an XML tag (or a closing tag).

It might make sense to use some zero-width assertions.

2022-05-17 23:03 UTC, mjbvz commented
Thanks for looking into this

Based on these comments and how common mark handles the code, I think this is by-design. I've gone ahead and closed the original issue: https://github.com/microsoft/vscode/issues/149475#issuecomment-1129401447

2022-05-17 23:03 UTC, closed without merging