support watch task reconnection
microsoft/vscode pull request #155120
Opened 2022-07-13 23:43 UTC by meganrogge

This PR fixes #

2022-07-13 23:45 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/browser/terminalService.ts
> +	private _taskReconnectedTerminals: ITerminalInstance[] = [];
to do: make this generic. the event didn't work so well for tasks and might not for other owners either because of timing

2022-07-13 23:46 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/browser/terminalService.ts
> +	private _taskReconnectedTerminals: ITerminalInstance[] = [];
maybe should be a map from owner to terminals

2022-07-13 23:58 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/browser/terminalService.ts
> +	private _taskReconnectedTerminals: ITerminalInstance[] = [];
and `reconnectionOwner` can be the string key of the map

2022-07-14 00:45 UTC, Tyriar requested changes

2022-07-14 00:45 UTC, Tyriar commented on src/vs/platform/terminal/common/terminal.ts
> +	task?: { label: string; id: string; lastTask?: string; group?: string };
Can this be a reconnection owner id or something and this data gets persisted by contrib/tasks? We don't want to mention tasks anywhere in terminal ideally

2022-07-14 00:45 UTC, Tyriar commented on src/vs/platform/terminal/common/terminal.ts
> +	task?: { label: string; id: string; lastTask?: string; group?: string };
This?

```json
reconnectionOwner: {
  ownerName: string;
  ownerId: number;
}
```

2022-07-14 00:45 UTC, Tyriar commented on src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
> +	private async _registerCommands(): Promise<void> {
Can revert this?

2022-07-14 00:45 UTC, Tyriar commented on src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts
> +		const terminals = this._terminalService.getReconnectedTerminals('Task');
2 refs should use a constant

2022-07-14 00:45 UTC, Tyriar commented on src/vs/platform/terminal/common/terminal.ts
> +	task?: { label: string; id: string; lastTask?: string; group?: string };
If that's not easily doable, a temporary fix is to give this a generic name with type `unknown` and validate the type in tasks. I'd be fine for that to live in terminal as it basically moves the tech debt out of terminal and into tasks.

2022-07-14 00:55 UTC, Tyriar approved these changes, later dismissed

2022-07-14 01:03 UTC, Tyriar approved these changes

2022-07-14 01:16 UTC, merged