Add settings option for status bar decoration in debugging session
microsoft/vscode pull request #155522
Opened 2022-07-18 16:55 UTC by KoushikSahu

This PR fixes #155294

2022-07-19 02:49 UTC, KoushikSahu commented
@roblourens Can you please review my PR? Also I believe you would be able to provide necessary permission to run the remaining gh actions.

2022-08-04 16:39 UTC, roblourens commented on src/vs/workbench/contrib/debug/browser/debug.contribution.ts
> +		'debug.DecorateStatusBar': {
Maybe `debug.enableStatusBarColor`?

2022-08-04 16:39 UTC, roblourens commented on src/vs/workbench/contrib/debug/browser/debug.contribution.ts
> +			description: nls.localize({ comment: ['This is the description for a setting'], key: 'decorateStatusBar' }, "Decorate status bar when debugger is connected."),
Comment is not necessary

2022-08-04 16:39 UTC, roblourens commented on src/vs/workbench/contrib/debug/browser/debug.contribution.ts
> +			description: nls.localize({ comment: ['This is the description for a setting'], key: 'decorateStatusBar' }, "Decorate status bar when debugger is connected."),
"Color status bar when debugger is active"

2022-08-04 16:39 UTC, roblourens commented on src/vs/workbench/contrib/debug/browser/statusbarColorProvider.ts
> +		if (decorateStatusBar) { this.enabled = isStatusbarInDebugMode(this.debugService.state, this.debugService.getViewModel().focusedSession); }
Should be formatted on 3 lines (running "Format Document" might fix this)

2022-08-05 18:32 UTC, KoushikSahu commented on src/vs/workbench/contrib/debug/browser/debug.contribution.ts
> +		'debug.DecorateStatusBar': {
lgtm

2022-08-05 18:32 UTC, KoushikSahu commented
@roblourens thanks for the review. Let me know if this works.

2022-08-05 19:12 UTC, roblourens requested changes
Actually, this needs a little more. `update()` should run immediately when the setting changes. I should be able to toggle this even while debugging and see the effect. And currently if I disable it while in a debugging session, then the color never goes away. So `this.enabled` should always be set to something when update runs, instead of skipping it. Please test it a little bit like this and make sure nothing weird can happen.

2022-08-05 19:23 UTC, KoushikSahu commented
> Actually, this needs a little more. `update()` should run immediately when the setting changes. I should be able to toggle this even while debugging and see the effect. And currently if I disable it while in a debugging session, then the color never goes away. So `this.enabled` should always be set to something when update runs, instead of skipping it. Please test it a little bit like this and make sure nothing weird can happen.

@roblourens Yeah I didn't test it this way. I'll try and figure this out.

2022-08-06 07:56 UTC, KoushikSahu commented
> Actually, this needs a little more. `update()` should run immediately when the setting changes. I should be able to toggle this even while debugging and see the effect. And currently if I disable it while in a debugging session, then the color never goes away. So `this.enabled` should always be set to something when update runs, instead of skipping it. Please test it a little bit like this and make sure nothing weird can happen.

@roblourens So I made sure that the `this.enable` is always set to some boolean when `update` function is called. The behaviour I got was the same as before. During the debugging session if user changes the setting then the color is not reflected immediately but after performing some debugging action (like step over, step up ...).

2022-08-09 05:11 UTC, roblourens commented
You can listen to `configurationService.onDidChangeConfiguration` and update when that setting is changed.

2022-08-20 05:53 UTC, KoushikSahu commented
Been busy this month. I have time available now. I will be working on the required code changes from now.

2022-10-05 15:57 UTC, jrieken commented
Did this go stale? Iff so I'll work on a PR

2022-10-23 18:34 UTC, KoushikSahu commented
> Did this go stale? Iff so I'll work on a PR

Not getting the time to work on this. Sorry for the inconvenience. Please take this issue up.

2022-10-23 18:34 UTC, closed without merging