JavaScript and Node.js walkthrough
microsoft/vscode pull request #157965
Opened 2022-08-12 00:19 UTC by DanielRosenwasser

I figured it would be worth opening a new PR for this one.

The feedback I got on https://github.com/microsoft/vscode/pull/151665 was effectively to scope things down and make a walkthrough that's just Node.js and JavaScript. Doing that brings some parity with other languages like Python and reduces the need to introduce HTML, at the expense of losing the convenience of the browser and web development.

Fixes https://github.com/microsoft/TypeScript/issues/48489
Ticks a box off on https://github.com/microsoft/vscode/issues/144062

Here's the current TODOs, with some specific callouts that I'd appreciate some input on.

* [ ] **Media Assets**: I'll need to work with @misolori @daviddossett on these.
  * [ ] Walkthrough icon
  * [ ] Media for each step (currently just a TODO page)
* [ ] **Workflow and Phrasing**
  * [ ] I added a button to restart VS Code in case `node` isn't present on the terminal. Should I?
  * [ ] Is there a better way to have a user graduate from running on the terminal to debugging?
* [ ] **Polish**
  * [ ] Can we either hide or fill in the step for installing Node.js? Is there an easy way to determine whether Node.js is already installed? (@mjbvz)
  * [ ] In the last step, if a user tries to run/debug a single JavaScript file in their root directory, the debugger takes *forever* to start. Can we fix this? (@connor4312)
* [ ] **Experiments**: Let's plumb these through (@devinvalenciano @isidorn @digitarald). Good experiments to start with:
  * [ ] How do we pitch this? Is it a "get started with JS" or a "get started with Node.js and JS" walkthrough?

2022-08-12 21:07 UTC, mjbvz reviewed
Looks like a great start!

For determining if node is on the users's system, I think you'll have to use `child_process` to check. Hopefully we can catch the majority of installs. Here's an example of how we find `git`: https://github.com/microsoft/vscode/blob/81e6a02c18da69547acdfa83613d9f09013ba854/extensions/git/src/git.ts#L80

2022-08-12 23:32 UTC, DanielRosenwasser commented
@mjbvz seems fine but then I have to do that every time the extension is activated, right? It seems wasteful to spawn up a process every time a `.ts`/`.js` file is opened. I can do it, but it probably makes sense for this to live in its own extension.

2022-08-13 00:15 UTC, DanielRosenwasser commented
Actually, I seem to be having some trouble getting the walkthrough wired up with that. I'll push up my new changes in a minute but the current state is this:

I've defined a new command

```ts
// extensions/typescript-language-features/src/commands/jsWalkthrough.ts
// ...

export class NodeInstallationFoundCommand {
	public static readonly id = 'javascript-walkthrough.commands.nodeInstallationFound';
	public readonly id = 'javascript-walkthrough.commands.nodeInstallationFound';
	public execute() {
		vscode.window.showInformationMessage('yay it happened');
	}
}
```

and registered it

```ts
// extensions/typescript-language-features/src/commands/index.ts
// ...

	commandManager.register(new NodeInstallationFoundCommand());
```

and fired the command after it's registered and after I check for if Node exists.

```ts
// extensions/typescript-language-features/src/extension.ts
// ...

	hasNode().then(
		async (isInstalled) => {
			if (isInstalled) {
				await vscode.commands.executeCommand('javascript-walkthrough.commands.nodeInstallationFound');
				vscode.window.showInformationMessage('it is installed :)');
			}
			else {
				vscode.window.showErrorMessage('it aint installed :(');
			}
		}
	);
```

When the extension gets activated, I *do* see the information message; however, in the walkthrough I have an `onCommand` completion event

```jsonc
          {
            "id": "walkthroughs.jsWelcome.downloadNode.forMacOrWindows",
            "title": "%walkthroughs.jsWelcome.downloadNode.forMacOrWindows.title%",
            "description": "%walkthroughs.jsWelcome.downloadNode.forMacOrWindows.description%",
            "media": {
              "markdown": "resources/walkthroughs/TODO.md"
            },
            "when": "isWindows || isMac",
            "completionEvents": [
              "onLink:https://nodejs.org/en/download/",
              "onCommand:javascript-walkthrough.commands.nodeInstallationFound"
            ]
          },
```

but it doesn't seem like that step is marked as completed.

Anything obvious I'm doing wrong?

2022-08-30 20:57 UTC, DanielRosenwasser commented
Hey all, here's the current status.

First, the walkthrough just has 4 steps now

* Install Node.js
* Create a JS File
* Run & Debug the JS File
* Read more

The notable stuff on each step is

* "Install Node.js" still segments you based on Linux vs Windows/Mac. I don't bother to do any auto-detection  to see whether Node.js is already installed. This is partially because the API seems to have issues with marking a step as completed programmatically. @karrtikr got around this in https://github.com/microsoft/vscode-python/pull/19379 by just hiding the tile with a context variable. I'm probably not going that route in this PR.
* "Create a JS File" is minimal. I just use `console.log`.
* "Run & Debug" is merged into a single step.
  * I mention running from the terminal, but I don't present a button to do it.
  * I *do* check that Node was installed when clicking the debug button. I give the user the option of <btn>Reload VS Code</btn>, <btn>Try Debugging Anyway</btn>, and <btn>Dismiss</btn>.

    ![Run and Debug Failure Dialog](https://user-images.githubusercontent.com/972891/187541461-74e155f7-f50d-4783-a208-5bb4d9d0ef0b.png)


I will need assets for each step, along with a walkthrough icon which should probably use the JS community logo, the Node.js logo, or both. I've created some tentative assets, which I derived from the Python walkthrough, but they don't appear aligned, so I need some help on that.

I don't expect this to go into the August release at this point, but the sooner the better.

2022-08-30 21:37 UTC, daviddossett commented
I'll add the assets to this PR this week 👍

2022-09-02 16:57 UTC, daviddossett commented
Updated icon and SVGs

https://user-images.githubusercontent.com/25163139/188202440-4cdbbc79-d3f8-41e4-933d-994a89b7054f.mp4

2022-09-12 19:55 UTC, DanielRosenwasser commented on extensions/typescript-language-features/package.json
> +        "when": "isWindows && workspacePlatform == windows || isMac && workspacePlatform == mac || isLinux && workspacePlatform == linux",
```suggestion
        "when": "false",
```

2022-09-12 21:25 UTC, mjbvz requested changes
The icon.png file is used in VS Code's extension UI. I think it would be confusing to use a `js` specific one for the JS/TS language features extension

2022-09-12 21:36 UTC, daviddossett commented
> The icon.png file is used in VS Code's extension UI. I think it would be confusing to use a `js` specific one for the JS/TS language features extension

That's fair. I'll replace with something less specific.

2022-09-12 22:09 UTC, DanielRosenwasser commented
Huh - is there no way to provide an alternative icon for a walkthrough? (@lramos15)

2022-09-13 13:38 UTC, lramos15 commented
Not sure I understand the question, what do you mean by alternative icon @DanielRosenwasser

2022-09-13 17:15 UTC, daviddossett commented
> Not sure I understand the question, what do you mean by alternative icon @DanielRosenwasser

If I understood correctly I think he means that these icons are currently both using the same source icon. I.e. you can't use a different icon for a walkthrough vs. the extension itself.

<img width="287" alt="CleanShot 2022-09-13 at 10 14 13@2x" src="https://user-images.githubusercontent.com/25163139/189965188-f74a3284-9545-45be-a8fe-07c02612a2ae.png">

<img width="390" alt="CleanShot 2022-09-13 at 10 14 24@2x" src="https://user-images.githubusercontent.com/25163139/189965204-e8b28330-3638-457f-8eec-13b152a1c416.png">

2022-09-13 21:20 UTC, DanielRosenwasser commented
That's correct - but I don't think we should block this PR over the icon. I would rather begin experimenting here, and use the suggested icon if walkthroughs eventually do support their own icons.

2022-09-13 22:49 UTC, mjbvz approved these changes, later dismissed

2022-09-14 16:35 UTC, mjbvz approved these changes

2022-09-14 16:53 UTC, merged