adjust width for CJK characters
microsoft/vscode pull request #15838
Opened 2016-11-21 20:59 UTC by rebornix

Fix #11859 . Read character from view to get the correct width of a character.

2016-11-23 18:58 UTC, alexdima requested changes
Looks ok, but the new code should run only if the cursor is configured to be rendered as a block. Currently, this makes line cursors (the default we ship with) render as a block cursor

2016-11-23 18:58 UTC, alexandrudima commented on src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts
> +			let visibleRangeForCharacter = ctx.linesVisibleRangesForRange({
@rebornix This extra call should be done only if the cursor style is a block cursor

2016-11-23 18:58 UTC, alexandrudima commented on src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts
> +			let desiredWidth = '1ch';
@rebornix Computing the desiredWidth and setting it needs to happen only if the cursor style is set to block.

2016-11-27 22:18 UTC, rebornix commented
Comments addressed. Only update cursor width if its style is block or underline.

@alexandrudima we had issues with underline cursor style as well, which should be taken care of the same way as block cursor. Besides, this fix makes tab more explicit as below

<img width="479" alt="screen shot 2016-11-27 at 1 56 01 pm" src="https://cloud.githubusercontent.com/assets/876920/20652336/48412eea-b4ac-11e6-823f-f180cf5b75ad.png">
<img width="501" alt="screen shot 2016-11-27 at 1 56 15 pm" src="https://cloud.githubusercontent.com/assets/876920/20652337/4841808e-b4ac-11e6-823e-70a702d9bd90.png">

2016-11-29 16:38 UTC, alexdima approved these changes

2016-11-29 16:38 UTC, alexandrudima commented
:+1:

2016-11-29 16:38 UTC, merged