use common task ID instead of map key
microsoft/vscode pull request #159233
Opened 2022-08-25 22:30 UTC by meganrogge

fix #158886

2022-08-25 23:16 UTC, mjbvz requested changes

2022-08-25 23:16 UTC, mjbvz commented on src/vs/workbench/contrib/terminal/test/browser/links/terminalLocalLinkDetector.test.ts
> +	suite.only('Windows', () => {
Looks like a missed `.only`

2022-08-25 23:17 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/test/browser/links/terminalLocalLinkDetector.test.ts
> +	suite.only('Windows', () => {
```suggestion
	suite('Windows', () => {
```

2022-08-25 23:17 UTC, mjbvz approved these changes, later dismissed

2022-08-25 23:44 UTC, meganrogge commented
it works in the build 👍🏼

2022-08-25 23:52 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/test/browser/links/terminalLocalLinkDetector.test.ts
> +	'foo bar'
```suggestion
```

2022-08-26 01:28 UTC, DonJayamanne approved these changes

2022-08-26 01:28 UTC, merged

2022-08-26 13:26 UTC, meganrogge commented
works well - anything I should be concerned abt with this change @alexr00 ?

2022-08-26 14:18 UTC, alexr00 commented
Looks like it should be safe!