Adding context menu on the sticky scroll line (Fixes https://github.com/microsoft/vscode/issues/162330)
microsoft/vscode pull request #162425
Opened 2022-09-30 08:55 UTC by aiday-mar

Fixes https://github.com/microsoft/vscode/issues/162330.

Adding the possibility to toggle the sticky scroll line by right clicking on it. I had to modify the ClickLinkGesture in order to introduce a new parameter 'hasRightClick' which will differentiate between a normal click and a right click. Here is an example of how it currently works:

![sticky-scroll-contextmenu](https://user-images.githubusercontent.com/61460952/193232947-e5b8a606-1a0f-433c-8383-fd0076f3d457.gif)

2022-09-30 10:50 UTC, Tirednfedup requested changes
Is there any suggestions?

2022-09-30 12:33 UTC, jrieken commented on src/vs/platform/actions/common/actions.ts
> +	static readonly StickyScroll = new MenuId('StickyScrollMenu');
nit: use the `Context` suffix, eg.`StickyScrollContext`

2022-09-30 12:35 UTC, jrieken reviewed
This looks really good, left a tiny nit about the name of the menu (consistency matters)

I would also suggest to add the 'Toggle Breadcrumbs' command into the command. I believe sticky scroll and breadcrumbs are closely related and configured them in a single place sounds like a good idea. You can find the command here: [ToggleBreadcrumb](https://github.com/microsoft/vscode/blob/20e2a1524df3b40b3d96e42d468ac6d3ed23e545/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L500)

2022-09-30 13:24 UTC, gjsjohnmurray commented
> I would also suggest to add the 'Toggle Breadcrumbs' command

Doing this would also act as a clue about where I might be able to go to toggle Sticky Scroll back on again. But only if right-click on breadcrumbs also gave this kind of menu. Without that I have to realize that the View menu is the place to go, or Command Palette.

Also, I wonder if the "Toggle prefix is necessary? And should other editor-view-related toggles appear here as well? For example Minimap (currently on a context menu of an editor's vertical scrollbar, as well as one from the minimap itself when visible).

2022-09-30 13:28 UTC, aiday-mar commented
> > I would also suggest to add the 'Toggle Breadcrumbs' command
> 
> Doing this would also act as a clue about where I might be able to go to toggle Sticky Scroll back on again. But only if right-click on breadcrumbs also gave this kind of menu. Without that I have to realize that the View menu is the place to go, or Command Palette.
> 
> Also, I wonder if the "Toggle prefix is necessary? And should other editor-view-related toggles appear here as well? For example Minimap (currently on a context menu of an editor's vertical scrollbar, as well as one from the minimap itself when visible).

I would agree that having the menu appear also on the breadcrumbs bar would be more intuitive.

2022-10-04 10:35 UTC, jrieken commented
> Also, I wonder if the "Toggle prefix is necessary? And should other editor-view-related toggles appear here as well?

That's a good point. It seems that we don't have a good story for this, we often use "Toggle XYZ" because of places that don't render the check mark, e.g the command palette. We should maybe expand on the existing toggled title so that the default label is "XYZ" (which gets rendered with the check mark_ and then have on/off labels like "Show XYZ" and "Hide XYZ" for places that don't renderer the check mark.

This is an interesting discussion but I am in favour of leaving this out of this PR.

2022-10-04 11:03 UTC, aeschli approved these changes

2022-10-04 15:00 UTC, jrieken commented
There is https://github.com/microsoft/vscode/pull/162672 for the toogle-title disuccsion

2022-10-04 16:13 UTC, merged