Log where an editor action was triggered from
microsoft/vscode pull request #16250
Opened 2016-11-30 05:46 UTC by chrmarti

For evaluating #15156

@bpasero I would like to add a 'from' to the editor actions telemetry, the same way we have that for workbench actions. Could you take a look? I might be missing things since the data flows past a lot of code.

2016-11-30 05:47 UTC, chrmarti commented on src/vs/platform/keybinding/browser/keybindingServiceImpl.ts
> +			this._commandService.executeCommand(commandId, objects.assign({ from: 'keybinding' }, resolveResult.commandArgs || {})).done(undefined, err => {
Not sure if copying the arguments object is save here. What are the cases that come into play?

2016-11-30 06:18 UTC, bpasero commented
@chrmarti I suggest @alexandrudima to review this. My initial feeling is that you cannot change command arguments (e.g. by adding one) because some commands might assume a specific set of arguments to be passed over to run properly.

2016-11-30 18:52 UTC, chrmarti commented
@alexandrudima The only way I can see this being implemented properly is with an additional parameter to commandService.executeCommand() so we can pass contextual information like 'from'. What do you think?

2016-11-30 22:30 UTC, chrmarti commented
@bpasero / @alexandrudima It looks like we have been using that 'args' object for passing along the 'from' argument for a while. Maybe that should be cleaned up?

2016-12-05 20:40 UTC, alexandrudima commented
Sorry for being late, I can't assess the risks of this change, since there might be commands in our system or coming in from an extension that might find a new argument unexpected. This change also prohibits any command from being able to use the argument "from". Perhaps there might be a better way to get this information? i.e. the keybinding service could directly log a telemetry event?

@jrieken for ideas

2016-12-06 08:38 UTC, jrieken requested changes

2016-12-06 08:38 UTC, jrieken commented on src/vs/platform/keybinding/browser/keybindingServiceImpl.ts
> +			this._commandService.executeCommand(commandId, objects.assign({ from: 'keybinding' }, resolveResult.commandArgs || {})).done(undefined, err => {
:-1: for multiple reasons. For once, the command args can be `undefined`, `null`, or a primitive values. I don't think object.assign is happy in that case. Also, this changes the argument the command is receiving which potentially invalidates its execution.

2016-12-06 08:45 UTC, jrieken commented
My suggestion would be to either have "twin" calls like `commandService.excuteCommand(id, args)` and `telemetryService.publicLog(...)` or to have another method on the `ICommandService` ala `executeCommand<T>(id: string, telemetryData:any, ...args: any[]): TPromise<T> {`

2016-12-30 15:58 UTC, closed without merging