Allow passing initial dom dimensions to lists
microsoft/vscode pull request #164101
Opened 2022-10-20 03:11 UTC by mjbvz

This allows callers to provide initial dimensions to lists. This lets us avoid an expensive call to `getContentHeight` in the `List` constructor

By adopting this for the notebook editor widget, we cut the creation time of the widget from around 30ms to around 10ms

Before:

<img width="534" alt="Screen Shot 2022-10-19 at 8 01 06 PM" src="https://user-images.githubusercontent.com/12821956/196847391-7f35ddbf-70c9-44fc-ad45-ae8b7a8bb1bc.png">

After:

<img width="685" alt="Screen Shot 2022-10-19 at 7 58 36 PM" src="https://user-images.githubusercontent.com/12821956/196847624-202f95be-68da-411f-9ae9-49d5e2c96e40.png">

Unfortunately `updateShadowElement` still ends up forcing a restyle later a bit later, so the entire duration of `setInput` only drops from ~50ms to 40ms with this. Hopefully we can figure out a way around that too

2022-10-20 03:22 UTC, rebornix submitted a review, later dismissed
👏 this is great! Wish we can save some time for the shadow element measurement in the future.

2022-10-20 07:40 UTC, joaomoreno requested changes

2022-10-20 22:17 UTC, mjbvz commented on src/vs/base/browser/ui/list/listView.ts
> +		this.layout(initialDimensions?.height, initialDimensions?.width);
Ok, I'll pass this as an `initialSize` option instead

2022-10-21 07:06 UTC, joaomoreno approved these changes, later dismissed

2022-10-21 10:31 UTC, jrieken commented
Cool stuff. I don't believe my review is needed but I see some unit test failures 🤓

2022-10-21 18:04 UTC, mjbvz commented
Turns out `TestInstantiationService` was implicitly casting to `any`, which hide some important errors :) Should be fixed now

2022-10-21 18:09 UTC, mjbvz commented
Whoops, my fix actually revealed quite a few problems! (that watch didn't catch). Will make more scoped fix for now

2022-10-21 18:14 UTC, joaomoreno approved these changes

2022-10-21 18:25 UTC, merged