Moves css rules from links.ts to links.css
microsoft/vscode pull request #166258
Opened 2022-11-14 08:49 UTC by dmartzol

Ref: https://github.com/microsoft/vscode/issues/165169

Uses css variable for `src/vs/editor/contrib/links/browser/links.ts`.

2022-11-14 08:52 UTC, dmartzol commented
@microsoft-github-policy-service agree [company="default"]

2022-11-14 08:52 UTC, dmartzol commented
@microsoft-github-policy-service agree

2022-11-14 13:44 UTC, aeschli requested changes

2022-11-14 19:14 UTC, dmartzol commented on src/vs/editor/contrib/links/browser/links.css
> +	color: var(--vscode-activeLink-foreground) !important;
ahh, thank you! Fixed it

2022-11-15 08:58 UTC, aeschli approved these changes, later dismissed

2022-11-15 08:58 UTC, aeschli commented
Thanks @weartist !

2022-11-16 12:24 UTC, aeschli approved these changes

2022-11-16 12:26 UTC, dbaeumer approved these changes

2022-11-16 12:48 UTC, merged