Fix hover escape key focus impl
microsoft/vscode pull request #166657
Opened 2022-11-17 23:43 UTC by rzhao271

Ref #159088

Previously, when pressing the escape key from a focused hover, the user loses the previously focused element and has to tab back to it. This PR attempts to fix that scenario by placing the focus back to the previously focused element.

2022-11-22 19:53 UTC, rzhao271 commented
Demo showing tab looping behaviour
![Screencap of the Modified elsewhere indicator in the Settings editor being focused. Pressing space opens the hover. Tabbing around goes to the various links. Pressing escape closes the hover and focuses back on the indicator.](https://user-images.githubusercontent.com/7199958/203408322-20906b52-815c-4c21-b9be-163ab527f294.gif)

2022-11-22 20:39 UTC, Tyriar requested changes

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverService.ts
> +	private _lastFocusedElementBeforeOpen: HTMLElement | null = null;
Let's use undefined if there are only 2 states

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverWidget.ts
> +	private readonly _lastFocusedElementBeforeOpen: HTMLElement | null;
Do we need to track this element in both the service and the widget?

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverWidget.ts
> +	private _addedTabLoop: boolean = false;
I think "focus trap" is a more common name for this

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverWidget.ts
> +			const afterContainerFocusElement = dom.append(this._hoverContainer, $('div.focus-after'));
I don't think these classes are used

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverWidget.ts
> +					const parsedNode = <HTMLElement>node;
nit

```suggestion
					const parsedNode = node as HTMLElement;
```

2022-11-22 20:39 UTC, Tyriar commented on src/vs/workbench/services/hover/browser/hoverWidget.ts
> +		}
This would be cleaner/safer moved into `addTabLoop`

2022-11-25 11:06 UTC, alexr00 commented on src/vs/workbench/services/hover/browser/hoverService.ts
<span style="background-color:#542426;">&nbsp;&nbsp;Hello&nbsp;&nbsp;</span>

2022-11-28 18:24 UTC, Tyriar approved these changes

2022-11-28 18:33 UTC, merged