moves css rules for activityaction.css
microsoft/vscode pull request #167196
Opened 2022-11-24 18:24 UTC by dmartzol

Ref: https://github.com/microsoft/vscode/issues/165169

Moves css rules for ` src/vs/workbench/browser/parts/activitybar/activitybarActions.ts`

2022-12-10 10:12 UTC, bpasero requested changes

2022-12-10 10:12 UTC, bpasero commented on src/vs/workbench/browser/parts/activitybar/media/activityaction.css
> +.monaco-workbench .activitybar > .content :not(.monaco-menu) > .monaco-action-bar .action-item .action-label.profile-activity-item,
Same rule repeated 3 times, maybe @sandy081 did a mistake here?

2022-12-10 10:12 UTC, bpasero commented on src/vs/workbench/browser/parts/activitybar/media/activityaction.css
> +	visibility: hidden;
This was previously only being set if there is a `ACTIVITY_BAR_ACTIVE_FOCUS_BORDER` color, so I think this change changes the semantic in that it is now always `hidden` even without a `ACTIVITY_BAR_ACTIVE_FOCUS_BORDER`

2022-12-10 10:12 UTC, bpasero commented on src/vs/workbench/browser/parts/activitybar/media/activityaction.css
> +	z-index: 0;
Similar to above, this was only set when `ACTIVITY_BAR_ACTIVE_BACKGROUND` was configured.

2022-12-10 10:12 UTC, bpasero commented on src/vs/workbench/browser/parts/activitybar/media/activityaction.css
> +	content: "";
Similar to above, this was behind a check for `activeContrastBorder`

2022-12-12 18:35 UTC, bpasero commented
We discussed this in the team today: changes to other properties that are not colors or borders will still require some JS code, for example:
* listen to theme changes manually
* toggle a CSS class based on the presence of a color
* in CSS set the non-CSS-variable based properties based on that

2022-12-13 14:48 UTC, sandy081 commented
This is not a straight forward porting from JS to CSS using variables. This needs some logic to be retained in JS and shall be tested with all possible cases. Sounds not trivial.

2022-12-21 11:24 UTC, closed without merging