Add border to quick pick to match menus
microsoft/vscode pull request #167773
Opened 2022-11-30 21:56 UTC by daviddossett

- Adds `widgetBorder`
- Adds border to quick input

https://user-images.githubusercontent.com/25163139/204916542-5e47b672-de94-4765-b480-7329a9a1a3e5.mp4

2022-12-01 21:43 UTC, tsr-images submitted a review, later dismissed

2022-12-05 19:02 UTC, amunger approved these changes, later dismissed

2022-12-05 19:10 UTC, Tyriar requested changes
I think the notifications look fantastic, I'm not sure about the other cases like the rename widget though. This deserves discussion in the UX sync imo

2022-12-13 18:15 UTC, Tyriar approved these changes

2022-12-13 18:27 UTC, merged