`terminal.quickFixes` -> `terminalQuickFixes`
microsoft/vscode pull request #173860
Opened 2023-02-08 18:47 UTC by meganrogge

fix #167577

2023-02-08 19:22 UTC, Tyriar requested changes

2023-02-08 19:22 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/common/terminal.ts
> -			quickFixes: {
I think this is still under `terminal.terminalQuickFixes` because of `extensionPoint: 'terminal'` above

2023-02-08 19:22 UTC, Tyriar commented
Does this need adoption in the npm extension?

2023-02-08 20:14 UTC, meganrogge commented on extensions/npm/package.json
>      "onTaskType:npm",
it said these could be removed

2023-02-08 20:15 UTC, meganrogge commented
tested using the npm quick fixes via `npm audt` and saw the quick fix show up, though not always bc of https://github.com/microsoft/vscode/issues/172068

2023-02-09 17:37 UTC, Tyriar approved these changes

2023-02-09 17:38 UTC, merged