Explicitly call exthosttelemetry on command failure
microsoft/vscode pull request #173990
Opened 2023-02-09 19:52 UTC by lramos15

Fixes #172132

2023-02-09 20:12 UTC, Tyriar approved these changes, later dismissed

2023-02-09 20:45 UTC, lramos15 commented
FYI @jrieken I removed a duplicate test and merged another one because there was warnings about them in the editor. Feel free to revert that if you don't want those changes since I was just cleaning up while in the area.

2023-02-09 20:51 UTC, Tyriar submitted a review, later dismissed

2023-02-10 07:55 UTC, jrieken requested changes
Let's simply rename test to make them unique

2023-02-10 07:55 UTC, jrieken commented on src/vs/workbench/api/test/browser/extHostApiCommands.test.ts
This is just a name duplication but a (slighty) different test (provider returns one or two elements) so we should keep both and simply rename them

2023-02-10 07:55 UTC, jrieken commented on src/vs/workbench/api/test/browser/extHostLanguageFeatures.test.ts
> +		called = [false, false, false];
Better keep the test but use a different name?

2023-02-10 15:23 UTC, Tyriar commented
Integration tests failing

2023-02-10 15:47 UTC, lramos15 commented
> Integration tests failing

Yeah waiting to hear back from @jrieken about possible thoughts. The `IExtHostTelemetry` initiates RPC messages to sync the levels across processes so now by adding it to a dependency of commands there is an RPC message that goes through when the service is instantiated that wasn't there before. It's just 1 so not really a perf issue, but we were asserting no RPC messages at all before.

2023-02-10 16:44 UTC, jrieken approved these changes

2023-02-10 16:44 UTC, merged