Fix package.json Auto complete
microsoft/vscode pull request #17423
Opened 2016-12-16 22:05 UTC by mjbvz

Fixes #17342

**Bug**
I believe that 739d8ca77f6215a5a385587e6e6c7d66fdbe15c6 introduced a regression for package.json auto complete where we end up inserting the text `*` when completing dependency versions

**Fix**
Insert `""` instead of star to match previous behavior better

2016-12-20 08:30 UTC, jrieken commented
Not so sure. The afore mentioned commit replaced `insertText += ': "{{*}}"';` with `insertText.appendText(': ').appendPlaceholder('*');`. Both should describe a placeholder containing `*`

2016-12-20 08:32 UTC, jrieken requested changes

2016-12-20 08:32 UTC, jrieken commented on extensions/javascript/src/features/packageJSONContribution.ts
>  											if (!isLast) {
should be `"*"`, not just `""`

2016-12-20 23:52 UTC, mjbvz commented
@jrieken The reason using an empty string was that I was trying to get the version intellisense to trigger properly after you complete the package name. Here's what I originally tried:

```js
insertText.appendText(': "').appendPlaceholder('*').appendText('"');
```

![dec-20-2016 15-47-34](https://cloud.githubusercontent.com/assets/12821956/21372378/a3ec2d90-c6cb-11e6-8559-f11ec0a8e1b0.gif)

The makes the `package.json` valid, but you have to type a character in order to get any intellisense for the version names. Is this what you recommend using instead, or was it something else?

2016-12-21 08:06 UTC, jrieken commented
> Is this what you recommend using instead, or was it something else?

Unsure. I didn't originally write the code but just migrated it. Naturally, I try to get its original behaviour back. What you say makes sense, we should check with @aeschli why it was `"*"` in the beginning

2016-12-30 12:50 UTC, jrieken approved these changes

2016-12-30 12:50 UTC, merged