Improve Markdown code block tokens
microsoft/vscode pull request #17591
Opened 2016-12-20 07:25 UTC by joshpeng

Code blocks without a language weren't tokenized. Code blocks didn't have their ending ``` punctuation tokenized. Both fixed.

Code blocks used to only have one token. Now each block has the following tokens available for syntax highlighters:
- Starting and ending ``` punctuations
- Code block's language setting
- Code snippet

2016-12-20 07:25 UTC, msftclas commented
Hi __@joshpeng__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.microsoft.com.
    </span>

TTYL, MSBOT;

2016-12-20 16:39 UTC, msftgits commented
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

2016-12-20 16:39 UTC, msftclas commented
Hi __@joshpeng__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSBOT;

2016-12-20 23:35 UTC, mjbvz requested changes
I like the overall idea, but this introduces a number of important regressions that need to be fixed before we can merge this in. Please take a look at the comments and let me know if you have any questions.

2016-12-20 23:35 UTC, mjbvz commented on extensions/markdown/syntaxes/markdown.tmLanguage
> +					<string>(^|\G)\s*([`~]{3,})\n</string>
We have to use a while clause here. This prevents broken language grammars from leaking outside of the fenced block. Switching to while from end fixed a large number of syntax highlighting issues.

2016-12-20 23:35 UTC, mjbvz commented on extensions/markdown/syntaxes/markdown.tmLanguage
> +					<string>(^|\G)\s*([`~]{3,})\s*(html|htm|shtml|xhtml|inc|tmpl|tpl)\n</string>
Keep the `(\s+.*)?$`bit. We allow arbitrary text on the rest of the line after the language identifier to support passing other attributes (line line numbers) that some markdown engines support.

2016-12-20 23:35 UTC, mjbvz commented on extensions/markdown/syntaxes/markdown.tmLanguage
> +					<string>(^|\G)\s*([`~]{3,})\n</string>
This should also reverted to how it was before so that we consume any number of spaces after the fence end and the end of line.

2016-12-20 23:35 UTC, mjbvz commented on extensions/markdown/syntaxes/markdown.tmLanguage
> +					<string>(^|\G)\s*([`~]{3,})\n</string>
Also, the closing fenced code block should match the fence type originally used. That's why we used the back references instead of ```[`~]```

2016-12-21 01:30 UTC, joshpeng commented on extensions/markdown/syntaxes/markdown.tmLanguage
> +					<string>(^|\G)\s*([`~]{3,})\n</string>
Hmm. That is why the closing ``` wasn't captured though. I'll continue thinking about how to achieve both our goals.

2016-12-21 11:15 UTC, joshpeng commented
Latest commit addresses previous code review's issues in the following manner:
1. Originally, using while instead of end prevented broken language grammar from leaking, but it also prevented capturing the closing fence punctuation. Now I am nesting the while-captures inside a primary pattern to achieve capturing of the closing fence while still preventing grammar leaks.

2. `(\s+.*)?$` at the end of begin-captures added back and tokenized as `fenced_code.block.language.attributes`. This is for any arbitrary text after the language identifier

3. End-captures reverted to once again consume all whitespace after the closing fence as well as matching the opening fence's punctuation.

4. End-captures closing fence's prefix whitespace handling improved to cover some scenarios where it should be detected as a raw block starter instead of fenced block closer.

2016-12-27 16:27 UTC, joshpeng commented
@mjbvz Hope you had a great Christmas. Was wondering if you had a chance to see these changes? Thanks.

2016-12-31 00:43 UTC, mjbvz commented
The change looks good.

Before we merge this in, can you please take a look at the failing tests in travis. You likely have to run the colorization tests again locally and check in the updated markdown test file. See the `"VS Code Tokenizer Tests"` in the `launch.json`

2016-12-31 02:41 UTC, joshpeng commented
@mjbvz I've uploaded the updated tokenizer Markdown test, but Travis is still failing. Is that expected?

2017-01-03 18:03 UTC, merged

2017-01-03 18:05 UTC, mjbvz commented
@joshpeng Thank you for this change. I've gone ahead and merged it in. It should be available in the next insiders build

2017-02-04 19:12 UTC, joshpeng commented
@mjbvz How do I get mentioned for my contributions in the release notes of 1.9.0? ;(

2017-02-08 02:07 UTC, mjbvz commented
Sorry about that @joshpeng. Let me see if I can fix things

@gregvanl I thought the contributor lists for the release notes was automatically generated. Did the PR have to be marked with "January 2017" for that to happen? What's the best way to update the list post-release?

2017-02-09 16:59 UTC, joshpeng commented
@mjbvz Didn't make it into 1.9.1 notes either. oh well :[

2017-02-09 21:58 UTC, mjbvz commented
I've added you to the 1.9 release notes: https://github.com/Microsoft/vscode-docs/commit/d0e9826fe5c6ec712d79c7377713fa0ca0692b0b

Sorry for the omission when this was first published and thanks again for the PR