don't react to disposing view types if the workbench is shutting down
microsoft/vscode pull request #176450
Opened 2023-03-07 22:18 UTC by amunger

Fixes https://github.com/microsoft/vscode/issues/176311#issuecomment-1457572937

If the workbench is shutting down, we don't need to worry about closing down editors in reaction to losing a `viewtype`.

2023-03-08 06:52 UTC, bpasero requested changes
Why not just have the listener in an extra `IDisposable` that gets disposed `onWillShutdown`?

2023-03-09 08:10 UTC, jrieken approved these changes

2023-03-09 10:43 UTC, bpasero commented on src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
> +		lifecycleService.onWillShutdown((e) => {
I think he pushed a change to use `Event.once` later.

2023-03-09 10:43 UTC, bpasero approved these changes
Awesome!

2023-03-09 11:11 UTC, jrieken commented on src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
> +		lifecycleService.onWillShutdown((e) => {
Oh, I dislike GH PR notifications very much.

2023-03-09 16:59 UTC, merged