Use the CommandQuickAccess provider
microsoft/vscode pull request #176682
Opened 2023-03-09 19:41 UTC by lramos15

Appears the `MenuRegistry` is missing editor commands for the command palette so commands like `Format Document` are not available. 

Maybe we should think about switching to the `CommandRegistry` at some point, but for now the command palette has nice names for common commads which makes finding what you want for development easy.

2023-03-09 19:46 UTC, TylerLeonhardt requested changes
Moving from platform to workbench means this is no longer available in Monaco standalone.

2023-03-09 19:50 UTC, lramos15 commented
> Moving from platform to workbench means this is no longer available in Monaco standalone.

This is a command I introduced to help me with some debugging related efforts. It was never intended to work in standalone monaco.

2023-03-09 20:03 UTC, TylerLeonhardt approved these changes, later dismissed

2023-03-09 20:49 UTC, TylerLeonhardt commented
FYI @bpasero would love your thoughts

2023-03-09 22:22 UTC, TylerLeonhardt approved these changes

2023-03-09 22:22 UTC, merged

2023-03-10 09:26 UTC, bpasero requested changes
I commented inline.

2023-03-10 09:26 UTC, bpasero commented on src/vs/workbench/contrib/quickaccess/browser/commandsQuickAccess.ts
> +	public getCommandInfo(): Array<ICommandQuickPick> {
```suggestion
	getCommandInfo(): Array<ICommandQuickPick> {
```

2023-03-10 09:26 UTC, bpasero commented on src/vs/workbench/contrib/quickaccess/browser/commandsQuickAccess.ts
> +CommandsRegistry.registerCommand('_getAllCommands', async function (accessor: ServicesAccessor) {
Why do we need this? It is somewhat ugly that we instantiate a UI component here only to get to the commands. Maybe the functionality for getting the commands should better be extracted to its own function or class?