keybindings: add support for multi-command keybindings
microsoft/vscode pull request #176974
Opened 2023-03-13 15:47 UTC by ulugbekna

Based on https://github.com/microsoft/vscode/pull/176973

Notes: 

- This doesn't add support for multi-command keybindings that come by default and contributed by extension -- while the latter may be desirable, I'm not sure about the former. This decision mostly stems from the note below.

- Multi-command keybindings are not supported by keybinding editing service & keybinding editor (model opened by "Preferences: Open Keyboard Shortcuts" command)

Closes https://github.com/microsoft/vscode/issues/871

2023-03-13 17:41 UTC, aeschli commented on src/vs/platform/keybinding/common/abstractKeybindingService.ts
> +			this._log(`+ Invoking command(s) ${resolveResult.commands}.`);
This will result in `'+ Invoking command(s) [object Object].'`

2023-03-13 19:56 UTC, aeschli requested changes

2023-03-13 20:14 UTC, ulugbekna commented on src/vs/workbench/services/keybinding/common/keybindingIO.ts
> +				if (cmd.args) {
oh, good catch, thanks! pushed the fix

2023-03-14 08:22 UTC, aeschli approved these changes, later dismissed
Looks good!
There are a lot of TODO's. You might want to make a pass and remove the one's you don't plan to fix (or change them to regular comments)

2023-03-16 15:28 UTC, closed without merging