Add editor encoding api
microsoft/vscode pull request #177434
Opened 2023-03-17 06:44 UTC by Tarrowren

see https://github.com/microsoft/vscode/issues/824

2023-08-30 18:58 UTC, TosoxDev commented
Please merge it

2023-08-30 19:01 UTC, TosoxDev approved these changes
Looks great! The changes in this pull request are well-structured and address the issue efficiently. Code quality is solid. Please merge it dear collaborators.

2023-11-16 07:41 UTC, angelozerr commented
Is there any chance to merge this PR?

2023-12-05 08:16 UTC, lygstate commented
ping for merge

2023-12-07 01:08 UTC, lygstate commented on src/vs/workbench/api/common/extHostTextEditor.ts
> +			setEncoding(encoding: string): void {
: Promise<void>

2023-12-07 01:08 UTC, lygstate commented on src/vscode-dts/vscode.proposed.editorEncoding.d.ts
> +		setEncoding(encoding: string): void;
: Promise<void>

2023-12-08 14:08 UTC, Tarrowren commented on src/vs/workbench/api/common/extHostTextEditor.ts
> +			setEncoding(encoding: string): void {
done :)

2024-01-22 15:22 UTC, TosoxDev commented
Is there any chance to merge this PR?

2024-02-20 13:11 UTC, denniskp commented
Bump pull request

2024-04-16 09:16 UTC, feed3r commented
We also asked for the very same thing and proposed to implement a PR like this [here](https://github.com/microsoft/vscode/issues/210041)

It would be really good to know if this has some possibility to be merged or if there is any other reason to not merge it.

2024-05-14 00:18 UTC, billgan1024 commented
ping for merge

2024-06-27 10:30 UTC, Tosox commented on src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
The extensionsApiProposals have been moved to [src/vs/platform/extensions/common/extensionsApiProposals.ts](https://github.com/microsoft/vscode/blob/main/src/vs/platform/extensions/common/extensionsApiProposals.ts).

```tsx
editorEncoding: {
	proposal: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.editorEncoding.d.ts',
},
```
needs to be inserted after `editSessionIdentityProvider`

2024-06-27 10:30 UTC, Tosox commented on src/vs/workbench/api/browser/mainThreadEditors.ts
> +	$trySetEncoding(id: string, encoding: string): Promise<void> {
I think the EncodingMode for `encodingSupport.setEncoding` shouldn't be hardcoded but rather be a function parameter.

I created an extension which sets the encoding depending on the file contents. After opening an existing file previously saved with "Windows-1251" the contents of the file completely broke. Changing the EncodingMode here to `EncodingMode.Decode` fixed the issue.

I believe it also makes sense after looking at these references:
https://github.com/microsoft/vscode/blob/53ed07606e51c2047564d8cefebc36a177fa3e6f/src/vs/workbench/browser/parts/editor/editorStatus.ts#L1521
https://github.com/microsoft/vscode/blob/53ed07606e51c2047564d8cefebc36a177fa3e6f/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L1116

2024-07-05 21:11 UTC, Tosox commented
Nice to see you still maintaining this pr. I hope someone will finally merge this soon.

2024-12-29 17:00 UTC, vivodi commented
Is this still relevant?

2024-12-29 18:26 UTC, leaumar commented
> Is this still relevant?

Yes, very, lots of people are eagerly awaiting the merge

2025-02-07 10:16 UTC, bpasero commented
@Tarrowren this change is heavily behind `main`, I tried to merge myself but miss the permissions to push back to your branch. I have https://github.com/microsoft/vscode/tree/ben/editor-encoding-api-fork with that work, how do you want to proceed, in here or in a new PR from https://github.com/microsoft/vscode/tree/ben/editor-encoding-api-fork ?

2025-02-07 15:12 UTC, bpasero requested changes
@Tarrowren On a high level, the better location for encoding concerns is actually `TextDocument`. Because that maps to the underlying text model where the encoding information is at and where it can be changed. A text editor is never the owner of the documents encoding. This is the first change I am asking to do.

As for the API itself, `encoding` should be a `readonly encoding: string` that lives on `TextDocument` and can be received without awaiting a `Promise`. Subsequently, I would suggest a `encode(encoding: string): Promise<void>` and `decode(encoding: string): Promise<void>` method on `TextDocument` for the remainder.

Does that sound reasonable? Please let me know if you are willing to continue working on this PR given this feedback.

2025-02-13 08:23 UTC, bpasero commented
Thus this continues in https://github.com/microsoft/vscode/pull/239961

2025-02-13 08:23 UTC, closed without merging