keybindingService: isolate file-wide mutable state into a singleton
microsoft/vscode pull request #178428
Opened 2023-03-27 14:47 UTC by ulugbekna

2023-03-27 16:19 UTC, connor4312 approved these changes, later dismissed

2023-03-30 13:18 UTC, aeschli requested changes

2023-03-30 15:29 UTC, ulugbekna commented on src/vs/workbench/services/keybinding/browser/keybindingService.ts
> +		KeybindingsJsonSchema.getInstance().updateSchema(this._contributions.flatMap(x => x.getSchemaAdditions()));
done in 95610a8

2023-03-30 16:08 UTC, aeschli approved these changes

2023-03-30 16:24 UTC, merged