separate logger for semantic tokens
microsoft/vscode pull request #181239
Opened 2023-05-01 11:23 UTC by aeschli

Fixes https://github.com/microsoft/vscode/issues/181174

2023-05-10 15:57 UTC, sandy081 requested changes

2023-05-10 15:57 UTC, sandy081 commented on src/vs/editor/common/services/semanticTokensProviderStyling.ts
> +			if (this._logger.getLevel() === LogLevel.Trace) {
Wondering why you have to check for the log level? Logger already does it for you.

2023-05-10 15:58 UTC, sandy081 commented
> Should we go ahead with this PR?

I would leave the decision to you to have separate logger or not. Supporting categories in log service might not come soon.

2023-10-13 21:48 UTC, Frenchy9669 approved these changes

2023-12-20 17:16 UTC, aeschli commented
Closing. See https://github.com/microsoft/vscode/issues/181174#issuecomment-1864849251

2023-12-20 17:16 UTC, closed without merging