Kartik/terminalupdates
microsoft/vscode pull request #182914
Opened 2023-05-18 20:32 UTC by karrtikr

Follow-up to https://github.com/microsoft/vscode/pull/182238

2023-05-19 13:57 UTC, Tyriar requested changes

2023-05-19 13:57 UTC, Tyriar commented on extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts
> +				const collection = extensionContext.environmentVariableCollection as (EnvironmentVariableCollection & { getScopedEnvironmentVariableCollection(scope: EnvironmentVariableScope): EnvironmentVariabl
Add `// TODO` to remove once API is stabilized

2023-05-19 13:57 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/environmentVariableInfo.ts
> +function getMessage(collection: IMergedEnvironmentVariableCollection, scope: EnvironmentVariableScope | undefined, extensionService: IExtensionService, extSet: Set<string>): string {
`getMergedDescription`?

2023-05-19 14:08 UTC, Tyriar commented on src/vs/workbench/api/common/extHostTerminalService.ts
>  		}
When working on options just now I wanted to make this change:

```
	private _setIfDiffers(variable: string, mutator: vscode.EnvironmentVariableMutator, scope: vscode.EnvironmentVariableScope | undefined): void {
```

Is it safe to remove `scope` off `mutator` like this?

2023-05-19 14:13 UTC, karrtikr commented on src/vs/workbench/api/common/extHostTerminalService.ts
>  		}
> Is it safe to remove scope off mutator like this?

No, scope is present in the mutator type to be used in implementation.

2023-05-23 17:15 UTC, karrtikr commented on src/vs/platform/terminal/common/environmentVariableCollection.ts
> +	strictFilter = false /** whether mutator has to exactly match the scope */
We've to use different parameters I think, I've clarified it better in the param comment.

2023-05-23 18:10 UTC, Tyriar approved these changes

2023-05-23 18:34 UTC, merged