Implement `GlyphMarginWidget`s
microsoft/vscode pull request #184375
Opened 2023-06-06 00:05 UTC by joyceerhl

Fixes https://github.com/microsoft/vscode/issues/114776
Part of https://github.com/microsoft/vscode/issues/179725

2023-06-13 13:05 UTC, alexdima requested changes
Looking pretty good and in the right direction! I pushed a change to do the lane count computation only once per frame. I also left a couple of comments, plus there are a couple of problems that I've spotted for which I didn't add comments, as I didn't digg deeper to see what are the root causes:

* enable `"typescript.referencesCodeLens.enabled": true`
* observe how the breakpoints margins are rendered one line above than before
* observe also that sometimes the breakpoints cannot be removed:


https://github.com/microsoft/vscode/assets/5047891/531a9ece-942c-4870-93b6-f8cc50c2616d

2023-06-13 13:05 UTC, alexdima commented on src/vs/editor/browser/viewParts/glyphMargin/glyphMargin.ts
> +		}
I think the preferences should be compared structurally because they're objects, not primitives.

2023-06-13 13:05 UTC, alexdima commented on src/vs/editor/browser/editorBrowser.ts
> +	className: string;
What is the purpose of `className` given that API users can pass in their own dom node where they can already define its `className` as they wish?

2023-06-14 00:37 UTC, joyceerhl commented
Looked into the off-by-one issue some, it looks like whitespace added by codelenses, as well as the peek view widgets, are not included in the calculation for `getVerticalOffsetForLineNumber` even when accounting for viewzones: https://github.com/microsoft/vscode/blob/fda41b80d37bbdae27d36bfe8c936cc369d3993a/src/vs/editor/browser/viewParts/glyphMargin/glyphMargin.ts#L452

I probably need a different way to calculate the `top` offset for each decoration, will do some digging

2023-06-15 22:41 UTC, joyceerhl commented
Fixed!

https://github.com/microsoft/vscode/assets/30305945/098c8004-542f-430e-b442-ad59feeb9ea2

2023-06-16 12:48 UTC, alexdima approved these changes

2023-06-16 13:18 UTC, jrieken approved these changes

2023-06-16 13:18 UTC, merged

2023-07-17 07:44 UTC, zvailanu98 reviewed
Coin)