Adopt editor resolver for Welcome/Walkthrough pages
microsoft/vscode pull request #184770
Opened 2023-06-09 22:45 UTC by bhavyaus

This helps with:
https://github.com/microsoft/vscode/issues/166831

2023-06-10 06:24 UTC, bpasero requested changes
This is very cool!

I would suggest to tackle https://github.com/microsoft/vscode/issues/184673 here as well because depending on where the input is contributed, we may need to move it to an earlier phase. Specifically the editor resolver needs to know about the registration before we attempt to open the welcome page from `layout.ts` I think.

2023-06-10 06:24 UTC, bpasero commented on src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts
> +				editorService.openEditor({
There now seems to be a `const gettingStartedInput =` a few lines up that is not needed unless you are in the `if` branch above?

2023-06-11 17:34 UTC, bhavyaus commented
> This is very cool!
> 
> I would suggest to tackle #184673 here as well because depending on where the input is contributed, we may need to move it to an earlier phase. Specifically the editor resolver needs to know about the registration before we attempt to open the welcome page from `layout.ts` I think.

I'll tackle this in separate PR. I might have to move some of startup logic to an earlier phase as well. I want to keep this change specific to adopting the editor resolver.

2023-06-11 18:00 UTC, bpasero approved these changes

2023-06-11 20:37 UTC, merged

2023-06-14 12:24 UTC, abhijit-chikane commented
I think any tab open over there after closing should be able to get it after pressing CTRL+SHIFT+T 
I was going over the release notes and I accidently closed it but after click CTRL+SHIFT+T it didn't open
same for the extension tabs If I click on any extension and close the tab after CTRL+SHIFT+T it should open it 

I think any close tab should be undoable irrespective of the type of tab
@bhavyaus @bpasero