Add snippets as a language
microsoft/vscode pull request #185017
Opened 2023-06-13 13:23 UTC by alexr00

2023-06-13 20:01 UTC, jeff-hykin commented
> I'm going to get some more feedback from the dev team to see if we want to include this a language since it will always show in the language picker.

Is there an altenative that keeps the syntax highlighting but "snippets" doesn't show up in the language picker?

2023-06-14 10:11 UTC, alexr00 commented
Feedback was positive, including that it shows in the language picker. I will merge at the beginning of the July iteration for maximum time in Insiders before release.

2023-06-14 10:13 UTC, alexr00 commented on extensions/json/syntaxes/snippets.tmLanguage.json
@jeff-hykin, just FYI, as part of the script that we'll update the grammar with I've made the scope `json.snippets` (changed from `json.comments`).

2023-06-14 11:34 UTC, jeff-hykin commented on extensions/json/syntaxes/snippets.tmLanguage.json
that might break some people's theme settings. It's not that big of deal, but you might want to switch to `json.comments.snippets` which should maintain backwards compatibility

2023-06-15 22:01 UTC, gjsjohnmurray commented
Will there also be a "New snippet" snippet? Something like this:
```json
	"New snippet" : {
		"scope": "snippets",
		"body": [
			"\"${1:name}\": {",
				"\t\"scope\": \"$2\",",
				"\t\"description\": \"$3\",",
				"\t\"body\": [",
					"\t\t\"$0\"",
				"\t]",
			"},"
		]
	},
```

2023-06-15 22:07 UTC, RedCMD commented
> Will there also be a "New snippet" snippet?

for intellisense?
that could easily be done

2023-06-16 14:42 UTC, alexr00 commented
@jrieken, FYI about [this ](https://github.com/microsoft/vscode/pull/185017#issuecomment-1594657028)possible "escape for snippet" command.

2023-06-16 15:17 UTC, jrieken commented
that's like https://github.com/microsoft/vscode/issues/26706?

2023-07-28 14:38 UTC, Tyriar requested changes
@alexr00 can we get a linked issue for this to ensure we verify/test?

2023-07-28 15:47 UTC, alexr00 commented
Added! https://github.com/microsoft/vscode/issues/189176

2023-07-28 16:21 UTC, Tyriar approved these changes

2023-07-28 16:21 UTC, merged