Fix #153590
microsoft/vscode pull request #185467
Opened 2023-06-18 05:56 UTC by weartist

2023-06-20 01:34 UTC, weartist commented
@lszomoru hi I changed the voice over display to generate semantic content from markdown, so that it would remove links and labels that were not easy to read, and the header files were just reordered, not modified (my eslint helped out)

2023-06-20 17:01 UTC, rzhao271 requested changes

2023-06-21 01:13 UTC, weartist commented on src/vs/workbench/contrib/preferences/browser/settingsTree.ts
> +			const descriptionWithoutSettingLinks = renderMarkdownAsPlaintext({ value: element.description });
Thanks~

2023-06-21 15:54 UTC, rzhao271 approved these changes

2023-06-21 16:20 UTC, meganrogge approved these changes

2023-06-21 18:00 UTC, merged