improve inline chat accessibility
microsoft/vscode pull request #185803
Opened 2023-06-21 18:44 UTC by meganrogge

fixes https://github.com/microsoft/vscode/issues/185690
fixes https://github.com/microsoft/vscode/issues/185705
fixes https://github.com/microsoft/vscode/issues/185706
fixes https://github.com/microsoft/vscode-copilot/issues/291

2023-06-21 22:19 UTC, meganrogge commented on src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts
>  			reply = await raceCancellationError(Promise.resolve(task), requestCts.token);
```suggestion
			reply = await raceCancellationError(Promise.resolve(task), requestCts.token);

```

2023-06-22 07:29 UTC, aiday-mar submitted a review, later dismissed

2023-06-22 10:25 UTC, jrieken requested changes

2023-06-22 10:25 UTC, jrieken commented on src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts
> +			return;
Unsure if that wanted but this doesn't reset `_hasReceivedRequest`

2023-06-22 10:25 UTC, jrieken commented on src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts
> +			const content = renderedMarkdown.element?.textContent;
`renderedMarkdown.element` should never be undefined or null. Did you experience something different or why the `?` here?

2023-06-22 10:25 UTC, jrieken commented on src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts
> +				status = localize('errorResponseMessage', "{0}", response.message);
`localize` doesn't do anything here because it's just the none-localized parameter (response.message)

2023-06-22 13:34 UTC, jrieken commented on src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts
> +		}, CHAT_RESPONSE_PENDING_AUDIO_CUE_LOOP_MS);
Sorry, what I meant is to have all of this in the ctor and only call `this._runOnceScheduler.schedule` here. And register the scheduler once as disposable

2023-06-22 14:29 UTC, jrieken approved these changes

2023-06-22 14:29 UTC, merged