Add tabSizingFixedMinWidth setting (#185766)
microsoft/vscode pull request #186058
Opened 2023-06-24 08:27 UTC by jacekkopecky

This PR simply adds a `tabSizingFixedMinWidth` setting to address the request in #185766. 

With the minimum being configurable, with diverse users presumably choosing both higher and lower values than the default, there is no longer a reason to have a setting minimum for the `MaxWidth`, so I set both to have minimum of 5px, which is the left padding in tabs and in my testing tabs never went any smaller.

2023-06-24 08:33 UTC, jacekkopecky commented
With a small minimum setting value, normal tabs can get smaller than pinned tabs sized `compact` or `shrink`; I guess that's OK. 8-)

2023-06-25 12:44 UTC, bpasero requested changes

2023-06-25 12:44 UTC, bpasero commented on src/vs/workbench/browser/workbench.contribution.ts
> +				'minimum': 5,
I suggest `38px` here, same as pinned compact tabs width.

2023-06-25 12:44 UTC, bpasero commented on src/vs/workbench/browser/workbench.contribution.ts
> +				'minimum': 5,
I suggest `38px` here, same as pinned compact tabs width.

2023-06-26 06:50 UTC, bpasero approved these changes, later dismissed

2023-06-26 10:54 UTC, jacekkopecky commented
@bpasero thank you for updating those minima

2023-06-26 13:21 UTC, alexr00 approved these changes

2023-06-26 14:58 UTC, bpasero approved these changes

2023-06-26 14:58 UTC, merged