[typescript-language-features] Add option for excluding library symbols in "Go to Symbol in Workspace"
microsoft/vscode pull request #192798
Opened 2023-09-11 16:47 UTC by gabritto

Fixes https://github.com/microsoft/TypeScript/issues/48194.
Partially fixes #46718 (still doesn't allow for custom exclusion based on `search.excludes`).
TS Server PR: https://github.com/microsoft/TypeScript/pull/55605.

2023-09-11 20:45 UTC, mjbvz requested changes
LGTM just one small change for description

2023-09-11 20:45 UTC, mjbvz commented on extensions/typescript-language-features/package.nls.json
> +	"typescript.workspaceSymbols.excludeLibrarySymbols": "Exclude symbols that come from library files in `Go To Symbol in Workspace` results.",
Can you add a note that this requires TS 5.3+

2023-09-12 18:20 UTC, mjbvz commented on extensions/typescript-language-features/src/typescriptServiceClient.ts
> +				// @ts-expect-error until TS 5.3
You can actually remove the `@ts-expect-error` check. We now build using the latest TS 5.3 types

2023-09-13 17:50 UTC, mjbvz approved these changes

2023-09-13 18:19 UTC, aeschli approved these changes

2023-09-13 18:19 UTC, merged