Fixes Aria Label Showing [Object object]
microsoft/vscode pull request #195929
Opened 2023-10-18 18:27 UTC by amaust

closes #195661
Switches aria-label titles to tooltip titles for certain instances where options.title is a markdown string.

2023-10-18 19:08 UTC, meganrogge commented
Thanks so much for looking into this @amaust. Have you made sure this works well for all of these areas?

![Screenshot 2023-10-18 at 12 07 43 PM](https://github.com/microsoft/vscode/assets/29464607/fb6ce7e3-a564-439f-8c17-3d66ef2d1082)

2023-10-18 19:08 UTC, meganrogge commented
@lramos15 this changes some code that you added

2023-10-18 21:48 UTC, amaust commented
@meganrogge I ran the unit tests but I did not think about double checking those. My apologies, I'll look into it ASAP.

2023-10-18 22:22 UTC, lramos15 requested changes
This actually isn't quite the same and breaks some of the cases which this was intended to fix.

For example if you modify a file and it's under source control the aria label will read out 

`~/path/test.md • Modified`

but the title will just be `test.md`. Hiding some of that information from screen reader users.  I will leave it up to @meganrogge to decide what should be done for terminal. My suggestion would be that maybe `typeof options.title === 'string' ? options.title : label;`

2023-10-18 22:28 UTC, amaust commented
Sorry about that @lramos15, I was thinking about trying what you suggested as soon as I began looking at the other cases. Lemme know how you wanna proceed.

2023-10-19 01:48 UTC, amaust commented
@lramos15 I did go ahead and made the fix you suggested. I also went and verified the case you specified and it worked as expected. Let me know if any other changes need to be made!

2023-10-19 14:25 UTC, lramos15 approved these changes

2023-10-19 14:31 UTC, alexr00 approved these changes

2023-10-19 17:21 UTC, merged