Do not trim whitespace when part of strings or regexes
microsoft/vscode pull request #198164
Opened 2023-11-14 01:18 UTC by 333fred

Fixes https://github.com/microsoft/vscode/issues/195010. If the token to be removed is part of a string or a regex, then we do not want to remove the character, as it is very likely semantically important.

Before I mark this as ready to review, I need some help with how to approach testing this. Presumably, tests need to go in `trimTrailingWhitespaceCommand.test.ts`, but I'm going to need a language in the unit test suite with standard token types. Is there an example of this that isn't creating an entire language provider just for the test? Every example of `testTextModel.createTextModel` that I can see that has a language makes an entire custom one just for the test; if this is the only approach, I could use someone to point out what things I'll need to mock to test this. I would also like to add some integration tests, particularly around whitespace after the end a string, to ensure that it works with real tokenization as well.

The other open question I have is whether this behavior should be on by default, or if we need to update the trim whitespace option to have a "trim except in strings and regexes" option, as this behavior may not be desired by some?

2023-11-14 01:18 UTC, 333fred commented
@hediet, since you're the assignee on #195010, would you be able to comment on my questions above?

2023-11-15 16:32 UTC, coreyward commented
Not sure how viable this is, but I actually prefer trailing whitespace in multiline strings to be trimmed most of the time (in JS), but in some cases it's not desirable (specifically for tests). Perhaps there is a way to alter this behavior just for test files?

2023-11-15 20:00 UTC, 333fred commented
@hediet or @alexdima, thoughts on my questions? Given the comment from @coreyward on just this draft PR, I'm definitely leaning towards "needs an option switch". Personally, I do not want whitespace trimming in a multiline string, ever, in any file, regardless of whether it's a test file or not. It could be a regex component, or part of a piece of markdown where trailing `  ` matters.

2023-11-17 09:38 UTC, hediet commented
I think this should be behind an opt-in flag.
Also, I think when this flag is enabled, trimming whitespace should wait on the tokenization to complete.

2023-11-17 23:30 UTC, 333fred commented
@hediet I think I've plumbed through a setting for this correctly, but I could still use some pointers on how to test this appropriately.

2023-11-27 17:10 UTC, 333fred commented
Talked with @hediet offline. With the end of year coming up there isn't a lot of bandwidth to look at a change like this at the moment, given the potential costs of tokenization for the file. I'll ping again in January.

2023-12-06 22:49 UTC, alexdima requested changes

2023-12-07 09:01 UTC, hediet commented on src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts
> +			}
Thinking of it, shouldn't this problem be solved by a proper (extension-powered) on-save formatter?

2023-12-07 22:06 UTC, coreyward commented on src/vs/workbench/contrib/files/browser/files.contribution.ts
> +		'files.trimTrailingWhitespaceInRegexAndStrings': {
Yeah, they're common in Ruby.

2023-12-08 11:30 UTC, alexdima commented on src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts
> +			}
> Thinking of it, shouldn't this problem be solved by a proper (extension-powered) on-save formatter?

Yes, but there are always a long tail of languages which don't come with language servers. So I find the feature request reasonable.

2023-12-08 21:35 UTC, 333fred commented on src/vs/workbench/contrib/files/browser/files.contribution.ts
> +		'files.trimTrailingWhitespaceInRegexAndStrings': {
C# regexes can also be written across multiple lines using raw strings, but I'm unsure whether this tokenizer would consider them regex or strings. Roslyn will, certainly, but it's driven with semantics and I don't know if that's surfaced here.

2023-12-08 21:40 UTC, 333fred commented on src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts
> +			}
> If the model has tokens, then we consult them, if it doesn't have tokens, we don't trim the trailing whitespace.

This approach seems fine to me, but do we need to clarify the setting description to convey this info?

2024-01-05 18:49 UTC, 333fred commented on src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts
> +			}
Updated. Still looking for advice on how to actually test all of this though.

2024-01-08 07:24 UTC, hediet commented
For testing, please see existing unit tests for tokenization. Basically you should create a fake language with a static tokenizer where you set tokens manually. Then look for tests that test TrimTrailingWhitespaceCommand (or other commands) and try to run the command on the text model with the fake language.

2024-03-15 22:29 UTC, alexdima approved these changes
Thank you!

2024-03-16 00:42 UTC, Tyriar approved these changes

2024-03-16 00:43 UTC, merged

2024-03-18 18:11 UTC, 333fred commented
@alexdima thanks for picking this up! Really appreciate it, I've been very busy with other things and was unlikely to get back to this for another few months.