Making `move to` code action appear less often
microsoft/vscode pull request #198864
Opened 2023-11-22 14:43 UTC by aiday-mar

In relation to https://github.com/microsoft/vscode/pull/198858

2023-11-22 16:22 UTC, mjbvz commented
Thanks for looking into this but I think this should happen on the TS side instead

Working around the issue on our side add extra code we have to maintain and makes fixing the root cause on TS less of a priority. The TS team can provide code pointers if you are interested in helping by submitting a PR against TypeScript

2023-11-23 08:13 UTC, aiday-mar commented
Agreed I think TypeScript should fix this issue in priority, we were thinking this could be a temporary fix until TypeScript fixes this issue? I'll look at this issue with the TypeScript team directly in the meantime. cc @aeschli

2023-11-28 22:06 UTC, mjbvz requested changes

2023-11-28 22:06 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/refactor.ts
> +				return MoveToFileCodeAction.isOnDeclarationName(navigationTree.body, rangeOrSelection);
The move refactors should likely still show if you explicitly request them, such as using the `refactor` context menu or a keybinding. You can check the code action trigger for that

2023-11-28 22:06 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/refactor.ts
> +			if (action.kind?.value === Move_NewFile.kind.value) {
Let's also scope these new checks to TS 5.3 and add a comment about removing them in the future

TS 5.4 is still in pre-release and that's where the fix on the TS side will go

2023-11-29 00:48 UTC, mjbvz approved these changes

2023-11-29 00:56 UTC, DonJayamanne approved these changes

2023-11-29 01:00 UTC, merged