Ensure that cursor state change is always emitted upon restoring state
microsoft/vscode pull request #203451
Opened 2024-01-25 14:50 UTC by aramikuto

Fixes #203345

It seems that the distinction between cases where the scrollbar background appears and where it does not lies in whether [onCursorStateChanged](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler.ts#L298) is called or not. When a file is opened, [restoreCursorState](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/common/viewModel/viewModelImpl.ts#L1033) fires events that initialize the cursor state, and [_emitStateChangedIfNecessary](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/common/cursor/cursor.ts#L395) determines whether the `CursorStateChangedEvent` should be fired by comparing the previous and current cursor states. However, it appears that the default value for the cursor position in a newly opened view is (1,1), which results in the `CursorStateChangedEvent` not being fired if the cursor position after restoration is also (1,1) – the cursor positioned before the first character on the first line. Without this event, certain parts of [DecorationsOverviewRuler](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler.ts) do not initialize properly, leading to the problem I linked above.

To address this, I've ensured that cursor events are emitted if they were caused by the `restoreState`.

2024-01-26 16:45 UTC, hediet commented
Thanks for your analysis and bug report!

I think the bug fix is at the wrong location though. The event is correct, it should only fire when it changes. When the default value is (1,1) and the workbench restores the value to (1,1), no event should be fired.

However, the `DecorationsOverviewRuler` should not assume that this even is fired before it gets rendered!

2024-01-26 16:45 UTC, hediet requested changes
See comment.

2024-01-28 09:22 UTC, aramikuto commented
@hediet Thank you for reviewing my changes and providing feedback! I have adjusted my implementation according to the information provided.

This time, I explicitly added `Position(1, 1)` as the initial value for the cursor position in the `DecorationsOverviewRuler` constructor. This ensures that the initial value for the cursor position in both the newly opened view and the decorations overview are the same, allowing for proper rendering even when `onCursorStateChanged` is never called (such as when the editor's cursor is at its initial position (1,1)).

In cases where the cursor is not at the default position after state restoration, `onCursorStateChanged` is called, and everything should work as before.

2024-01-29 09:26 UTC, hediet commented
Much nicer change! Thank you!

2024-01-29 09:27 UTC, hediet approved these changes

2024-01-29 09:31 UTC, sandy081 approved these changes

2024-01-29 09:31 UTC, merged