Fix: Fixed glibc version detection bug in check-requirements-linux.sh (issue #204186)
microsoft/vscode pull request #204635
Opened 2024-02-07 16:32 UTC by NorthSecond

- Existing detection scripts simply use the `awk` command to record the version number in the `libstdc++.so` filename, 
- but in some specific versions of glibc++, the detailed version number is not indicated in the filename. 
  - Like the issue  #204186 , the OS version (Ubuntu 22.04) supports `GLIBCXX_3.4.25` but fails version checking because the filename is simply `libstdc++.so.6`, 
  - and we have reproduced this issue when connecting to the Ubuntu 22.04 server using ssh. 
- Instead of simply using the `awk` command to filter file names, we use a script to simulate the `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` operation, which reads the highest-supported version number of GLIBCXX, and determines whether the existing environment supports the minimum VSCode requirements. instead of simply filtering filenames with the `awk` command.

2024-02-07 22:02 UTC, deepak1556 requested changes
Thanks for the PR, some follow-ups

1) Can you provide the output of `bash -x check-requirements-linux.sh` without the changes from this PR.
2) `strings` will not available by default on many cases so we would need a fallback

2024-02-08 06:00 UTC, NorthSecond commented
> Thanks for the PR, some follow-ups
> 
> 1. Can you provide the output of `bash -x check-requirements-linux.sh` without the changes from this PR.
> 2. `strings` will not available by default on many cases so we would need a fallback

1. The result of `previous bash -x check-requirements-linux.sh` is `Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib/x86_64-linux-gnu/libstdc++.so.6`. 
2. Since some Linux distributions do not come with GNU binutils pre-installed,  the `strings` command does not fit on all platforms,  so we use `grep` and `sed` instead of `strings`. However, this change may cause performance degradation.

2024-02-08 08:10 UTC, deepak1556 commented
Sorry the change still uses `strings`, can you please provide a minimal devcontainer configuration that would demonstrate the error you are seeing.

2024-02-08 08:36 UTC, NorthSecond commented
> Sorry the change still uses `strings`, can you please provide a minimal devcontainer configuration that would demonstrate the error you are seeing.

Apologies for the fact that due to the changes I copied from vim, I didn't succeed in pasting them into the online editor when editing, now the current version no longer requires `strings`.

I tested this using a real Linux SSH connection to the server - in fact, it was a workstation with an Ubuntu 22.04 system. I was not involved in the installation and maintenance of the environment, so you may want to contact the author of issue #204186  if you need a reproducible container environment.

2024-02-08 08:53 UTC, deepak1556 commented
Issue https://github.com/microsoft/vscode/issues/204186 is different from the issue you are describing, there the script resolved to proper files

```
Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.24
Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.26.so
```

But based on the ldd output in https://github.com/microsoft/vscode/issues/204186#issuecomment-1924590175 it is very likely the author has multiple toolchain installations, so we would need to understand why that is the case and resolve that.

If this PR is trying to address https://github.com/microsoft/vscode/issues/204186 then let's wait for https://github.com/microsoft/vscode/issues/204186#issuecomment-1933016029. Also the script has got many changes since the issue was reported so I would also like to try the latest insiders on the setup.

2024-02-08 09:39 UTC, NorthSecond commented
> Issue #204186 is different from the issue you are describing, there the script resolved to proper files
> 
> ```
> Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.24
> Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.26.so
> ```
> 
> But based on the ldd output in [#204186 (comment)](https://github.com/microsoft/vscode/issues/204186#issuecomment-1924590175) it is very likely the author has multiple toolchain installations, so we would need to understand why that is the case and resolve that.
> 
> If this PR is trying to address #204186 then let's wait for [#204186 (comment)](https://github.com/microsoft/vscode/issues/204186#issuecomment-1933016029). Also the script has got many changes since the issue was reported so I would also like to try the latest insiders on the setup.

Okay, so it looks like the issue is different from what I'm experiencing.

Going back to my  environment, when I run `ls -l | grep libstdc++.so.6` in the `/usr/lib/x86 64-linux-gnu` directory, I get a somehow "unusual" output:

```plain
-rwxr-xr-x  2 root root  12212840 Jan  12 01:15 libstdc++.so.6
-rwxr-xr-x  2 root root  12212840 Jan  12 01:15 libstdc++.so.6.0.30
```

Run `cmp . /libstdc++.so.6.0.30 . /libstdc++.so.6` and there is no output, indicating that the contents of the two files are identical.

So the reason of the problem is that under the current system, instead of soft linking `libstdc++.so.6` to `libstdc++.so.6.0.30` with `ln` as expected, the solution in the current environment is to copy it directly, which directly results in the current `libstdc++.so.6` failing to pass the environment check.

Skimmed [GNU C++ Library Documentation](https://gcc.gnu.org/onlinedocs/libstdc++/). I didn't find any indication that `libstdc++.so.6` is necessarily a linked file, just that there is a `libstdc++.so.6` in `LD_LIBRARY_PATH`.

Therefore, I prefer to use the internal contents of `libstdc++.so.6` to determine if `GLIBCXX_3.4.25` is actually supported, rather than renaming it with the `cp` command to easily get older versions of the GLIBCXX to pass inspection.

2024-02-08 09:50 UTC, NorthSecond commented
Then, another problem is that the script looks for the `libstdc++.so.6` file directly in `/usr/lib` and `/usr/lib64` , but for some environments with multiple toolchain installations, we may manually use tools like `patchelf` to specify other versions of `libstdc++.so.6` for VSCode. other versions of `libstdc++.so.6`, which may result in the detection script not executing as expected.

2024-02-08 09:55 UTC, deepak1556 commented
What does `ldconfig -p` output in your setup ?

2024-02-08 09:58 UTC, NorthSecond commented
> What does `ldconfig -p` output in your setup ?

The result of ` ldconfig -p | grep libstdc++` is

```plain
libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
```

2024-02-08 10:20 UTC, NorthSecond commented
> There are conflicts in this PR, can you please rebase and resolve them.

Solved it.

2024-02-08 10:52 UTC, deepak1556 approved these changes
LGTM, I add a small change to skip the new check on alpine since it will not work there. Please check if the script continues to work for your setup.

2024-02-08 10:59 UTC, bpasero approved these changes

2024-02-08 11:01 UTC, NorthSecond commented
> LGTM, I add a small change to skip the new check on alpine since it will not work there. Please check if the script continues to work for your setup.

Yes It work's well.

2024-02-08 11:01 UTC, NorthSecond commented
> @NorthSecond please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-02-08 11:03 UTC, NorthSecond commented
> @NorthSecond please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-02-08 11:15 UTC, NorthSecond commented
Thanks for the review and the conversation, I've updated the current PR to based on the latest `main` branch.

Look forward to the next collaboration!

2024-02-08 11:43 UTC, merged