Try use shell integration in debug terminals
microsoft/vscode pull request #205034
Opened 2024-02-12 19:51 UTC by Tyriar

Fixes #204694

Shell integration when debugging xterm.js' unit tests with `console: integratedTerminal` set.

<img width="754" alt="Screenshot 2024-02-12 at 11 48 46" src="https://github.com/microsoft/vscode/assets/2193314/062cb280-04f5-48ef-ab4d-44746b588673">

2024-02-12 20:00 UTC, connor4312 approved these changes

2024-02-13 04:15 UTC, karrtikr reviewed
Thanks. Waiting on debug team: https://github.com/microsoft/vscode/issues/204694#issuecomment-1940395773 before approving.

2024-02-20 15:52 UTC, karrtikr requested changes
Based on https://github.com/microsoft/vscode/issues/204694#issuecomment-1944365481 it looks like this will also require changes to `RunInterminalRequestArguments`.

2024-02-20 15:58 UTC, Tyriar commented
What was the issue with always enabling this?

2024-02-20 17:21 UTC, karrtikr commented
If we can always enable shell integration by default (thereby enabling it for debug terminals) that'd be great.

2024-02-20 18:09 UTC, Tyriar commented
Let's merge this early next iteration and see if there's any negative feedback for insiders

2024-02-20 18:26 UTC, Tyriar commented on src/vs/platform/terminal/common/terminal.ts
> +	forceShellIntegration?: boolean;
Not always, but it will attempt to just like any other terminal. Previously "feature terminals" would all be excluded.

2024-02-21 17:53 UTC, Tyriar commented on src/vs/platform/terminal/common/terminal.ts
> +	forceShellIntegration?: boolean;
@karrtikr it's internal only (see no vscode.d.ts change) and only used right now for debug terminals

2024-02-21 18:04 UTC, karrtikr commented on src/vs/platform/terminal/common/terminal.ts
> +	forceShellIntegration?: boolean;
I see ok

2024-02-21 18:05 UTC, karrtikr approved these changes

2024-02-23 19:42 UTC, merged