feat. add a menu item 'expand-select' to expand subtree in search view
microsoft/vscode pull request #206033
Opened 2024-02-23 03:55 UTC by pagict

Implementation of #206032 

![image](https://github.com/microsoft/vscode/assets/1499282/46f09c20-3062-4159-9b53-6d15ea4b1123)

2024-02-23 04:06 UTC, RedCMD commented
Middle click (scroll click/button 3) is often used for toggling between expanding and collapsing nested items
(just like folding ranges in the editor)

2024-02-24 01:03 UTC, pagict commented
@microsoft-github-policy-service agree

2024-02-29 17:46 UTC, andreamah requested changes
Just a few small changes 👍

2024-02-29 17:46 UTC, andreamah commented on src/vs/workbench/contrib/search/browser/searchActionsFind.ts
> +		await expandSelectSubtree(accessor);
no need to await if the function is not async

2024-02-29 17:46 UTC, andreamah commented on src/vs/workbench/contrib/search/browser/searchActionsFind.ts
> +		viewer.expand(selected);
This only expands one level. The call will need to be such that recursive is true.

2024-02-29 17:47 UTC, andreamah commented
> Middle click (scroll click/button 3) is often used for toggling between expanding and collapsing nested items (just like folding ranges in the editor)

I think the search view already supports this, where middle click expands one level. Is this what you meant, or is there still missing functionality?

2024-03-01 09:01 UTC, pagict commented
> > Middle click (scroll click/button 3) is often used for toggling between expanding and collapsing nested items (just like folding ranges in the editor)
> 
> I think the search view already supports this, where middle click expands one level. Is this what you meant, or is there still missing functionality?

I meant for recursive expansion. I will update my code to make work, thx for reviewing.

2024-03-01 18:49 UTC, RedCMD commented
> I think the search view already supports this, where middle click expands one level. Is this what you meant, or is there still missing functionality?

yeah I meant for recursively nested items
The same as Folding ranges in the editor

2024-03-01 18:51 UTC, andreamah commented
> > I think the search view already supports this, where middle click expands one level. Is this what you meant, or is there still missing functionality?
> 
> yeah I meant for recursively nested items The same as Folding ranges in the editor

As in the middle click should recursively open nested items? Does this only happen in the editor with nested ranges, or does it happen in other tree views?

2024-03-01 18:57 UTC, RedCMD commented
yes, I would like middle click to recursively open nested items.
I think it only works for Folding ranges atm
I don't think any other tree view supports it

I'm pretty sure there was something else that did support it
but I can't remember if it was even in VSCode or not

2024-03-02 06:36 UTC, pagict commented
I tried and also checked the code, "middle mouse for recursively expansion" only works for foldings in the editor. 

https://github.com/microsoft/vscode/blob/1f94e5cd54ce0a7bc503a3f95a3742ddc5980151/src/vs/editor/contrib/folding/browser/folding.ts#L492-L499

2024-03-28 19:06 UTC, andreamah commented
Do we use the language "Expand Selected" anywhere else? Otherwise, I would prefer just "Expand" since it's implied that it's acting on selected elements.

2024-04-01 05:30 UTC, pagict commented
> Do we use the language "Expand Selected" anywhere else? Otherwise, I would prefer just "Expand" since it's implied that it's acting on selected elements.

no, the term "Expand Selected" does not in anywhere else. should I modify it as "Expand the Tree" or something similar, since this is quite a different behavior to what "Expand" implies.

2024-04-01 15:17 UTC, andreamah commented
![image](https://github.com/microsoft/vscode/assets/31675041/b7443d63-efc1-4962-91ed-4799e331b037)

The button that expands/collapses all (in the top toolbar) uses the term "Expand all" to expand all of the tree nodes, so I would expect that right-clicking and "expanding" a node would recursively open the node.

2024-04-02 05:09 UTC, pagict commented
> ![image](https://private-user-images.githubusercontent.com/31675041/318476758-b7443d63-efc1-4962-91ed-4799e331b037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzQ3NTQsIm5iZiI6MTcxMjAzNDQ1NCwicGF0aCI6Ii8zMTY3NTA0MS8zMTg0NzY3NTgtYjc0NDNkNjMtZWZjMS00OTYyLTkxZWQtNDc5OWUzMzFiMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA1MDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkODVjOTcxOTQ1NTQxMGZhZDY2YmFlYTQxYTNiMjBkMmZmZTBkYmIzNzMwMjI0OTE0ZTRhM2ZiMDg2ZGI1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PADLLsDa76A2IHJTIlPMPDthSlxc0pPoZeHyaonkfy8)
> 
> The button that expands/collapses all (in the top toolbar) uses the term "Expand all" to expand all of the tree nodes, so I would expect that right-clicking and "expanding" a node would recursively open the node.

update as "Expand All", please kindly review

2024-04-03 07:15 UTC, pagict commented
I think they both are good, and how about "Expand from This"? or maybe should be more succinct.

I don't have any preferences on this

2024-04-03 20:25 UTC, andreamah commented
I think "Expand Recursively" would be the best from my perspective, since it seems less wordy in my opinion.

2024-04-04 19:58 UTC, andreamah approved these changes
Thanks!

2024-04-04 20:56 UTC, amunger approved these changes

2024-04-04 20:57 UTC, merged