Cleanup editor group context keys
microsoft/vscode pull request #212955
Opened 2024-05-17 08:15 UTC by benibenj

This pull request includes changes to clean up the editor group context keys.

2024-05-17 08:16 UTC, benibenj commented on src/vs/workbench/browser/parts/editor/editorGroupView.ts
> +		const editorPart = this.groupsView as EditorPart;
I am not sure how we want to expose the `bind` method. Ideally we would not make it visible on the service, right?

2024-05-17 08:30 UTC, benibenj commented
Also, I need to make sure it's correctly handled when the active group changes which is not the case currently. I wonder if we can solve this from the EditorPart. It could listen on active group change and then set the global contextkeys to the scoped ones. Not sure its possible in a nice way...

2024-05-17 11:49 UTC, kalebers approved these changes

2024-05-17 14:37 UTC, bpasero requested changes

2024-05-17 14:37 UTC, bpasero commented on src/vs/workbench/browser/parts/editor/editorPart.ts
> +	private _globalContextKeys = new Map<RawContextKey<ContextKeyValue>, IContextKey<ContextKeyValue>>();
```suggestion
	private readonly globalContextKeys = new Map<RawContextKey<ContextKeyValue>, IContextKey<ContextKeyValue>>();
```

2024-05-17 14:37 UTC, bpasero commented on src/vs/workbench/browser/parts/editor/editorPart.ts
> +			this._globalContextKeys.set(contextKey, contextKey.bindTo(this.contextKeyService));
To be safe, you need to check for the `key` of the `RawContextkey`, otherwise you might end up with the same context key.

2024-05-17 14:37 UTC, bpasero commented on src/vs/workbench/browser/parts/editor/editorPart.ts
> +					$this._globalContextKeys.get(contextKey)?.set(value);
Instead of always looking this up, I would lookup or create the global key in the `bind` method early and then provide access to it.

2024-05-17 14:39 UTC, bpasero commented
> Also, I need to make sure it's correctly handled when the active group changes which is not the case currently. I wonder if we can solve this from the EditorPart. It could listen on active group change and then set the global contextkeys to the scoped ones. Not sure its possible in a nice way... Otherwise, the editor group view just needs to rerun `observeActiveEditor` when it becomes active.

Yeah you need to keep track of active group changes and then go over all context keys that have been bound and ask for the scoped context key value to update the global one.

Btw `EditorPart` is per window and each window can have an active editor group. But only `EditorParts` has the true single active editor group, so maybe this actually needs to be managed by `EditorParts` so that we are not updating the global context key from multiple windows.

2024-05-19 07:30 UTC, bpasero requested changes
I think `bind` works fine now for context keys that are bound within the group, but what if someone calls `bind` and passes in the active group, the key would only be bound for that active group and not the other groups.

So maybe `bind` needs to work differently: you are not passing in the editor group, but just the key. And then `EditorParts` makes sure to set the key properly when editor groups change, add or remove?

2024-05-19 12:12 UTC, benibenj commented
That is why `bind` is not on the service, so others don't use it, but it's hard to fully restrict it to the outside. The next step (other PR ideally) will be to have a method on the service which allows others to register a context key handler. This will then be managed correctly across all groups.

2024-05-19 16:57 UTC, bpasero approved these changes

2024-05-20 11:03 UTC, deepak1556 approved these changes

2024-05-20 11:03 UTC, merged