When completing color keys in settings, fill in current value
microsoft/vscode pull request #213451
Opened 2024-05-25 09:11 UTC by SimonSiefke

fixes #25633

![color-theme](https://github.com/microsoft/vscode/assets/23744935/09330b46-8669-48f9-b059-29e37944dc61)

2024-05-27 12:22 UTC, aeschli requested changes

2024-05-27 12:22 UTC, aeschli commented on src/vs/platform/theme/common/colorUtils.ts
> +import type { ColorThemeData } from 'vs/workbench/services/themes/common/colorThemeData';
platform can not reference `workbench/services`, use `IColorTheme` instead

2024-05-27 12:22 UTC, aeschli commented on src/vs/platform/theme/common/colorUtils.ts
> +export const setTheme = (theme: ColorThemeData) => {
that's not so nice to have this as a global function. Better add it as a function to the `IColorRegistry`. I would call it` notifyThemeUpdate(...)`

2024-05-27 12:22 UTC, aeschli commented on src/vs/workbench/services/themes/browser/workbenchThemeService.ts
> +		setTheme(newTheme)
theme colors not only change on `applyTheme`, but also when the color customizations change.
Best is to subscribe to `onColorThemeChange` to get all notifications

2024-05-28 07:59 UTC, aeschli requested changes

2024-05-28 07:59 UTC, aeschli commented on src/vs/workbench/services/themes/browser/workbenchThemeService.ts
> +		this.onColorThemeChange.event
this line can be removed

2024-05-28 07:59 UTC, aeschli commented on src/vs/workbench/services/themes/browser/workbenchThemeService.ts
> +		this._register(this.onDidColorThemeChange(this.handleColorThemeChange, this));
directly call `getColorRegistry().notifyThemeUpdate(theme)`

2024-06-05 13:08 UTC, bpasero approved these changes

2024-06-05 14:15 UTC, Tyriar approved these changes

2024-06-05 14:59 UTC, aeschli approved these changes

2024-06-05 14:59 UTC, merged

2024-06-05 14:59 UTC, aeschli commented
Thanks @SimonSiefke !