mute terminal hint color
microsoft/vscode pull request #214173
Opened 2024-06-03 19:22 UTC by meganrogge

fix #213647

2024-06-03 19:54 UTC, Tyriar requested changes

2024-06-03 20:41 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts
> +	light: Color.fromHex('#0007'),
I see we don't use this `Color.fromHex` for other colors 🤔 . I'm wondering why 👀

2024-06-03 20:42 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts
> +	light: Color.fromHex('#0007'),
looks like that's not necessary, removing

2024-06-03 20:43 UTC, meganrogge commented on src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts
> +	hcDark: '#ffffff56',
seeing what we should do for HC themes atm

2024-06-03 21:34 UTC, Tyriar submitted a review, later dismissed

2024-06-03 21:34 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts
> +export const TERMINAL_INITIAL_HINT_FOREGROUND = registerColor('terminal.initialHint.foreground', {
`terminal.initialHintForeground` would be more consistent with others (I know it's messy across the product but we want it to be as consistent as possible within the component.

2024-06-04 20:55 UTC, Tyriar approved these changes

2024-06-04 20:55 UTC, merged