[typescript-language-features] Add diagnostics performance telemetry
microsoft/vscode pull request #220127
Opened 2024-07-05 23:29 UTC by gabritto

2024-07-08 15:54 UTC, mjbvz requested changes

2024-07-08 15:54 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/diagnostics.ts
> +		performanceData.forEach(data => {
[nit] use `for of`

2024-07-08 15:54 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/diagnostics.ts
> +					syntaxDiagDuration: data.syntaxDiag,
I think all of these numbers should be measures instead of normal telemetry properties. Just add `"isMeasurement": true` to each property definition

2024-07-08 15:54 UTC, mjbvz commented on extensions/typescript-language-features/src/languageFeatures/diagnostics.ts
> +		if (performanceData && this._diagnosticsTelemetryManager) {
Can this just be `this._diagnosticsTelemetryManager?.(...)`

2024-07-12 16:58 UTC, mjbvz approved these changes

2024-07-12 17:02 UTC, Tyriar approved these changes

2024-07-12 17:03 UTC, merged