fix image rendering, use paste provider
microsoft/vscode pull request #229779
Opened 2024-09-25 23:25 UTC by justschen

fixes https://github.com/microsoft/vscode/issues/229625 and https://github.com/microsoft/vscode-copilot/issues/8637

demo:

paste:
https://github.com/user-attachments/assets/691c4134-f52c-4758-848d-0c9cf05f2b23

dnd:
https://github.com/user-attachments/assets/45382850-dba8-4b6c-a332-7e9ddce54a11

2024-09-26 09:11 UTC, benibenj reviewed
FYI, in this case you can use the `ChatContextAttachments` contribution which also takes care of duplicates. We are not able to use it for chat dnd sadly.

2024-09-26 09:11 UTC, benibenj commented on src/vs/workbench/contrib/chat/browser/chatPasteProviders.ts
>  		return;
```suggestion
		const widget = this.chatWidgetService.getWidgetByInputUri(_model.uri);
		if (!widget) {
			return;
		}

		const attachContribution = widget.getContrib<ChatContextAttachments>(ChatContextAttachments.ID);
		attachContribution?.setContext(false, imageContext);
```

2024-09-30 18:44 UTC, mjbvz requested changes

2024-09-30 18:44 UTC, mjbvz commented on src/vs/workbench/contrib/chat/browser/chatPasteProviders.ts
> +		const currClipboard = await this.clipboardService.readImage();
Can you use the `dataTransfer` here instead? It should have the image data in it

2024-09-30 18:44 UTC, mjbvz commented on src/vs/workbench/contrib/chat/browser/chatPasteProviders.ts
> +		attachContribution?.setContext(false, imageContext);
`provideDocumentPasteEdits` should not have any side effects. Maybe ok as a temporary workaround for now but let's look into allowing workspace edits to add attachments to chat. That way undo/redo will work nicely too

2024-10-07 21:11 UTC, mjbvz approved these changes, later dismissed
Approving for continued iteration but please make sure to follow up about using workspace edits

2024-10-07 22:09 UTC, rzhao271 approved these changes

2024-10-07 22:14 UTC, merged