Added Support Of /dir/file_path.txt, <line> link format #217927
microsoft/vscode pull request #229964
Opened 2024-09-27 13:55 UTC by vp007-dev

This Pull Request adds support for file paths in the format /dir/file_path.txt, <line> (with a space after the comma) in VS Code. Previously, this format was not recognized by the editor, causing issues when navigating to specific lines in error messages or logs that follow this format.

**### Changes introduced:**
Added a new regex clause to handle the /dir/file_path.txt, <line> format with a space between the comma and line number.
Updated the lineAndColumnRegexClauses to ensure correct parsing of file paths with this format.
Added relevant tests to ensure compatibility and coverage.

**### Example:**
Error messages in the format /home/rahultadakamadla/file.svh, 204 are now clickable, allowing users to directly jump to the specified line in the file.

**### Testing:**
Tested locally to verify that the new format is correctly parsed and linked to the appropriate file and line in the editor.
Added new unit tests to ensure continued support for other file formats while including this new format.

**### Checklist:
 Tested the new functionality locally
 Added appropriate unit tests
 Verified compatibility with existing formats
 Followed VS Code's contribution guidelines**

**### Related Issues:**
Closes #217927

2024-09-27 17:24 UTC, Tyriar requested changes

2024-09-27 17:24 UTC, Tyriar commented on src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts
> +		`['"]?${p()}, ${r()}` + eolSuffix,
I think we could add this to the top entry in the array, by just adding `,` as an option in this group:

```
Before: (?::|#| |['"],)
 After: (?::|#|,| |['"],)
```

We will also need some tests to cover this case here:

https://github.com/microsoft/vscode/blob/13ac4f2de288322b1fd31415e3a0b8c9bc43ea07/src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkParsing.test.ts#L42-L62

2024-09-27 17:25 UTC, Tyriar requested changes

2024-09-27 17:25 UTC, Tyriar commented on src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts
> +		`['"]?${p()}, ${r()}` + eolSuffix,
Oh there's also a compile error here:

```
[tsec-compile-check      ] src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts(121,11): error TS2304: Cannot find name 'p'.
```

Note that r() is row, c() is column

2024-09-27 17:26 UTC, Tyriar commented
Did you use AI to generate the PR description? You say you tested it locally and added a unit test but neither can be true as it would give a runtime error?

2024-09-28 03:01 UTC, vp007-dev commented
> Did you use AI to generate the PR description? You say you tested it locally and added a unit test but neither can be true as it would give a runtime error?

Yes i did use AI to generate description because i am bad at grammar so i just explained my work and it gave me a description so i edited the description a little bit so yeah AI can ruin work

I am having errors in my local machine for no reasons i spent hours to build vs code but it gives error in my system and i think its because of some hardware problem and not because of the changes i made. i followed the steps for building vs code oss but i failed and i tried to fix it and it just give rise to new error 


But i was not surprised because i always get this type of error when i build electron apps



But i will try again on linux machine i guess


And i will make changes to the PR that you requested.

2024-09-28 03:08 UTC, vp007-dev commented
> Did you use AI to generate the PR description? You say you tested it locally and added a unit test but neither can be true as it would give a runtime error?

Yes i did use AI to generate description because i am bad at grammar so i just explained my work and it gave me a description so i edited the description a little bit so yeah AI can ruin work

I am having errors in my local machine for no reasons i spent hours to build vs code but it gives error in my system and i think its because of some hardware problem and not because of the changes i made. i followed the steps for building vs code oss but i failed and i tried to fix it and it just give rise to new error 


But i was not surprised because i always get this type of error when i build electron apps



But i will try again on linux machine i guess


And i will make changes to the PR that you requested.



Also can i ask for help here if i face any problems? 😭

2024-09-28 13:27 UTC, Tyriar commented
@vp007-dev no problem, just it had incorrect information. You don't need perfect grammar, just `Closes #217927` would have been fine in this case.

Instructions to set up are [here](https://github.com/microsoft/vscode/wiki/How-to-Contribute). I can try help if you give an error but I'm often busy so don't respond too often.

2024-09-30 16:03 UTC, vp007-dev commented
**### Error!:**
![adawdwadawdawd](https://github.com/user-attachments/assets/461cd25b-3362-4410-86fc-b20a39162595)

and yes i have installed and tried everything here:

![awdawdadwa](https://github.com/user-attachments/assets/14d557a3-1458-40b3-9bc9-5acc8a15e0c8)
 and i also tried that msvs_version thing i edited the config file still no good

2024-10-16 21:15 UTC, Tyriar commented
I've never seen that one. I guess the first thing I'd try is look at the problem file it's talking about and seeing if it does indeed lack a `main` property. Make sure you're on a relatively new version of VS Code as well (the resolve conflicts button in on this page), if this branch is too old it might have some weird stuff related to our AMD -> ESM migration.

2026-08-08 06:22 UTC, anthonykim1 commented
Thanks for the PR. This was implemented in #231775, which closed #217927. Closing this as superseded. Please let us know if you think this is incorrect.

2026-08-08 06:22 UTC, closed without merging