CountBadge :lipstick:
microsoft/vscode pull request #233708
Opened 2024-11-12 17:20 UTC by benibenj

2024-11-12 17:24 UTC, karthiknadig approved these changes, later dismissed

2024-11-12 17:25 UTC, Tyriar requested changes

2024-11-12 17:25 UTC, Tyriar commented on src/vs/base/browser/ui/countBadge/countBadge.ts
> +			this.hover = undefined;
`MutableDisposable` would make this a little nicer and let you register in the prob instead of overriding dispose

2024-11-13 12:55 UTC, Tyriar approved these changes

2024-11-13 12:55 UTC, merged