Implementing Terminal: Run Recent Commad when there are no open terminal
microsoft/vscode pull request #234124
Opened 2024-11-18 17:27 UTC by SalerSimo

Related to issue #233604 
The command 'Terminal: Run Recent Command' will now create a new terminal if no terminals are currently open.

Simply creating a new terminal is not sufficient for the recent command window to display correctly.
When a new terminal is created, it looks like it takes some more time to fully update its related variables, so I inserted a loop of quick sleep functions (up to 5 seconds in total) while continuosly trying to display the recent command window.

2024-11-22 16:59 UTC, Tyriar requested changes
I don't think we should be doing anything outside of the command implementation. Everything you need to do should be able to be done there. You might need to change it to `registerTerminalAction` instead in order to get it to run when a terminal doesn't actually exist yet.

2024-11-22 16:59 UTC, Tyriar commented on src/vs/workbench/contrib/terminal/browser/terminalActions.ts
> +			activeInstance = c.service.activeInstance;
This is a generic function so you shouldn't be changing this, instead you should change the `run` callback passed in when it's called.

2024-11-22 18:08 UTC, SalerSimo commented
@Tyriar I changed it in order to avoid changing the generic function.

2025-06-06 16:17 UTC, Tyriar commented
Closing in favor of https://github.com/microsoft/vscode/pull/250799 which is closer to what I was thinking.

2025-06-06 16:17 UTC, closed without merging