Issue: #214481 Add Option to Ignore Code Blocks in Text-to-Speech
microsoft/vscode pull request #235697
Opened 2024-12-10 04:39 UTC by jaymroy

Implementation of a requested feature
I introduced a new setting under the existing accessibility.voice.* namespace, modified the nextChatResponseChunk generator to track code block boundaries and stopped synthesizing text within the code blocks when the setting is enabled.

2024-12-10 11:28 UTC, HarshPatel2010 commented
Preparing review...

2024-12-10 11:47 UTC, HarshPatel2010 commented
Preparing review...

2024-12-10 11:48 UTC, HarshPatel2010 commented
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 3 🔵🔵🔵⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<a href='https://github.com/microsoft/vscode/pull/235697/files#diff-3fd6fda06fcf4ddc95190c5bd20dfff5058b91c68c8ab09ed5a97c2d90b60db8R771-R795'><strong>Code Complexity</strong></a><br>The implementation of the feature to ignore code blocks in text-to-speech adds significant complexity to the `nextChatResponseChunk` method. Consider refactoring for better maintainability.

<a href='https://github.com/microsoft/vscode/pull/235697/files#diff-9d33df30c0953d8c43bdb5285db467b65a408ea054206635f08ef026f7ccbe27R141-R141'><strong>Typo in Constant</strong></a><br>There is a typo in the constant name 'IgnoreCodeBlocks' which is spelled as 'accesibility.voice.ignoreCodeBlocks' instead of 'accessibility.voice.ignoreCodeBlocks'.

</td></tr>
</table>

2024-12-11 05:38 UTC, bpasero requested changes
The approach in principle makes sense to me but it does not work: the chunk from here:

```
const { chunk, offset } = this.parseNextChatResponseChunk(response, totalOffset);
```

No longer contains any backticks. They are removed when calling `renderStringAsPlaintext` I believe, can you check?

2024-12-11 06:23 UTC, bpasero submitted a review, later dismissed

2024-12-11 06:25 UTC, bpasero commented
Thanks!

2024-12-11 07:47 UTC, dbaeumer submitted a review, later dismissed

2024-12-11 20:07 UTC, bpasero commented
@jaymroy can you agree to the CLA bot?

2024-12-11 21:29 UTC, jaymroy commented
> License

@microsoft-github-policy-service agree

2024-12-11 21:47 UTC, meganrogge approved these changes

2024-12-12 01:04 UTC, TylerLeonhardt commented on src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts
> +interface IChatSyntheSizerContext {
Shouldn't `SyntheSizer` be `Synthesizer`?

2024-12-12 03:47 UTC, DonJayamanne approved these changes

2024-12-12 03:48 UTC, merged