inline edit view refactoring
microsoft/vscode pull request #235836
Opened 2024-12-11 15:22 UTC by hediet

2024-12-11 15:46 UTC, jrieken requested changes, later dismissed
uppercase filename for `Inline...` isn't how we do it

2024-12-12 14:05 UTC, alexdima approved these changes, later dismissed

2024-12-12 15:00 UTC, Tyriar approved these changes

2024-12-12 15:01 UTC, alexdima approved these changes

2024-12-12 15:01 UTC, merged