During unpin, only update viewlet switcher if it has already been rendered
microsoft/vscode pull request #28568
Opened 2017-06-12 21:44 UTC by nicksnyder

This avoids a javascript error if unpin is called before the activity bar renders.

2017-06-13 04:33 UTC, bpasero requested changes

2017-06-13 04:33 UTC, bpasero commented on src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
> +			if (this.viewletSwitcherBar) {
@nicksnyder should we not just move this check into the `updateViewletSwitcher` method? There are many more places where we call it.

2017-06-13 17:24 UTC, nicksnyder commented on src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
> +			if (this.viewletSwitcherBar) {
Makes sense, updated.

2017-06-14 08:26 UTC, bpasero commented
LGTM

2017-06-14 08:26 UTC, merged