Task experiment 1.5
microsoft/vscode pull request #29506
Opened 2017-06-26 23:50 UTC by Lixire

Don't merge please :') 

- There must be a better way, right?

2017-07-03 02:20 UTC, roblourens requested changes

2017-07-03 02:20 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +.task-statusbar-item-label>.task-statusbar-item-label-counter {
Did you mean to reformat these? Maybe "format document" did the wrong thing

2017-07-03 02:20 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +	width: 1500;
1500px

2017-07-03 02:23 UTC, roblourens commented
I thought you said something about just showing the mockup with buttons for "is this helpful? yes/no", is that the plan? This looks like the mockup next to the original buttons for running task commands, in which case it will be confusing why the mockup is there.

2017-07-05 19:55 UTC, Lixire commented
@roblourens No worries, that commit was me saving stuff before I left for the weekend.

2017-07-12 17:49 UTC, roblourens requested changes

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +	margin-right: 10%;
Fix indentation

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		});
Don't duplicate all this, have some function that's attached to onThemeChange and also call it manually during `create()`

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskButtons.ts
> +export function domElement() {
maybe `getHtml()` - it's not a dom element yet

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskButtons.ts
> +export function domElement() {
This file could be named better, or just move this function inside taskPanel.ts

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +
extra lines

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		let builder = parent.innerHtml(domElement());
Use `const` when possible

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +			if (!this.storageService.get(this.taskExperimentPart5)) {
Maybe if someone has already replied, it should show the "thanks" message right away when they open the panel?

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		if (!dimension) {
Not necessary?

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		if (!dimension) {
And clean up `getActions`, `setVisible`, and `focus`

2017-07-12 17:49 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +	font-size: large;
Use a `px` size for font-sizes, I don't know if `large`, `smaller` etc are consistent.

2017-07-12 17:51 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +.hidden {
These css class names and rules are in the same global namespace as everything else in the product, so it's possible to have conficts. Two ways to deal with that - write rules to only apply inside the task panel `.task-panel .hidden { ...` or write specific class names `.task-panel-hidden { ...`. I'd recommend making most of these rules more specific.

2017-07-12 17:53 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts
> +export class ConfigureTaskRunnerAction extends OpenTaskConfigurationAction {
If you aren't exposing these actions from the panel, I think you can clean up these changes too.

2017-07-12 18:43 UTC, Lixire commented on src/vs/workbench/parts/tasks/electron-browser/media/task.contribution.css
> +	margin-right: 10%;
What do you mean here?

2017-07-13 17:15 UTC, roblourens approved these changes

2017-07-13 17:16 UTC, roblourens commented
Looks like it has some conflicts

2017-07-13 17:20 UTC, roblourens commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		} else if (thumbButtons.hasClass('dark')) {
Is this right? If you are switching from one dark theme to another dark theme, then it seems like it will fall into the second `if`.

2017-07-13 17:25 UTC, Lixire commented on src/vs/workbench/parts/tasks/electron-browser/taskPanel.ts
> +		} else if (thumbButtons.hasClass('dark')) {
true

2017-07-13 17:55 UTC, merged