Feature 29241: Add option to disable git indicators in gutter
microsoft/vscode pull request #29700
Opened 2017-06-28 04:38 UTC by BugraC

Feature #29241: Add option to disable git indicators in gutter

2017-08-22 08:01 UTC, joaomoreno commented on src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
> +	id: 'editor',
This should be `scm`.

2017-08-22 08:07 UTC, joaomoreno requested changes
If decorators are to be disabled, more needs to be done:

- You need to dispose and clean out all instances of `DirtyDiffModelDecorator`.
- You need to detach the `onEditorsChanged` listener.

You're also missing a configuration change listener, which should enable/disable the decorations accordingly.

2017-08-22 08:07 UTC, joaomoreno commented on src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
> +	id: 'editor',
This should be `scm`

2017-08-22 08:07 UTC, joaomoreno commented on src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
> +		'editor.enableDecorators': {
The property should be `scm.enableDiffDecorations`.

2017-08-22 08:07 UTC, joaomoreno commented on src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
> +			'description': localize('enableDecorators', "Enables or disables color decorators when changes happen in the editor.")
`Enables or disables diff decorations in modified files.`

2017-12-11 15:18 UTC, merged

2017-12-11 16:16 UTC, joaomoreno commented
Thanks! 🍻

2017-12-12 09:24 UTC, joaomoreno commented
Went ahead and changed the setting to accommodate https://github.com/Microsoft/vscode/issues/21795

You can now control this with `scm.diffDecorations`, which has the following possible values: `['all', 'gutter', 'overview', 'none']`.

2018-03-31 11:25 UTC, malimichael commented
Thanks guys, great change. I've just switched to VS code and I'm curios why the modified colour for the gutter is blue whilst the modified colour on the file name itself is orange. To me it makes sense to make these the same colour