Fix #8132. Open folder in integrated terminal.
microsoft/vscode pull request #30354
Opened 2017-07-10 21:14 UTC by rebornix

This is the first touch on Open Folder in Integrated Terminal. Some decisions still need to be revisited

* Configuration Name. Now I call it  `terminal.terminalKind` to align with  https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L198 . We have put settings for integrated terminal in `parts/terminal` folder and external ones in `parts/execution`. I'm not sure putting this one into `parts/explorer` and name it as `explorer.terminalKind` would be a good idea as then we have settings for terminal in three different places.
* I didn't touch `runInTerminal` yet as right now the only contrib `contrib/debug` who uses this API decides whether to use integrated terminal itself https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L21 . Add a path for integrated terminal in `runInTerminal` doesn't make sense without touching `debug` contrib.

2017-07-10 21:56 UTC, Tyriar requested changes

2017-07-10 21:56 UTC, Tyriar commented on src/vs/workbench/parts/execution/electron-browser/terminal.contribution.ts
> +		const configuration = this.configurationService.getConfiguration<ITerminalConfiguration>();
I think we actually want to make this decision in `ExplorerViewerActionContributor`, `OpenConsoleAction` is an action on the external/native terminal right now. Currently having `terminal.terminaKind` as `"integrated"` would make ctrl+shift+c behave similar to ctrl+` by creating and showing a new terminal - we want both to be able to be used at the same time.

2017-07-10 22:45 UTC, rebornix commented on src/vs/workbench/parts/execution/electron-browser/terminal.contribution.ts
> +		const configuration = this.configurationService.getConfiguration<ITerminalConfiguration>();
Nice catch, addressed.

2017-07-10 23:44 UTC, rebornix commented
Now we register Open in Terminal/Integrated Terminal in Files part and put corresponding configuration in Files part as well.

2017-07-10 23:52 UTC, Tyriar requested changes

2017-07-10 23:52 UTC, Tyriar commented on src/vs/workbench/parts/execution/browser/execution.contribution.ts
> +		this.order = 49; // Allow other actions to position before or after
Can be pulled into `AbstarctOpenInTerminalAction`?

2017-07-10 23:55 UTC, Tyriar commented
@bpasero please review the changes in fileActions and the new `explorer.openInTerminalKind` settings key. The original proposal introduced a `terminal.terminalKind` key which is awkward because it would represent a new settings category (or merging of external/integrated terminal categories):

![image](https://user-images.githubusercontent.com/2193314/28045186-77563e1a-6590-11e7-9397-b328e37b2839.png)

Also because I really feel this belongs in the File Explorer category as the functionality is contained within that component:

![image](https://user-images.githubusercontent.com/2193314/28045177-6aa3ec9e-6590-11e7-8f0b-5ac760e20a0a.png)

2017-07-10 23:56 UTC, rebornix commented on src/vs/workbench/parts/execution/browser/execution.contribution.ts
> +		this.order = 49; // Allow other actions to position before or after
Addressed.

2017-07-10 23:58 UTC, rebornix commented
The context menu with new action

![screen shot 2017-07-10 at 4 58 15 pm](https://user-images.githubusercontent.com/876920/28045281-024d29fc-6591-11e7-9cb1-00e42834b4b6.png)

2017-07-11 04:35 UTC, bpasero requested changes
@rebornix @Tyriar guys, we can do better :). The explorer code is now sprinkled with dependencies to `parts/execution`, does that make any sense? The way it used to be was correct: the terminal part would contribute into the explorer part and not force a dependency to the explorer. The explorer should only be concerned about managing and showing files. I have updated https://github.com/Microsoft/vscode/wiki/Code-Organization#workbench-parts

2017-07-11 04:35 UTC, bpasero commented on src/vs/workbench/parts/files/browser/fileActions.contribution.ts
> +import { ExplorerViewerActionContributor as TerminalExplorerViewerActionContributor } from 'vs/workbench/parts/execution/browser/terminal.contribution';
Compile error

2017-07-11 04:35 UTC, bpasero commented on src/vs/workbench/parts/files/browser/fileActions.contribution.ts
> +actionBarRegistry.registerActionBarContributor(Scope.VIEWER, TerminalExplorerViewerActionContributor);
This should move into `execution-contribution.ts`

2017-07-11 04:35 UTC, bpasero commented on src/vs/workbench/parts/files/browser/files.contribution.ts
> +		},
This should be contributed from `execution.contribution.ts`

2017-07-11 04:35 UTC, bpasero commented on src/vs/workbench/parts/files/browser/files.contribution.ts
> +			'default': 'external',
Make the default "integrated"?

2017-07-11 04:35 UTC, bpasero commented on src/vs/workbench/parts/files/common/files.ts
> +		openInTerminalKind: string;
This is not the right place to have it, it should be in execution contribution.

2017-07-11 17:00 UTC, Tyriar commented on src/vs/workbench/parts/files/browser/files.contribution.ts
> +			'default': 'external',
:+1:

2017-07-11 17:08 UTC, Tyriar commented
@rebornix let's go with something like `terminal.explorerKind` as a contribution within the Integrated Terminal settings category.

I created https://github.com/Microsoft/vscode/issues/30402 to do the eventual clean up I'd like to do.

2017-07-11 18:14 UTC, rebornix commented
The final code change consists of 

* Option `terminal.explorerKind`
* Register Open In Integrated Terminal action when above option is set to `integrated` (which is the default value)
* Merge execution.contribution and terminal.contribution.
* Update test cases to avoid failure.

2017-07-12 04:23 UTC, bpasero approved these changes
Thanks, much better. Only noticed one nit: `AbstarctOpenInTerminalAction` (should be "abstract")

2017-07-12 18:03 UTC, Tyriar commented on src/vs/workbench/parts/execution/electron-browser/execution.contribution.ts
> +	public static Label = nls.localize('openFolderInIntegratedTerminal', "Open in Integrated Terminal");
I think we should be using the same name here - adding "Integrated" makes the context menu quite a bit wider without adding much.

2017-07-12 18:47 UTC, rebornix commented on src/vs/workbench/parts/execution/electron-browser/execution.contribution.ts
> +	public static Label = nls.localize('openFolderInIntegratedTerminal', "Open in Integrated Terminal");
Revert to `Open in Terminal` now.

2017-07-12 18:50 UTC, Tyriar approved these changes

2017-07-12 18:50 UTC, merged

2017-07-12 18:50 UTC, Tyriar commented
:fireworks: