env support in terminal api
microsoft/vscode pull request #30352
Opened 2017-07-10 20:49 UTC by ramya-rao-a

Fixes #20446

2017-07-10 22:05 UTC, Tyriar requested changes
Looks good, did you use a extension to verify?

2017-07-10 22:05 UTC, Tyriar commented on src/vs/vscode.d.ts
> +		 * A custom environment for the terminal, if this is not set the environment will be inherited
This should be clear about adding to the environment, not replacing it.

2017-07-10 22:16 UTC, ramya-rao-a commented on src/vs/vscode.d.ts
> +		 * A custom environment for the terminal, if this is not set the environment will be inherited
We are indeed replacing the env. The `env` property on `IShellLaunchConfig` does eventually replace and not add to the VS Code process.

I can change the api to make it additive if you are ok with changing the use of `IShellLaunchConfig` as well

2017-07-10 22:26 UTC, Tyriar commented on src/vs/vscode.d.ts
> +		 * A custom environment for the terminal, if this is not set the environment will be inherited
Asked people's thoughts in https://github.com/Microsoft/vscode/issues/20446#issuecomment-314267087

2017-10-24 17:18 UTC, Tyriar commented
Works like a charm, thanks a lot @ramya-rao-a. Sorry about the delay on my end 😃

2017-10-24 17:18 UTC, merged

2017-10-25 16:58 UTC, chrmarti commented
Thanks everyone! Will be using it with the Cloud Shell integration.