Better reveal logic
microsoft/vscode pull request #33986
Opened 2017-09-08 03:06 UTC by nicksnyder

The current logic only attempts to reveal the line below the zone widget. This does not guarantee that the zone widget is entirely visible.

The logic in this pr first reveals the line above the zone widget (in the center if not already in the viewport) and then reveals the line below the zone widget.

2017-10-23 16:04 UTC, alexandrudima commented
@joaomoreno I'm not sure what the latest change from you does and if it semantically contains the change in this PR.

2017-10-27 09:51 UTC, joaomoreno requested changes
This seems to call `reveal` twice. Leaving it for @jrieken to decide, since it doesn't affect git dirty diff.

2017-10-27 09:52 UTC, joaomoreno commented
Actually no.. I realised I did push changes related to this lately which make this PR obsolete.

2017-10-27 09:54 UTC, joaomoreno commented
I'm actually very confused by this. @alexandrudima My change simply reverted to the old behaviour, since I changed it a couple of weeks ago. Leaving it to @jrieken to decide whether the user's change makes sense.

2017-11-02 17:22 UTC, nicksnyder commented
@joaomoreno @jrieken @alexandrudima 

I updated this diff to resolve conflicts. I think this diff is still relevant. We want both the top and the bottom of the zone widget to be visible.

2017-11-02 17:31 UTC, nicksnyder commented
If you don't want to call `reveal` twice here in general, I can workaround for my use case by overriding `revealLine`.

2017-11-02 22:01 UTC, nicksnyder commented
After playing around with this for a bit, I think overriding `revealLine` is an acceptable solution so going to close this PR.

2017-11-02 22:01 UTC, closed without merging