Use html on enter rules in php
microsoft/vscode pull request #39741
Opened 2017-12-05 23:52 UTC by ramya-rao-a

Fixes #39142

The onEnterRules of html come into play in the html parts of a php file only if the html extension has been activated. So in a case where there is no html file open, the onEnterRules of html doesnt get applied in a php file causing #39142

One way to fix this is to activate html extension when a php file is opened. But that feels like an overhead.
This PR covers another way which is to set the onEnterRules for html in the php extension.

@aeschli @rebornix I am not sure if doing this would cause any issues to html files

cc @roblourens

2017-12-06 09:52 UTC, aeschli commented
The PHP extension should not define any HTML settings. This can result in conflicting settings and random bahaviour once the two settings are no longer the same.
The correct fix is to activate the HTML mode when accessing the onEnterRules.
I suggest to file this issue against the editor / @rebornix.

2017-12-06 09:52 UTC, aeschli requested changes
See my comment

2017-12-06 17:23 UTC, ramya-rao-a commented
> The correct fix is to activate the HTML mode when accessing the onEnterRules

Do you mean activate the HTML extension or use language-config rules of HTML?

I believe the HTML mode does get activated (we do get all the rules as defined declaratively in the `language-configuration.json` file from the `html` extension.
But since the onEnterRules are programmatically defined, they don't show up in the html model unless the html extension gets activated in the current VS Code session.

2017-12-07 00:10 UTC, rebornix commented
Activate HTML mode when accessing onEnterRules would be too late as we don't want to activate an extension when type.

A proper fix can be moving onEnterRules to language configuration, and then they don't rely on extension activation.

2017-12-07 09:19 UTC, aeschli commented
Language configuration can come from both code and declaration. The programmatic API won't go away, so IMO there's no choice than to activate all extensions that have the 'onLanguage:xyz' activation point when accessing the 'xyz' language configurations.
@alexandrudima Alex, your thoughts?

2017-12-07 11:21 UTC, alexandrudima commented
When the tokenizer hits an embedded language, it triggers the loading of language configuration files for the embedded language. It will not activate the embedded language.

This works mostly well, as nobody has complained so far about brackets in php/html/js, etc. The problem here IMHO is that `onEnterRules` cannot at this point be written in language configuration files and they are mostly coming in via the competing `setLanguageConfiguration`.

I suggest the following:
* language configuration files get support for `onEnterRules`
* we slowly but steadily move away from `setLanguageConfiguration` once the file is on-par with the API call.

2017-12-07 14:08 UTC, aeschli commented
As a temporary workaround, I'd suggest that the PHP extension has an extension dependency on the HTML extension.

2017-12-07 17:18 UTC, ramya-rao-a commented
Thanks all!

I'll look into adding the onEnterRules support to the lang-config file in December

2017-12-07 17:18 UTC, closed without merging