Added tags for azure py packages in requirements.txt
microsoft/vscode pull request #59282
Opened 2018-09-25 01:43 UTC by bowdenk7

also tags other py requirement formants (Pipfile, etc) but doesn't crack them open to look for dependencies yet

2018-09-25 21:16 UTC, ramya-rao-a requested changes

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +			tags['workspace.py.conda'] = WorkspaceStats.searchArray(names, /^environment+(\.yml$|\.yaml$)/i);
Why is the `+` needed in this regular expression?

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +				console.log(content.value);
Why console.log?

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +					if (PyModulesToLookFor.indexOf(packageName) > -1) {
`packageName` should be trimmed before we go looking for it in `PyModulesToLookFor`

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +					// congitive services has a lot of tiny packages. eg. 'azure-cognitiveservices-search-autosuggest'
congitive -> cognitive

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +					if (packageName.indexOf('azure-cognitiveservices') > -1) {
`packageName` will be `undefined` when the current line was not of the format `a == b`, and this would throw an error

2018-09-25 21:16 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +			return TPromise.join(dependencyFilePromises).then(() => tags);
The variable `dependencyFilePromises` is not needed. You can do `TPromise.join([...packageJsonPromises, ...requirementsTxtPromises])

2018-09-25 22:53 UTC, bowdenk7 commented
Sample `Pipfile`:

```
[[source]]
url = 'https://pypi.python.org/simple'
verify_ssl = true
name = 'pypi'

[requires]
python_version = '2.7'

[packages]
azure-eventgrid = '>0.5.0'
azure-functions
azure-graphrbac = '*'
azure-keybault = '0.0.1'
requests = { extras = ['socks'] }
records = '>0.5.0'
django = { git = 'https://github.com/django/django.git', ref = '1.11.4', editable = true }
"e682b37" = {file = "https://github.com/divio/django-cms/archive/release/3.4.x.zip"}
"e1839a8" = {path = ".", editable = true}
pywinusb = { version = "*", os_name = "=='nt'", index="pypi"}

[dev-packages]
nose = '*'
unittest2 = {version = ">=1.0,<3.0", markers="python_version < '2.7.9' or (python_version >= '3.0' and python_version < '3.4')"}
```

2018-09-25 22:54 UTC, bowdenk7 commented
Sample `requirements.txt` ([link to docs](
https://pip.readthedocs.io/en/1.1/requirements.html#requirements-files)):

```
autopep8==1.4
certifi==2018.8.24
chardet==3.0.4
click==6.7
dominate==2.3.1
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
gunicorn==19.9.0
idna==2.7
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pycodestyle==2.4.0
python-dotenv==0.9.1
requests==2.19.1
rope==0.11.0
urllib3==1.23
visitor==0.1.3
Werkzeug==0.14.1
azure-storage>=0.0
azure-storage-common==0.0
azure-cognitiveservices-search-autosuggest
```

2018-09-25 23:08 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +						const format2 = dependency.split('>=')[0];
`format1` will always have something. `foo.split('==')` gives an array with a single string of "foo"

2018-09-25 23:17 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +					dependencies = dependencies.slice(dependencies.indexOf('[packages]') + 1, dependencies.indexOf('[dev-packages]'));
This order may not hold true always right?

There might be another section before `[packages]` and `[dev-packages]`.
Or the dev-packages might appear before packages
Or there might not be a dev-packages section at all

2018-09-25 23:18 UTC, ramya-rao-a commented on src/vs/workbench/parts/stats/node/workspaceStats.ts
> +						if (PyModulesToLookFor.indexOf(packageName) > -1) {
When the `dependency` here doesnt have the `=` in it, the `packageName` will be equal to `dependency`

2018-09-26 00:01 UTC, ramya-rao-a approved these changes

2018-09-26 00:06 UTC, ramya-rao-a commented
This area is growing bigger, we should have some tests to back all this up.

2018-09-26 00:33 UTC, merged