Fixes for 58176: Middle clicking files in breadcrumbs explorer opens …
microsoft/vscode pull request #59797
Opened 2018-10-02 01:03 UTC by J-Graham

…as preview

Added a variable to detect the middle click and pass the pinned option when this is true

2018-10-02 01:05 UTC, J-Graham commented
This is a PR for the following issue: https://github.com/Microsoft/vscode/issues/58176.  It's my first attempt and I would love to hear any feedback on if you felt there was a better way to implement this.

2018-10-03 14:15 UTC, jrieken requested changes

2018-10-03 14:15 UTC, jrieken commented on src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts
> +					this._revealInEditor(event, data.target, this._getEditorGroup(data.payload && data.payload.originalEvent), data.payload.originalEvent.middleButton);
`data.payload` might be undefined and will explode now

2018-10-03 14:15 UTC, jrieken commented on src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts
> +	private _revealInEditor(event: IBreadcrumbsItemEvent, element: any, group: SIDE_GROUP_TYPE | ACTIVE_GROUP_TYPE, middleClick: boolean = false): void {
I'd call it `pinned` instead of `middleClick`

2018-10-04 00:28 UTC, J-Graham commented
Thanks for the feedback @jrieken.  Let me know if these changes cover what you need.

2018-10-05 08:29 UTC, jrieken approved these changes
lgtm

2018-10-05 08:29 UTC, jrieken commented
Thanks

2018-10-05 08:29 UTC, merged