Fixed #59395 - Emmet Syntax Profiles tag_nl produces no extra space
microsoft/vscode pull request #60108
Opened 2018-10-07 20:03 UTC by irrationalRock

This PR fixes https://github.com/Microsoft/vscode/issues/59395.

With:
```
"emmet.syntaxProfiles": {
        "html": {
            "tag_nl": false            
        }
    },
```

It no longer allows extra space.

Before:
![vscode-59395-before](https://user-images.githubusercontent.com/16523071/46586211-18a9ba80-ca49-11e8-915a-1d302e2258a5.gif)

After:
![vscode-59395](https://user-images.githubusercontent.com/16523071/46586284-5eb34e00-ca4a-11e8-81a0-e76c7e3e1c8f.gif)

Thanks for considering this request.

2018-10-08 18:37 UTC, ramya-rao-a requested changes
The tests seem to be failing. Can you take a look at that?

To run the tests locally, run `scripts\test-integration.bat` on Windows or `./scripts/test-integration.sh` on Linux/Mac

It would also do us good to add a test case to cover this scenario.
`wrapWithAbbreviation.test.ts` would be the file to update.

2018-10-08 18:37 UTC, ramya-rao-a commented on extensions/emmet/src/abbreviationActions.ts
> +				if (wrappingNode && inlineElements.indexOf(wrappingNode.name) === -1 && emmetConfig.syntaxProfiles['html']['tag_nl']) {
We can probably get the value for `tag_nl` from `expandOptions.profile` object

2018-10-11 18:02 UTC, irrationalRock commented
I updated my code to use `expandOptions.profile`. I'm wondering if you can give me an example of how to change the config in tests. I am having some problems trying to change `tag_nl` to `false`.

2018-10-12 01:05 UTC, ramya-rao-a requested changes
My apologies, I should have cleared some things previously.

The new emmet modules that we use dont use the same `syntaxProfile` settings as documented in https://docs.emmet.io/customization/syntax-profiles/

The new emmet modules follow the profile as defined in https://github.com/emmetio/output-profile/blob/1a7571e78da9d7bf056289b3396dbb0bcc45c435/types.d.ts#L1

To support backward compatibility in VS Code, we support both in the settings. I convert the old profile to a new one using a [helper](https://github.com/Microsoft/vscode-emmet-helper/blob/7ec2e95ea7caea3d938e70cc194a9bb4eebd05e3/src/emmetHelper.ts#L689)

So now coming to the current issue. You can just add `expandOptions['format'] === true` to the `if` condition and that should be enough.

2018-10-12 01:08 UTC, ramya-rao-a commented
https://github.com/Microsoft/vscode/blob/release/1.28/extensions/emmet/src/test/abbreviationAction.test.ts#L441 is an example where I changed the config for the `emmet.excludeLanguages` setting. You can use that as an example.

2018-10-17 21:42 UTC, irrationalRock commented
Thanks for the help. I had to use `expandOptions['profile'].format` instead of `expandOptions['format']` because it didn't seem to produce any properties when `tag_nl` was set to `true`.
I also added tests for this feature.

2018-10-20 21:08 UTC, irrationalRock commented
It seems like my commits fail when running the hygiene tests. Is there any way for me to run these tests on my local machine? Running `./scripts/test-integration.sh` passes all of the tests.

2018-10-23 02:29 UTC, ramya-rao-a commented
The hygiene failure was due to formatting errors. I have pushed a change to fix that.

2018-10-23 02:31 UTC, ramya-rao-a approved these changes

2018-10-23 02:39 UTC, merged

2018-11-08 22:12 UTC, contentfree commented
Wrap still produces incorrect results if `tag_nl_leaf` is false, I believe. (`tag_nl_leaf` doesn't seem to be respected at all, really, nor does the `'decide'` value for `tag_nl`)

2018-11-08 22:30 UTC, ramya-rao-a commented
@contentfree I have logged an upstream issue for that. See https://github.com/emmetio/output-profile/issues/1