#61410 Add keybinding to "Find in Folder" action
microsoft/vscode pull request #61526
Opened 2018-10-22 20:19 UTC by maxbarnas

Resolves https://github.com/Microsoft/vscode/issues/61410

I left the handler in `search.contibutions.ts` because of import linting rules on `workbench/parts/*/browser/*` files. 
Happy to fix that if pointed how.

2018-10-22 21:05 UTC, Tyriar commented
@roblourens I'm not sure we're meant to use ctrl+alt+ as default keybindings?

2018-10-22 21:11 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Microsoft/vscode?pullRequest=61526) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Microsoft/vscode?pullRequest=61526) before we can accept your contribution.<br/><br/>:x: maxbarnas [sign now](https://cla.opensource.microsoft.com/Microsoft/vscode?pullRequest=61526)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Microsoft/vscode?pullRequest=61526) it.</sub>

2018-10-22 22:00 UTC, roblourens commented
How about `shift+alt+f` on windows?

2018-10-22 22:20 UTC, maxbarnas commented
> How about `shift+alt+f` on windows?

Works fine when having selected a folder. But fires code formatting when focused in editor and opens File menu when focused on a file (not folder) in Side Explorer. None of those are happening with <kbd>Ctrl+Alt+f</kbd>.

Still, I might be missing bigger picture here therefore I can lean towards your suggestion.

2018-10-23 18:20 UTC, roblourens commented
So I filed https://github.com/Microsoft/vscode/issues/61644 for the File menu opening when alt+shift+f is pressed, because that seems wrong

2018-11-01 00:07 UTC, roblourens commented
Ok that other issue has been fixed, I think alt+shift+f is a good shortcut. But it's too late for the October release. You can update the PR anytime and I'll merge it next week for the November release.

2018-11-01 11:57 UTC, maxbarnas commented
I've changed the key binding but some pipelines failed for (apparently) no good reason. Is there a way to rerun them?

2018-12-10 21:53 UTC, roblourens commented
Sorry, I forgot about this PR. Taking a look now.

2018-12-10 21:53 UTC, roblourens requested changes

2018-12-10 21:53 UTC, roblourens commented on src/vs/workbench/parts/search/electron-browser/search.contribution.ts
> +CommandsRegistry.registerCommand({
I think this is registering the command twice now. `registerCommandAndKeybindingRule` should do this work already

2018-12-22 15:55 UTC, merged