Add Git log, globalConfig, and tree diff API
microsoft/vscode pull request #64826
Opened 2018-12-11 22:13 UTC by IlyaBiryukov

Fix for #62609,
cc @joaomoreno

2018-12-14 01:55 UTC, IlyaBiryukov commented
The test failures doesn't look to have anything to do with my changes.

2018-12-20 10:07 UTC, joaomoreno requested changes

2018-12-20 10:07 UTC, joaomoreno commented on extensions/git/src/git.ts
> +		const entries = gitResult.stdout.split('\x00\x00');
This will get expensive. We should instead do a _while regex exec_ loop and keep matching commits until we reach the end of `gitResult.stdout`.

2018-12-20 10:07 UTC, joaomoreno commented on extensions/git/src/git.ts
> +	async diffWithHEAD(path?: string): Promise<string | Change[]> {
Could we move those cool overloads also here?

```ts
 	diffWithHEAD(): Promise<Change[]>;
 	diffWithHEAD(path: string): Promise<string>;
 	diffWithHEAD(path?: string | undefined): Promise<string | Change[]> {
```

2019-01-07 10:14 UTC, joaomoreno commented
ping @IlyaBiryukov

2019-01-28 14:35 UTC, merged