Detect md image link
microsoft/vscode pull request #66958
Opened 2019-01-23 00:56 UTC by flurmbo

Fixes #49238. I added an option to the regex to have an image instead of text for the link description. Then when iterating over regex matches `providerInlineLinks` will now check to see if an image resource was also matched, and if so add it to results. All the tests pass, as well as a new one I've added. 

Feedback on the regex would be appreciated, also I think perhaps the code I copied [starting here](https://github.com/Microsoft/vscode/blob/2d79ffe0cd84515a4c771fcbd7294c2448d97826/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L76) could be refactored into a separate function.

2019-01-23 20:01 UTC, mjbvz requested changes
Thanks for taking a look! Changes look good, just a few tweaks.

Let me know if you have any questions about my comments or the code

2019-01-23 20:01 UTC, mjbvz commented on extensions/markdown-language-features/src/features/documentLinkProvider.ts
> +				const imageOffset = (match.index || 0) + imagePre.length + 1;
I agree that you can refactor out this logic. I'd create a function that either returns a `DocumentLink` or `undefined` (if an exception was thrown)

2019-01-26 01:46 UTC, merged

2019-01-26 01:47 UTC, mjbvz commented
Thanks! This change will be in the next VS Code insiders build and is scheduled to be included in VS Code 1.31

2019-01-26 02:02 UTC, flurmbo commented
Awesome, thanks for the fast response