Fix for oversized folding icons
microsoft/vscode pull request #68226
Opened 2019-02-08 10:27 UTC by andyunleashed

This adjustment fixes the issue of massive folding icons in the gutter when using a large line referenced in issue [#59695](https://github.com/Microsoft/vscode/issues/59695)

2019-02-08 12:43 UTC, usernamehw approved these changes

2019-02-08 17:03 UTC, miguelsolorio requested changes
Thanks for taking a look at this! The problem that this introduces is that at higher font sizes (like 30px) the folding icons do not re-size accordingly (see screenshots below). Can you make this also work with large font sizes?

## With your PR
<img width="828" alt="image" src="https://user-images.githubusercontent.com/35271042/52493429-454d1a80-2b80-11e9-8cc2-8da8caf9e250.png">

## Current Experience
<img width="843" alt="image" src="https://user-images.githubusercontent.com/35271042/52493446-5007af80-2b80-11e9-8efa-ac748de8a53d.png">

2019-02-08 22:33 UTC, andyunleashed commented
Hi @misolori - I looked into it and unfortunately it seems to be one or the other, at least without resizing the gutter as well.

The best result so far has been using `background-size: 1.4em;` for `.folding` - but at font sizes around 50px it crops like it was doing for the line height as it seems to get too big for the available space.

I think it'll always be a bit of a trade off size wise unless the width of the gutter is flexible too, but I can't see in the code where that is determined, unless you can point me in the right direction?

2019-02-08 23:47 UTC, misolori commented
I think we’ll always have this issue so long as we use background images for icons. And I do believe the gutter is relatively fixed (@rebornix can you confirm?). 

We’re currently working on redesigning all of our icons and are looking into using an icon font, which would easily fix this issue as it will be able to scale via font size and line height.

2019-02-09 19:13 UTC, andyunleashed commented
> We’re currently working on redesigning all of our icons and are looking into using an icon font, which would easily fix this issue as it will be able to scale via font size and line height.

That sounds pretty cool and would definitely clear this issue, if there's anything I can help with on that give me a shout.

2019-02-11 17:14 UTC, rebornix commented
> And I do believe the gutter is relatively fixed

@misolori yes, it has a fixed width and we will adjust when line numbers width changes.

2019-08-26 17:59 UTC, closed without merging