fix link navigation to extended config file in tsconfig
microsoft/vscode pull request #71944
Opened 2019-04-08 15:00 UTC by vitaliymaz

2019-04-08 15:14 UTC, vitaliymaz commented
Fixes #71639

2019-04-08 18:40 UTC, mjbvz requested changes
Thanks for taking a look. Just a few minor changes and I think we can merge this for April

2019-04-08 18:40 UTC, mjbvz commented on extensions/typescript-language-features/src/features/tsconfig.ts
> +		if (extendsNode.value.startsWith('./') || extendsNode.value.startsWith('../')) {
Not sure if TS supports windows style paths but to be safe I think this condition can just be `startsWith('.')`.

2019-04-08 18:40 UTC, mjbvz commented on extensions/typescript-language-features/src/features/tsconfig.ts
> +				vscode.Uri.file(join(dirname(document.uri.fsPath), extendsNode!.value + (basename(extendsNode.value).match('.json$') ? '' : '.json')))
Use `endsWith` instead of `match` (so we don't have to escape the `.`)

2019-04-09 18:26 UTC, merged

2019-04-09 18:26 UTC, mjbvz commented
Thanks! Change will be in the next VS Code insiders build and is scheduled to ship with VS code 1.34