Fix spelling of the example abbreviation (e.g.)
microsoft/vscode pull request #74785
Opened 2019-06-03 11:08 UTC by waldyrious

Most of the instances of this abbreviation already use the "e.g." form.
This commit changes the non-conforming ones to match.

Note that although this commit changes 29 files, almost all of these changes are in code comments. The only user-visible ones are in the README, and in localizable strings on the following six files:

- src/vs/code/node/cliProcessMain.ts
- src/vs/workbench/contrib/debug/common/debugSchemas.ts
- src/vs/workbench/contrib/extensions/electron-browser/extensions.contribution.ts
- src/vs/workbench/contrib/markers/browser/messages.ts
- src/vs/workbench/contrib/snippets/browser/snippets.contribution.ts
- src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts

2019-06-03 11:12 UTC, waldyrious commented
By the way, I'm not making this change spuriously; My original goal was to propose a change one of these messages (the one in [src/vs/workbench/contrib/markers/browser/messages.ts](https://github.com/microsoft/vscode/pull/74785/files#diff-d99f77eba286403d5e3f2a2f6fc6f606)), to make it clearer and more explicit, like this:

```diff
-"Filter. Eg: text, **/*.ts, !**/node_modules/**");
+"Filter files. E.g.: text, **/*.ts, !**/node_modules/**");
```

but didn't want to change the "Eg." to "E.g." in one place while leaving the others in an inconsistent state.

2019-06-05 09:29 UTC, alexr00 commented
The files under src\typings are copied in, and shouldn't be changed since the changes will get overwritten.

2019-06-05 09:34 UTC, alexr00 requested changes

2019-06-05 09:34 UTC, alexr00 commented on src/vs/base/parts/tree/browser/tree.ts
> +	 * related IDs (e.g.. full file path, in the Explorer example).
Extra period.

2019-06-05 12:51 UTC, waldyrious commented
Thanks for the careful review, @alexr00. I'll fix and update the PR shortly.

2019-06-05 13:59 UTC, alexr00 approved these changes
Looks good to me!

2019-06-05 14:00 UTC, merged

2019-06-05 18:02 UTC, waldyrious commented
@alexr00 thanks for the quick merge :) for future reference, was the extended message in this specific commit not particularly useful, or is there some guideline to not add additional details to commit messages?

2019-06-06 07:46 UTC, alexr00 commented
Concise details are always welcome!