Support Update VS Code from Command Palette
microsoft/vscode pull request #77515
Opened 2019-07-17 10:25 UTC by DiamondYuan

close https://github.com/microsoft/vscode/issues/77184

2019-07-17 10:25 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=77515) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=77515) before we can accept your contribution.<br/><br/>:x: DiamondYuan [sign now](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=77515)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vscode?pullRequest=77515) it.</sub>

2019-07-18 02:41 UTC, DiamondYuan commented
@joaomoreno 

CI broken,How to fix it ?

```
src/vs/workbench/contrib/update/common/update.ts:6:48:Unexternalized string found: "update.showCurrentReleaseNotes"
src/vs/workbench/contrib/update/common/update.ts:7:45:Unexternalized string found: "update.checkForVSCodeUpdate"
```

2019-07-18 09:35 UTC, joaomoreno requested changes
Please merge both classes, there's no need for an abstract class here.

2019-07-18 09:36 UTC, joaomoreno requested changes

2019-07-18 09:36 UTC, joaomoreno commented on src/vs/workbench/contrib/update/common/update.ts
> +export const CheckForVSCodeUpdateActionId = "update.checkForVSCodeUpdate";
You need to use single quotes, not double quotes.

2019-07-18 10:19 UTC, DiamondYuan commented
> Please merge both classes, there's no need for an abstract class here.

Ci Broken,Time out

2019-07-18 13:22 UTC, joaomoreno commented
CI is not broken. You are using double quotes instead of double quotes. CI is telling you exactly that. Fix that please.

2019-07-18 13:27 UTC, DiamondYuan commented
> CI is not broken. You are using double quotes instead of double quotes. CI is telling you exactly that.

![image](https://user-images.githubusercontent.com/9692408/61461106-a0423380-a9a2-11e9-8e42-22b41d7dcc0e.png)


https://dev.azure.com/vscode/VSCode/_build/results?buildId=23300

Last CI broken was due to timeout. I have fix the error.

2019-07-23 02:24 UTC, DiamondYuan commented
cc @joaomoreno  when will whit PR be merged ?

2019-09-24 18:35 UTC, ian-sawyer approved these changes

2019-10-25 09:55 UTC, merged

2019-10-25 09:56 UTC, joaomoreno commented
Thanks! :beers: