Fix #82200 - "Preserve Case" button in search viewlet is not tabbable
microsoft/vscode pull request #82485
Opened 2019-10-14 06:31 UTC by skprabhanjan

@roblourens  , Added the tab functionality for the preserve case button in order to fix #82200.

Whatever `onRegexKeyDown` was doing before is now being done in `onPreserveCaseKeyDown` and `onRegexKeyDown` only makes the preserve case to get focussed.

2019-10-15 23:07 UTC, roblourens requested changes
Great, except tabbing backwards (shift+tab) needs to work too.

2019-10-16 17:30 UTC, skprabhanjan commented
@roblourens , Sorry forgot to add that part but it is taken care now , Please check :)

2019-10-16 21:37 UTC, roblourens commented
Ok now if the replace input is collapsed, I can't shift+tab past the details `...` button, I get stuck there.

2019-10-22 17:03 UTC, skprabhanjan commented
@roblourens  . Fixed this and sorry for the delay :)

2019-10-23 00:54 UTC, roblourens commented
Thanks!

2019-10-23 00:55 UTC, merged