#82105 Add Terminal Rename Command
microsoft/vscode pull request #84429
Opened 2019-11-10 22:04 UTC by petevdp

This PR fixes #82105 by registering a new command `workbench.action.terminal.renameNoninteractive` that allows the user to set the terminal title via an argument instead of interactively.
example usage: 
```jsonc
{
        "key": "ctrl+t",
        "command": "workbench.action.terminal.renameWithArgs",
        "args": {
            "newName": "my new terminal name"
        }
}
```

The current changes acheive this, but a few things still have to be sorted out:

* I'm open to suggestions for the name.
* It seems possible to rename the terminal based on its index or even ID, if terminal IDs are exposed to the user. Would this be desirable behaviour? This would probably take the form of an optional argument `index`, and not changing the default behaviour. 
* How should I notify the user if the desired terminal doesn't exist? I'm guessing you can just throw an error, but if there's a preferred channel or preferred error message formatting, that would be good to adhere to.
* I see that there's an adjacent file called [terminalCommands.ts](https://github.com/microsoft/vscode/blob/c3e7a4a1ec93ec8af9c7a530ab4bf409838e3d2a/src/vs/workbench/contrib/terminal/browser/terminalCommands.ts). There are other commands similar to this one in *terminalActions.ts* but *terminalCommands.ts* obviously seems more appropriately named.

Any additional suggestions for preferred/extended functionality are welcome!

2019-11-10 22:04 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=84429) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=84429) before we can accept your contribution.<br/><br/>:x: petevdp [sign now](https://cla.opensource.microsoft.com/microsoft/vscode?pullRequest=84429)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vscode?pullRequest=84429) it.</sub>

2019-11-25 15:17 UTC, Tyriar requested changes
Doh, forgot to post this review earlier

2019-11-25 15:33 UTC, Tyriar approved these changes
Thanks @petevdp, sorry about the delay. The command name is now `renameWithArg`

2019-11-25 15:33 UTC, merged

2019-11-25 16:05 UTC, petevdp commented
Thanks @Tyriar!
And no problem, I'm in no rush!