Removes short-circuit that causes mis-alignment
microsoft/vscode pull request #85657
Opened 2019-11-27 04:50 UTC by eamodio

This PR fixes #85654

2019-12-02 09:48 UTC, alexr00 requested changes
Just deleting that condition results in another bad behavior where the icon of a child is further left than the icon of he parent. Insiders on the left, built from your PR on the right:
![image](https://user-images.githubusercontent.com/38270282/69949166-46757c80-14f1-11ea-933c-c61a133ef4d2.png)

2020-08-12 22:12 UTC, eamodio commented
@alexr00 I refined the logic here, which should better target this explicit case -- let me know what you think.

2020-08-13 11:29 UTC, alexr00 commented
I'm happy with it. It looks like an all-around improvement.

2020-08-13 11:30 UTC, alexr00 approved these changes

2020-08-13 11:31 UTC, merged