Add useActiveLanguage option to open new files with the language mode of the active editor
microsoft/vscode pull request #87007
Opened 2019-12-15 01:35 UTC by jzyrobert

This PR fixes #78903

Demo:
![6cZsyC6rvt](https://user-images.githubusercontent.com/20613660/70856465-b57da880-1ed5-11ea-90c7-61c147747d90.gif)

- When editor without language mode or no editor is open, default to files.useActiveLanguage
- If a valid editor is open, new untitled files will open in the same language mode.

This is different to what the issue originally proposed (having a "current" option for files.defaultLanguage), as it allows you to both have a files.defaultLanguage for fall-back and make use of this option.

- Ideally the UntitledEditorService can retrieve the current active TextModel by itself, but not sure how to do that.

2019-12-15 15:13 UTC, Ronkiro approved these changes

2019-12-16 07:14 UTC, bpasero requested changes
I would prefer if the mode would be set where we currently set the mode here:

https://github.com/microsoft/vscode/blob/3014b7bf40ff8fdca58189cc5f5284719e6bdb27/src/vs/workbench/services/untitled/common/untitledTextEditorService.ts#L248

Unfortunately the untitled editor service cannot depend on the editor service on that layer, so possibly a new service would have to be introduced to get the current active mode.

I like the suggestion in the issue to allow `files.defaultLanguage: current` instead of introducing a new setting. There is a slight chance of conflict, but I doubt it would be an issue.

2019-12-18 13:03 UTC, jzyrobert commented
@bpasero Is it not acceptable to have the editorService pass the current mode in as an optional parameter?
I am not sure how a new service would be added.

2019-12-18 14:07 UTC, bpasero commented
I would think the safest option is to have the language picked at the place where the untitled editor input is created because there might be more code paths leading to that code not from the editor service itself. 

I understand that this may be more technically challenging, but then suggest to close this PR and start a different solution if possible.

2019-12-18 22:03 UTC, jzyrobert commented
I can give it a go, do you have any tips for where to start, or existing services to look at?

2020-01-06 09:21 UTC, bpasero commented
I decided to go ahead and add this via https://github.com/microsoft/vscode/commit/0fd2883856bde19a78367705c30bcfcc91e2af47 since it required a bit of additional work. Thanks for the bootstrap :+1:

2020-01-06 09:21 UTC, closed without merging