Correct explorer opening & add ctrl double click support
microsoft/vscode pull request #87490
Opened 2019-12-21 00:18 UTC by jzyrobert

This PR fixes #87082 
@isidorn 
This PR consists of:

- Re-introducing [this](https://github.com/microsoft/vscode/commit/8b91600b08f5d88ba9d79785a7014c67f492629a) commit to respect the element that is passed in, instead of taking the first one from the selection.
- The above change was pushed and reverted by @isidorn as other parts of the code relied on the function catching incorrect opens with the `length === 1` check. The additional changes remedy that.
- Adding a shift-check for MouseEvent in `onDidOpenResource` such that opens are not triggered by shift-click selecting.
- Moving `focus` to be the first index in `setSelection` as `onSelection` always takes the first index, (This could also be changed to be last), as otherwise the first selected file is always the one incorrectly opened, as reported by #87082 
- Only triggering an `open` inside `onSelection` through a single click or double click when there is only one item in the selection, to prevent unnecessary calls.
- Adding the (somewhat hacky) ability to open a file to the side using Ctrl + double click, when you already have other files selected and want to keep the selection.
- This currently opens files to the side in _non-preview_ mode, which may not be wanted. This could be remedied by setting `doubleClick` to false again after `isCtrlDoubleClick` is true

2019-12-23 14:15 UTC, isidorn commented
Thanks a lot for this PR.
However the `isCtrlDoubleClick` checks feel too specific to live on the `listWidget` layer. I would like @joaomoreno to review this once he is back from vacation. I personally do not like them and sorry for not providing a suggestion on how to correctly tackle this.
Changes in the `explorerView` look good to me.

Anyways this PR is not urgent since we always behaved like this, thus assigning to backlog.

2019-12-23 21:17 UTC, jzyrobert commented
@isidorn I agree its not a particularly great implementation.
Do you want me to make a separate PR with the fixes only?

2019-12-24 08:56 UTC, isidorn commented
@jzyrobert if you can make a cleaner PR that is always good. However as I mentioned this is not high priority and Joao is on vacation so it might take some time until we merge this.

2020-01-15 10:12 UTC, joaomoreno requested changes
I'm definitely not a fan of harcoding this down at the list level, if we're trying to fix an Explorer bug.

2020-03-16 10:12 UTC, thernstig commented
@jzyrobert Did this stall? :) Annoyed by the behavior and your fix would be greatly appreciated.

2020-03-16 10:57 UTC, jzyrobert commented
> @jzyrobert Did this stall? :) Annoyed by the behavior and your fix would be greatly appreciated.

When I have some spare time I can extract the fix code, the added hard-coded double click behaviour is what hasn't got it merged.

2020-05-23 07:54 UTC, thernstig commented
@jzyrobert Still would love this change, I bump into this "try to double click" all the time 😆

2020-05-23 16:53 UTC, jzyrobert commented
Hey @thernstig, it looks like some of the code this was based on has changed, and I did some more investigation.
I think the issue consists of two main points:

1. When using Ctrl + click to select multiple things, unselecting all except one will trigger a side open of the last selected file. This is due to existing checks where selection.length === 1 (see [here](https://github.com/microsoft/vscode/blob/a1ed386162d6a5741ed440c6b8998ca5728a89f8/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L421)) triggers an open. I would consider this a bug, and fixing it would be somewhat tricky, because ctrl click without any previous selections should open the file to the side.

I'm not sure how to solve this, because only the new selection is passed down, rather than the element being focused on. You would have to somehow check that the last selected element matches the element you focused on, and then allow the open.

2. Double click events on list items are ignored if they are part of a selection change (see [here](https://github.com/microsoft/vscode/blob/a1ed386162d6a5741ed440c6b8998ca5728a89f8/src/vs/base/browser/ui/list/listWidget.ts#L647))
This is rather old code, and I'm not sure if removing that would cause any new problems.

So essentially what you're seeing is not a bug in the double click behaviour, but that its being treated as two single clicks and triggering bug 1.

@isidorn Would you have any input on this?

2020-11-05 14:20 UTC, isidorn commented
Joao Moreno worked on updating how we handle the click and double click in the tree.
Thus closing this as it is outdated now

2020-11-05 14:20 UTC, closed without merging

2020-11-06 11:40 UTC, thernstig commented
@isidorn is there a PR we can track?