Add setting to control whether to focus the inline editor in peek widget by default
microsoft/vscode pull request #88185
Opened 2020-01-07 03:09 UTC by jeanp413

This PR fixes #23001

2020-01-07 10:00 UTC, jrieken requested changes

2020-01-07 10:00 UTC, jrieken commented on src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts
> +	private _gotoReference(ref: Location): Promise<void> {
unrelated change? (this and the two below)

2020-01-07 12:04 UTC, jeanp413 commented on src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts
> +			this._widget.focusOnPreviewEditor();
`this._widget` could be undefined if inside `this._gotoReference` it goes through here ⬇️ , though not sure how to trigger that from within the editor.
https://github.com/microsoft/vscode/blob/a78e5830fd58bead0d190e689e16097bbdb669c9/src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts#L252-L257

2020-01-08 08:12 UTC, jrieken commented on src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts
> +			this._widget.focusOnPreviewEditor();
Check

2020-01-08 08:16 UTC, jrieken commented on src/vs/editor/common/config/commonEditorConfig.ts
> +		},
Sorry, the stablePeek setting wasn't actually a good sample. Try [`suggestFontSize`](https://github.com/microsoft/vscode/blob/8349ba385a89c3cf62c51de405a849e06a588fbc/src/vs/editor/common/config/editorOptions.ts#L3603). You need to add the property to `IEditorOptions`, `EditorOptions` and `EditorOption`

2020-01-09 02:54 UTC, jeanp413 commented on src/vs/editor/common/config/commonEditorConfig.ts
> +		},
Done 👍

2020-01-10 17:10 UTC, jrieken approved these changes
Looking good. Not super happy with the name of the setting yet, but we can tweak that at a later time - unless you have spontaneous idea.

2020-01-13 09:20 UTC, merged