selectively propagate debugging arguments for payload
microsoft/vscode pull request #96211
Opened 2020-04-26 22:57 UTC by weinand

This PR fixes #95957

The fix analyses the properties in the current payload and copies only debugging related properties to a new payload which is passed to the newly opened tab.
If no debugging related properties are found no payload is passed.

This fix works for the "Open folder" and the "Open workspace" case.

2020-04-27 11:43 UTC, bpasero requested changes
Thanks! 

I wonder though, is it really necessary to parse the `payload` from the workspace provider if the properties are already existing on the `IWorkbenchEnvironmentService`? Can we not simply take them from there?

2020-04-27 11:43 UTC, bpasero commented on src/vs/workbench/services/host/browser/browserHostService.ts
> +			let newPayload: Array<any> | undefined = undefined;
```suggestion
			let newPayload: Array<unknown> | undefined = undefined;
```

2020-04-27 14:23 UTC, weinand commented
@bpasero Yes, I'll investigate whether getting the properties from the `IWorkbenchEnvironmentService` is straightforward. On first glimpse it was not...

2020-04-27 16:43 UTC, weinand commented
Since I'm running out of time, I will release the current PR and postpone @bpasero's suggestion to debt week.

2020-04-27 16:45 UTC, merged

2020-04-28 05:52 UTC, bpasero commented
@weinand sounds good, can you open an issue to remember?

2020-04-28 07:36 UTC, weinand commented
done: #96337